### ISSUE TITLE
Error code 12 when updating the masterlist

### ISSUE THREAD

**Issue by Assmandu** [loot/skyrimse#1]
I created an entry for SkyrimSE in the settings for LOOT.  When I update the masterlist, I get "Error code 12; Failed to update the masterlist. Details: An error occurred while trying to read information on the updated masterlist. If this error happens again, try deleting the ".git" folder in C:\Users\User\AppData\Local\LOOT\SkyrimSE."

**Comment by Ortham** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html). Also, did you try deleting the `.git` folder like the message said?

**Comment by Ortham** [comment]
In fact, you shouldn't have needed to create an entry for Skyrim SE, and the builds that support it don't display error codes in the UI, so closing this as invalid.

**Comment by Assmandu** [comment]
I installed the latest version of LOOT but I don't see a Skyrim Special Edition entry, just the standard Skyrim (TES V: Skyrim) which when selected shows the standard Skyrim modlist.  What am I doing incorrect?  Is there a new build (later than 0.9.2) for SkyrimSE that I don't have access to?

**Comment by Ortham** [comment]
0.9.2 doesn't support Skyrim SE, only unstable snapshot builds do, there hasn't been a release with Skyrim SE support yet.

**Comment by Assmandu** [comment]
Thanks, I found the snapshot builds!
