### ISSUE TITLE
Updated bash tags for Immersive College of Winterhold and its patches

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#1008]
CollegeOfWinterholdImmersive.esp: Actors.ACBS, Actors.AIData, Actors.AIPackages, Actors.CombatStyle, Actors.Stats, C.Encounter, C.Light, C.Music, C.Owner, C.Water, Graphics, Keywords, NPC.Class, Stats (Invent already added)

![image](https://user-images.githubusercontent.com/26516348/73114536-a166a580-3f6f-11ea-8feb-bdbcc8c9900f.png)

CWIEnLFXSEPatch.esp: C.Climate, C.Encounter

![image](https://user-images.githubusercontent.com/26516348/73114596-14701c00-3f70-11ea-9a53-473dd3f97131.png)

CWIBDSPatch.esp: Graphics

![image](https://user-images.githubusercontent.com/26516348/73114630-6153f280-3f70-11ea-8ed9-692a00a9b3fa.png)

ICOW_WICO_Patch: Actors.Stats

![image](https://user-images.githubusercontent.com/26516348/73114678-c90a3d80-3f70-11ea-9de8-07510fdd1a89.png)

ICOW_MOW_Patch.esp: Actors.AIPackages, Actors.CombatStyle, Actors.Stats, Invent, NPC.Class

![image](https://user-images.githubusercontent.com/26516348/73114759-b2181b00-3f71-11ea-8715-a2ee71e6296a.png)

Any suggestions, objections or additions?

**Comment by MacSplody** [comment]
Seems fine to me, but I would check against https://wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html#patch-tags and test with the latest Wrye Bash, as that script is a bit out of date.

**Comment by Sabre142** [comment]
I am using the latest tag generator linked by Sharlikran in the bash discord - https://github.com/TES5Edit/xedit-scripts/blob/master/all/Generate%20Tags%20for%20Wrye%20Bash.pas

It doesn't have the new tags like Keywords and Text however.

Also using latest dropbox Wrye Bash.  And yeah, I reviewed each tag suggestion while also checking the Bash Tags readme.

**Comment by MacSplody** [comment]
Okay, if you're happy with them, then open a pull request and they can be added.
