### ISSUE TITLE
Realistic Water Two + ELFX hardcore

### ISSUE THREAD

**Issue by Harry-894** [loot/skyrimse#1024]
LOOT tells me i need a patch for ELFX but im actually using a patch for hardcore (the regular eflx patch is greyed out in the RWT installer since i only need the hardcore patch)

**Comment by MacSplody** [comment]
@Harry-894 Yeah you're right, it's checking for the wrong plugin name `RealisticWaterTwo - ELFX Hardcore Patch.esp` instead of `Realistic Water Two - ELFX Hardcore Patch.esp`. 
Thanks for reporting it.

**Comment by MacSplody** [comment]
Done in https://github.com/loot/skyrimse/commit/4d35c5a846776c3b234b9770b46b0a822decee47.

**Comment by Harry-894** [comment]
thank you for the update !

**Comment by MacSplody** [comment]
@Harry-894 You're welcome.
