### ISSUE TITLE
 WheelsOfLull.esp - incomplete meta data

### ISSUE THREAD

**Issue by selsie** [loot/skyrimse#1030]
I'm getting the message: 
You seem to be using Beyond Skyrim Bruma and Forgotten City, but you have not enabled a compatibility patch for this mod. A third party patch is available here: Wheels of Lull Forgotten City and Bruma Merged Fix

BUT

I am also running SOT, and there is another merged patch for all three mod available here https://www.nexusmods.com/skyrimspecialedition/mods/19734

Also the notice about an update patch is there, but it is installed already.

**Comment by MacSplody** [comment]
Okay that will need to be updated, thanks for reporting it.

**Comment by MacSplody** [comment]
Done in https://github.com/loot/skyrimse/commit/b5d69d8dcb535788d6f4fa227ef4cd19665738b1.
