### ISSUE TITLE
JK's Skyrim recommended patches for SSE not found

### ISSUE THREAD

**Issue by ghost** [loot/skyrimse#1034]
The following diagnostic for "JK's Skyrim" appears to recommend patch for SE that are not available.
--------------------------------------------------------------------------------------------------
JKs Skyrim.esp  
You seem to be using Bring Out Your Dead, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page.

You seem to be using Cutting Room Floor, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page.

You seem to be using Dragon Bridge, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page.

You seem to be using Ivarstead, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page.

You seem to be using Rorikstead, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page.

**Comment by MacSplody** [comment]
@Sorbe They should be in JK's Skyrim - Arthmoor's Patch Pack under misc files [here](https://www.nexusmods.com/skyrimspecialedition/mods/6289).

![image](https://user-images.githubusercontent.com/1944639/74710359-590e7080-5219-11ea-860d-bcf5c44d33f9.png)

**Comment by ghost** [comment]
You are absolutely correct.  I didn't see them under that pack.  Thanks for the quick reply.

**Comment by MacSplody** [comment]
You're welcome.
