### ISSUE TITLE
ITMs and UDRs in Mihail's Ice Golems (SSE)

### ISSUE THREAD

**Issue by ALEXXiRAPTOR** [loot/skyrimse#1036]
SSEEdit 4.0.3 reports 21 ITMs and 12 UDRs in [Mihail's Ice Golems port](https://www.nexusmods.com/skyrimspecialedition/mods/26185).

![image](https://user-images.githubusercontent.com/61366658/75101530-a892ca80-5592-11ea-808a-5de641547da4.png)

EDIT: I see that it's on the masterlist, but eve when it's uncleaned, it doesn't show any info in LOOT's application itself.

![image](https://user-images.githubusercontent.com/61366658/75101572-57cfa180-5593-11ea-9d94-1400d2251d8c.png)

EDIT 2 (so sorry): Now the info shows up after clicking the update masterlist button, but only shows 20 ITMs. There's one more that was found, so 21 now.

![image](https://user-images.githubusercontent.com/61366658/75101611-d7f60700-5593-11ea-8b7a-ac64aa65d653.png)

**Comment by MacSplody** [comment]
> There's one more that was found, so 21 now.

Just an oversight, the two rounds of cleaning weren't added together.
It's pretty minor but I'll correct that.

**Comment by MacSplody** [comment]
@ALEXXiRAPTOR It's corrected now.
