### ISSUE TITLE
Change Group for Cutting Room Floor

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1040]
![image](https://user-images.githubusercontent.com/1944639/76146207-c7ac5480-6088-11ea-9cf7-3c0c824ff9ed.png)

> And since we're on the subject of CRF anyway, I've been giving some though to having its placement adjusted in the list so that situations like this are easier to resolve via load order.

Moving up to the `default` group as there are a few cases where placing it before most mods doesn't work. Placing it in the `default` group will reduce the chances of a user after creating a sorting error.

Mods that need to be after `Cutting Room Floor.esp`.
  - [Another Sorting Mod](https://www.nexusmods.com/skyrimspecialedition/mods/10/), CRF is a master. Includes Replacer esp for  Book Covers Skyrim (With CRF as a master). `AnotherSortingMod_2017-SSE.esp`, `Book Covers Skyrim.esp`.
  - [Bijin All in One 2019](https://www.nexusmods.com/skyrimspecialedition/mods/11) `Bijin_AIO 2018.esp`
  - [Bijin Warmaidens SE](https://www.nexusmods.com/skyrimspecialedition/mods/1825/) `Bijin AIO.esp`, `Bijin Warmaidens.esp`.
  - [Book Covers Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/901/) `Book Covers Skyrim.esp`.
  - [Complete Alchemy and Cooking Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/19924) `Complete Alchemy & Cooking Overhaul.esp`.
  - [Cosmetic Vampire Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/8695/) `CosmeticVampireOverhaul.esp`
  - [Ethereal Elven Overhaul patches for SSE](https://www.nexusmods.com/skyrimspecialedition/mods/7351/) `ethereal_elven_overhaul.esp`.
  - [Guard Dialogue Overhaul Redux](https://www.nexusmods.com/skyrimspecialedition/mods/20791), [Guard Dialogue Overhaul SE](https://www.nexusmods.com/skyrimspecialedition/mods/22075) `Guard Dialogue Overhaul.esp`. GDO SE needs to be before WACCF, Redux version does not conflict with WACCF.
  - [Immersive College of Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/17004/) `CollegeOfWinterholdImmersive.esp`
  - [Obscure's College of Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/20514) `OCW_Obscure''s_CollegeofWinterhold.esp`.
  - [Palaces and Castles Enhanced SSE](https://www.nexusmods.com/skyrimspecialedition/mods/1819) `Palaces Castles Enhanced.esp`.
  - [Rigmor of Bruma](https://www.nexusmods.com/skyrimspecialedition/mods/5271/) `Rigmor.esp`.
  - [The Choice is Yours](https://www.nexusmods.com/skyrimspecialedition/mods/3850/) `TheChoiceIsYours.esp`.
  - [Winterhold Restored](https://www.nexusmods.com/skyrimspecialedition/mods/12811) `Winterhold Restored.esp`.

- [x] Move mods that need to be after CRF from early group to the default group. And any mods that need to be after those plugins.
- [x] Sort GDO before WACCF with checksum.
- [x] Add afters to ACE for QUARK.
- [x] Move up plugins that were in underrides so they could sort before CRF.

**Comment by Arthmoor** [comment]
This change looks good to me. The Default group was more or less where I figured it should land with the appropriate tweaking.

**Comment by MacSplody** [comment]
Done in https://github.com/loot/skyrimse/commit/d0fcf8e8f4c39f19373b5c196841316c33a923b1.
