### ISSUE TITLE
Cathedral Landscapes esp name change.

### ISSUE THREAD

**Issue by Vaati88** [loot/skyrimse#1044]
Cathedral Landscapes has changed their plugin name from Cathedral - Lightweight Grass Overhaul to Cathedral Landscapes.esp. The metadata for A Quality World Map still says it should load after the former and not the latter causing it to sort improperly.

The metadata for this and any other plugins that should load after Cathedral Landscapes need to be updated to reflect this change in plugin name.

**Comment by Ortham** [comment]
I've moved this to the skyrimse repo as it seems to be specific to Skyrim SE.

**Comment by MacSplody** [comment]
Done in https://github.com/loot/skyrimse/commit/85da03f7dd0c6c2761533a347931d9cfa7e81716.
