### ISSUE TITLE
Immersive Citizens + Dawnstar Arthmoor [flagged incompatable]

### ISSUE THREAD

**Issue by easelgames** [loot/skyrimse#1045]
Latest LOOT version Version 0.15.1 (build 82c756e1)

![LOOT_hLL0efdJEY](https://user-images.githubusercontent.com/46850157/73183969-ad767280-40e9-11ea-90e1-664486194e22.png)

This is contrary to the mod page for Dawnstar by Arthmoor who says to simply load IC BEFORE.

![chrome_iCvh7stJ2F](https://user-images.githubusercontent.com/46850157/73184049-cc750480-40e9-11ea-9af4-93fb2ec71b0e.png)

I assume this is the case for all his other mod expansions to vanilla citys no? If this is incorrect however, please close.
Dawnstar by Arthmoor: https://www.nexusmods.com/skyrimspecialedition/mods/13607

**Comment by easelgames** [comment]
Rechecking things, it seems loot is NOT putting his mods AFTER Immersive Citizens.. HALF of them are being placed before IC.

**Comment by Ortham** [comment]
I've moved this to the skyrimse repository as it seems to be specific to that game.

**Comment by MacSplody** [comment]
> After seen this message of his, I've tried and have been playing with this combination for a year now, never found anything game breaking or had anything that I had to resort to console commands to fix in Danwstar.
> Is there a message standard for "Minor inconsistances or incompatibilties"? I find the current message a bit misleading, as it suggests game breaking problemns.

Being incompatible doesn't mean it has to be game breaking, more like mod breaking.
The whole goal of ICAIO is for immersion, and teleporting or stuck characters doesn't really help acheive that.
