### ISSUE TITLE
Outdated Patch Suggestions

### ISSUE THREAD

**Issue by Vaati88** [loot/skyrimse#1049]
Several of Quinn's patcher patches for AI Overhaul and various other mods are outdated and shouldn't be recommended anymore. Namely the Pandorable AI Overhaul patches. More up-to-date patches can be found on each of the Pandorable mods' respective pages.

**Comment by MacSplody** [comment]
@Vaati88 Removed QUASIPC messages Pandorable's NPC in https://github.com/loot/skyrimse/commit/40a2cf5722ef200ba7aed7febbdc8b889c64a2bb. 
I'll leave this open in case any other QUASIPC messages need to be removed.

**Comment by Vaati88** [comment]
The RS Children + AI Overhaul patch in QUASIPC is also outdated. The message for that should also be removed.
