### ISSUE TITLE
Peacekeeper Armor cleaning entry

### ISSUE THREAD

**Issue by yggdrasil75** [loot/skyrimse#1060]
- name: 'peacekeeper armour1.esp'
    dirty:
      - <<: *quickClean
        crc: 0x121EAFD5
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 1
    clean:
      - crc: 0xA9679354
        util: 'SSEEdit v4.0.3'

also, bash:relev

**Comment by MacSplody** [comment]
@yggdrasil75 Do you have a link for that plugin?
I can only find `Peacekeeper Armour.esp` at [Peacekeeper Armour Special Edition port](https://www.nexusmods.com/skyrimspecialedition/mods/20068).

**Comment by yggdrasil75** [comment]
https://bethesda.net/en/mods/skyrim/mod-detail/4085096
I installed a bethnet mod to show how to properly do it with a mod manager in a video.

**Comment by MacSplody** [comment]
Done in https://github.com/loot/skyrimse/commit/d8c91fe8a3a9687751c15c61ddec38bb04710911.
