### ISSUE TITLE
Skyrim 3D Signs Wild Edit

### ISSUE THREAD

**Issue by yggdrasil75** [loot/skyrimse#1072]
[Skyrim 3D Signs](https://www.nexusmods.com/skyrimspecialedition/mods/21338)

`S3DSigns.esp` contains a wild edit in 001a277 (it is an itpo that cant be cleaned as an itm even though it should be an itm)

**Comment by MacSplody** [comment]
@yggdrasil75 Done, Thanks for reporting it.
