### ISSUE TITLE
3DNPCs Nexus + LAL Patch - Masterlist Revision Request

### ISSUE THREAD

**Issue by easelgames** [loot/skyrimse#1083]
Loot needs a masterlist warning for users having both [Live Another Live](https://www.nexusmods.com/skyrimspecialedition/mods/272) + [3DNPCs](https://www.nexusmods.com/skyrimspecialedition/mods/29194)... There is a patch on the 3DNPCs Nexus page. This is suggested since using said patch requires a new game.

<img width="617" alt="live another life patch" src="https://user-images.githubusercontent.com/46850157/78862262-ef366a00-7a04-11ea-88cf-f2d58c978a37.png">

**Comment by MacSplody** [comment]
> 
> 
> Loot needs a masterlist warning for users having both [Live Another Live](https://www.nexusmods.com/skyrimspecialedition/mods/272) + [3DNPCs](https://www.nexusmods.com/skyrimspecialedition/mods/29194)... There is a patch on the 3DNPCs Nexus page. This is suggested since using said patch requires a new game.
> 
> <img alt="live another life patch" width="617" src="https://user-images.githubusercontent.com/46850157/78862262-ef366a00-7a04-11ea-88cf-f2d58c978a37.png">

Yeah that seems fine, though there's no way to hide the message.
And a new game warning message could be used for other plugins.

**Comment by MacSplody** [comment]
@easelgames Done in https://github.com/loot/skyrimse/commit/44e211399886a17ab52c645f02ba9b4c91deb282.

**Comment by easelgames** [comment]
New information should note that if on existing save nothing game breaking, but patch may not work to its full potential. Thanks Cpt!

<img width="882" alt="live another life patch 2" src="https://user-images.githubusercontent.com/46850157/78890452-afd34200-7a33-11ea-8685-e331b99f0d09.png">
