### ISSUE TITLE
SkyVRaan Shimmering Waters Plugin Order

### ISSUE THREAD

**Issue by Wolfman5750** [loot/skyrimse#1087]
I've created a mod called SkyVRaan for Skyrim VR. In VR, the water reflections have been disabled, which generally looks very bad. I have a plugin named Cubemapenabler.esp that defines a cubemap for exterior water the same way it can be defined for an interior cell. I do this by assigning XWEM parameter for exterior worldspaces and every cell in those worldspaces.

Unfortunately, when assigning cubemaps in this way, you are limited to two water types the same way that an interior cell would be. If there are more than two watertypes defined, it causes instability and crashes. For this reason, cubemapenabler.esp also changes all watertypes to defaultwater. 

currently cubemapenabler is sorted very high up in the load order by loot. It should be loaded after bash and smash patches, but before DynDOLOD or Occlusion. My instructions on my mod page are to put cubemapenabler after Bash and Smash, and then run DynDOLOD and generate xLODGEN Occlusion with cubemapenabler enabled.

If Bash or Smash patches are loaded after cubemapenabler, or run with cubemapenabler active, then they will revert my watertype changes and cause crashes.

Please let me know if you would like more information. My mod page is:

https://www.nexusmods.com/skyrimspecialedition/mods/30571

**Comment by MacSplody** [comment]
Okay so I've tested it out with Wrye Bash and it seems to work fine if  a `C.Water` tag has been added. RWT would still revert some changes if it's after `CubemapEnabler.esp`, as it also has a `C.Water` tag. Could be resolved with an after or a patch for RWT.

The WRLD and persistent records are the main issue, as bash can't handle those correctly.
I'd recommend having an extra plugin with only the WRLD & persistent record changes that could be placed after the bashed patch. Now even with that, it would still conflict with any mods changing WRLD records, such as map markers, Paper maps, lighting enhancers, music mods, no grass plugins.

~- [ ] Add `C.Water` bash tag suggestion.~

**Comment by Wolfman5750** [comment]
Regarding the Bash Patch, what would be the difference between loading cubemapenabler after the bashed patch, and running it through WryeBash with a patch for RWT that would also need to be loaded after the bashed patch? With a cubemap defined for an exterior worldspace, that worldspace is limited to two watertypes, one for the LOD and one for the loaded cells. If Bash reverts my watertype changes, it will cause repeatable CTDs. This is the reason I have instructed people to load them after Bash and Smash.

I agree with the WRLD records being an issue. At some point, I plan to make an xEdit Script to automate this to hopefully carryover those changes, but at the moment it's semi-auto.

**Comment by MacSplody** [comment]
> what would be the difference between loading cubemapenabler after the bashed patch

Any mods that modify cells would be reverted by `CubemapEnabler.esp`.

![image](https://user-images.githubusercontent.com/1944639/79738677-f870e200-82f4-11ea-8716-f9df38e7c86a.png)

Having reviewed the results of the bashed patch a second time, even that won't patch it correctly.
It's just going to need a lot of patches, even if it is placed late.

![image](https://user-images.githubusercontent.com/1944639/79744921-23f8ca00-82ff-11ea-8635-94bd35f21c9b.png)

[SkyVRaan - USSEP Patch.zip](https://github.com/loot/skyrimse/files/4503017/SkyVRaan.-.USSEP.Patch.zip)

[SkyVRaan - Cutting Room Floor Patch.zip](https://github.com/loot/skyrimse/files/4503303/SkyVRaan.-.Cutting.Room.Floor.Patch.zip)

[SkyVRaan - Legacy of the Dragonborn v5 Patch.zip](https://github.com/loot/skyrimse/files/4503306/SkyVRaan.-.Legacy.of.the.Dragonborn.v5.Patch.zip)

[SkyVRaan - Obscure's College of Winterhold Patch.zip](https://github.com/loot/skyrimse/files/4503308/SkyVRaan.-.Obscure.s.College.of.Winterhold.Patch.zip)

[SkyVRaan - Dawnguard Map Markers Patch.zip](https://github.com/loot/skyrimse/files/4503310/SkyVRaan.-.Dawnguard.Map.Markers.Patch.zip)

Edit: And I'm assuming the default water flow is important, not just the cubemap texture?

**Comment by Wolfman5750** [comment]
Thank you. I've started making patches, and will definitely use the ones you posted.

you're correct. Unfortunately, the default water flow is also important.  If you have a bunch of these installed, you might need patches for the patches haha. I think a xedit script to generate the patches will probably be needed eventually, but I'm still thinking through how to do that. I don't add the cubemap to every worldspace, just the ones with enough water to make sense. I also don't add it to places that already have one, like Apocrypha.

**Comment by MacSplody** [comment]
@Wolfman5750 The rules are added now, I'd make sure any users know they'll have to patch their modlist for it. No way around it really, but it's fairly straight forward to patch.
Also any patches for `CubemapEnabler.esp` will need it added as a master, otherwise LOOT won't sort them correctly.

**Comment by Wolfman5750** [comment]
Thanks, I appreciate it. I'll make sure to make a note on my mod page.
