### ISSUE TITLE
Cyclic Error “CACO and Better Quest Objectives”

### ISSUE THREAD

**Issue by TURCOTTEisBORAT** [loot/skyrimse#1091]
![E7FFCE94-9B0D-4BD8-B4D7-E67BDFB78B72](https://user-images.githubusercontent.com/63488040/79035746-08ffba80-7b87-11ea-9c4e-99eb73d896f5.jpeg)

Issue between CACO and EBQO, thank y’all for the help and taking the time to make this great tool.

**Comment by MacSplody** [comment]
Hi @TURCOTTEisBORAT 
I can't replicate that sorting error, you'll need to provide some more info, see [How To Report Issues Helpfully](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

It seems to be a user rule so can you provide your `userlist.yaml`?
You'll find it under `C:\Users\%yourusername%\AppData\Local\LOOT\Skyrim Special Edition`

![image](https://user-images.githubusercontent.com/1944639/79041732-e783ea80-7be9-11ea-90b3-f39d7d65d9d8.png)

**Comment by TURCOTTEisBORAT** [comment]
[userlist.txt](https://github.com/loot/skyrimse/files/4465158/userlist.txt)
Here it is, it would not let me upload the yaml format so I had converted to txt. If this present an issue please let me know. I have cleared all user meta data a couple weeks ago but will wait for further comment. Again thank y'all for the time and effort put forth.

**Comment by MacSplody** [comment]
> [userlist.txt](https://github.com/loot/skyrimse/files/4465158/userlist.txt)
> Here it is, it would not let me upload the yaml format so I had converted to txt. If this present an issue please let me know. I have cleared all user meta data a couple weeks ago but will wait for further comment. Again thank y'all for the time and effort put forth.

Okay there are no rules in that, so that isn't the issue.
Are you merging any plugins?

**Comment by TURCOTTEisBORAT** [comment]
None at all. I have had these plugins for a while and have not had this issue until last night.

**Comment by MacSplody** [comment]
Please **enable** debug logging in LOOT settings and upload a full _LOOTDebugLog.txt_.

It will only be of use if you are still receiving the error.

![image](https://user-images.githubusercontent.com/1944639/67115390-ff982580-f1d5-11e9-82f1-9202da269976.png)

**Comment by TURCOTTEisBORAT** [comment]
[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/4465199/LOOTDebugLog.txt)
Here is the debug log from my most recent attempt. Have to go at the moment but will be back on later and can continue helping/being helped then. Thank you for your time so far, it is greatly appreciated.

**Comment by MacSplody** [comment]
> Details: Cyclic interaction detected: Complete Alchemy & Cooking Overhaul.esp --[Master]-> **Radiant Blocker Patch.esp --[Master]-> QuestsAreInSkyrimUSSEP.esp** --[Masterlist Load After]-> BetterQuestObjectives.esp --[Masterlist Load After]-> BetterQuestObjectives-DBForevertoMisc.esp --[Tie Break]-> BetterQuestObjectives.esp --[Masterlist Load After]-> Complete Alchemy & Cooking Overhaul.esp

Okay so `Radiant Blocker Patch.esp` is a master for your version of `QuestsAreInSkyrimUSSEP.esp`.
Where did you download that version of `QuestsAreInSkyrimUSSEP.esp` from?

**Comment by TURCOTTEisBORAT** [comment]
Off the LexyLotD modpage saw it as an improved version. Will try the real vanilla one when back home and let you know how that turns out. Thank you for going through my ridiculously long debug log. I really appreciate your time.

**Comment by TURCOTTEisBORAT** [comment]
Ran back real quick, but switching her version out for the regular plugin has resolved my issue having just been able to successfully sort my load order. Thank you for helping me with my trivial issue. I appreciate the help and the great tool you help maintain for the rest of us.
