### ISSUE TITLE
BetterQuestObjectives-EFFPatch.esp not loaded below EFFDialogue.esp

### ISSUE THREAD

**Issue by Crestfall17** [loot/skyrimse#1093]
BetterQuestObjectives-EFFPatch.esp not loaded below EFFDialogue.esp.

In fact, all the BetterQuestObjectives patches doesn't seem to have conditions to load below the mods they patched.

I will submit a pull request soon.

**Comment by MacSplody** [comment]
> `BetterQuestObjectives-EFFPatch.esp` not loaded below `EFFDialogue.esp`.

Yeah it's because `EFFDialogue.esp` isn't a master for the patch.

![image](https://user-images.githubusercontent.com/1944639/79075790-c952e300-7cec-11ea-8f26-ad04a1e9c8cc.png)

> In fact, all the BetterQuestObjectives patches doesn't seem to have conditions to load below the mods they patched.

If a patch has the correct masters it will sort after them and doesn't need to be added as metadata.

**Comment by Crestfall17** [comment]
Ah didn't know that. Still new in this thing.

**Comment by MacSplody** [comment]
A _requires_ or _after_ should still be added to `BetterQuestObjectives-EFFPatch.esp`
for `EFFDialogue.esp`.

![image](https://user-images.githubusercontent.com/1944639/79076033-bb05c680-7cee-11ea-859b-10c05fac8b8f.png)

**Comment by Crestfall17** [comment]
Ah yeah dumbass me didn't notice there are 2 EFF .esp(s). So yeah reopen it.
