### ISSUE TITLE
Warning about LotD patch for Jaysus swords even though patch is installed

### ISSUE THREAD

**Issue by zarantha** [loot/skyrimse#1094]
I have the 1.8 craft only version of Jaysus swords (Jswords.esm) and the Legacy of the Dragonborn patch for the craft only version from the LotD Patches (DBM_JaysusSwords_Patch.esp)

Still getting this message after sorting:

JSwords.esm 14.0 3E768974

You seem to be using Legacy of the Dragonborn, but you have not enabled a compatibility patch for this mod. A third party patch is available here: Legacy of the Dragonborn Patches (Official)

**Comment by MacSplody** [comment]
@zarantha The patch name must have changed at some point, `DBM_JaysusSwords_Patch.esp` used to only be for the full version. `DBM_JaysusPatch.esp` was the old name for the craft only version patch.

- [x] Update LotD patch condition for Jaysus swords Craft Only.
