### ISSUE TITLE
Guards Armor Replacer should be loaded after Unleveled Items

### ISSUE THREAD

**Issue by Crestfall17** [loot/skyrimse#1108]
(or any type of mod that unlevels items)
[Guards Armor Replacer](https://www.nexusmods.com/skyrimspecialedition/mods/22671)

![Screenshot_28](https://user-images.githubusercontent.com/48683189/79694633-c8e1bb80-829b-11ea-8c0f-e1a31268a4a4.png)
Guards Armor Replacer has it's own Solitude Shield leveling list, replacing it with a whole set of armor.

Actually, this might be better as just a note attached to the esp.

**Comment by MacSplody** [comment]
> Guards Armor Replacer has it's own Solitude Shield leveling list, replacing it with a whole set of armor.
> Actually, this might be better as just a note attached to the esp.

@Crestfall69 Done. And the after was correct, there's no conflict with Guards Armor Replacer after Unleveled Items.
