### ISSUE TITLE
Immersive College Of Winterhold + ELFX Patch (flag if both exist but no patch)

### ISSUE THREAD

**Issue by easelgames** [loot/skyrimse#1117]
Not sure if this is the right place... but upon playing with ICOW + ELFX I noticed all kinds of flickering.. This turned out to be because I missed the ELFX patch included in ICOW. I'd ask to flag message if loot detects you do not have this patch. Thanks. (adding said patch post save works in my limited testing)

**Comment by MacSplody** [comment]
@easelgames Done, I also added a few of the other patches.
