### ISSUE TITLE
Summermyst + WACCF - Recommend different patch.

### ISSUE THREAD

**Issue by easelgames** [loot/skyrimse#1136]
LOOT should recommend users change from https://www.nexusmods.com/skyrimspecialedition/mods/19500

To this: 
https://www.nexusmods.com/skyrimspecialedition/mods/34547?tab=description&BH=0

See post by Mod Author. (I'm aware favoring mods is not LOOTs job, however in the case of mods with better corrections, should be made noted..) [Can be done by checking ESP name no?]

<img width="975" alt="summermyst waccf patch" src="https://user-images.githubusercontent.com/46850157/81322638-49f1ce80-9062-11ea-9d6e-95e1ed1c64aa.png">

**Comment by MacSplody** [comment]
> LOOT should recommend users change from https://www.nexusmods.com/skyrimspecialedition/mods/19500
> To this:
> https://www.nexusmods.com/skyrimspecialedition/mods/34547?tab=description&BH=0
> See post by Mod Author. (I'm aware favoring mods is not LOOTs job, however in the case of mods with better corrections, should be made noted..) [Can be done by checking ESP name no?]

Yeah I think it would be best to avoid saying one patch is better than the other.
However the existing patch message can be updated to link to that patch instead.
It will still check for the previous patch since users might prefer to use it.

**Comment by MacSplody** [comment]
@easelgames Link has been changed. I've also added bash tags to the patch.
