### ISSUE TITLE
LOOT won't sort Skyrim SE

### ISSUE THREAD

**Issue by interstellar-villain** [loot/skyrimse#114]
[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/1938391/LOOTDebugLog.txt)

I am in the beginning of Modding Skyrim SE (Using Mod Organizer 2.1.2 and LOOT 0.12.5), I have run LOOT and it simply doesn't do anything to my load order. Obviously, I have manually moved some plugins and it doesn't help. The ONLY thing that makes it do any replacement is between:
**Unofficial Skyrim Special Edition Patch**
and
**Skyrim Project Optimization SE**   (Probably because this is an ESM file...)

Please help!

**Comment by Ortham** [comment]
There aren't any errors in the log, and you don't have many plugins, so I'd say probably nothing happens because LOOT doesn't think anything needs to happen.

**Comment by interstellar-villain** [comment]
But if you'll look on the order - it's wrong. I have manually manipulated
it, and still loot does, nothing.

**Comment by MacSplody** [comment]
> Dragon Stalking Fix.esp
> HornsAreForever.esp
> Better Skill and Quest Books Names SE.esp
> SkyUI_SE.esp
> Point The Way.esp
> Raven Rock - Fix Exit on Horseback.esp
> AMatterOfTime.esp
> FloraRespawnFix.esp 
> CT_AskToShowRoom.esp
> Lock_Overhaul.esp
> Simple AUA.esp

Out of those mods none of them conflict, you can sort them anyway and they will work correctly.
Try adding some more mods and then sorting, I'd suggest cutting room floor or alt start.

**Comment by Ortham** [comment]
> But if you'll look on the order - it's wrong.

Why's it wrong?

**Comment by interstellar-villain** [comment]
It is probably my bad understanding of how the sorting works, I'll try what @CptMcSplody said...

**Comment by MacSplody** [comment]
Marking as closed, as I understand it they thought loot would sort the above plug-ins. But there is no reason to sort those particular mods, regardless of how the order is manually changed.

@Ozymandias-king if you have any further issues with the above scenario please let us know.
