### ISSUE TITLE
Enhanced Blood Textures patch for Audio Overhaul Skyrim

### ISSUE THREAD

**Issue by HomerSlated** [loot/skyrimse#1164]
The latest Enhanced Blood Textures patch for [Audio Overhaul Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/12466) is now called `AOS_EBT Patch.esp`, but LOOT expects to find `Audio Overhaul Skyrim - Enhanced Blood Patch.esp`, so issues a warning that the patch was not found.

**Comment by MacSplody** [comment]
@HomerSlated Done, thanks for reporting it.
