### ISSUE TITLE
Legacy of the Dragonborn JKSkyrim/Dawn of Skyrim merged patch not recognized

### ISSUE THREAD

**Issue by HomerSlated** [loot/skyrimse#1165]
[Legacy of the Dragonborn Patches (Official)](https://www.nexusmods.com/skyrimspecialedition/mods/30980) provides the merged patch `DBM_JKSkyrim_DawnOfSkyrimDC_Patch.esp` if both JKSkyrim and Dawn of Skyrim are installed, but LOOT only recognizes either `DBM_JKSkyrim_Patch.esp` or `JKs Skyrim_Dawn of Skyrim_Patch.esp`, so issues a warning that a patch is needed.

**Comment by MacSplody** [comment]
@HomerSlated Done, thanks for reporting it.
