### ISSUE TITLE
A Quality Worldmap Luminosity Patch Sorting

### ISSUE THREAD

**Issue by bartmoss** [loot/skyrimse#1173]
Alright, I don't want to mess anything up, and the documentation says to raise an issue instead in that case, so I hope this is OK.

The "Quality Worldmap Luminosity Patch" must load after A Quality Worldmap, but as it only modifies records from that mod - and not Luminosity - it doesn't matter where it loads in relation to Luminosity. Currently, loot doesn't sort the patch correctly.

Mod URL:
https://www.nexusmods.com/skyrimspecialedition/mods/30162

Display Name:
"Luminosity - A Quality Worldmap Compatibility Patch"

Mod file name:
"maplightfix.esp"

Load after:
"icepenguinworldmapclassic.esp"
"IcePenguinWorldMapPaper.esp"
"IcePenguinWorldMap.esp"

I hope this is all you need, let me know if I can help in any other way..

**Comment by MacSplody** [comment]
@bartmoss Done, thanks for reporting it.
