### ISSUE TITLE
Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.

### ISSUE THREAD

**Issue by LittleDyke** [loot/skyrimse#119]
[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/1977083/LOOTDebugLog.txt)

im on win 10 and any solution given in https://github.com/loot/loot/issues/882 didn't work for me at all

**Comment by WrinklyNinja** [comment]
```
[03:55:48.493487] [error]: Exception while executing query: Git operation failed. Details: -1; failed to send request: The operation timed out
: libgit2 error
```

Does this consistently happen? Did you file this issue from the same PC that you ran LOOT on?

**Comment by CptMcSplody** [comment]
@LittleDyke Any update on this issue?
Closing, will reopen if there is any update.
