### ISSUE TITLE
Aurlyn Dawnstone & Tournament of the Ten Bloods compatibility info out of date.

### ISSUE THREAD

**Issue by SteveTownsend** [loot/skyrimse#1194]
[Aurlyn Dawnstone - The Reclusive Philosopher](https://www.nexusmods.com/skyrimspecialedition/mods/9536)
[Artifacts - The Tournament of the ten Bloods](https://www.nexusmods.com/skyrimspecialedition/mods/15264)
#801 is out of date

There is an SSE patch for this incompatibility on Aurlyn's webpage now under [Addons, v7.3.0](https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=152518&nmm=1&game_id=1704).
The patch installs as `ATOT10B patch.esp`. I have not tested yet, rebuilding Load Order right now.

Edited: Updated formatting.

**Comment by MacSplody** [comment]
@SteveTownsend Done, thanks for reporting it.
