### ISSUE TITLE
Using LOOT with Vortex

### ISSUE THREAD

**Issue by shadeshadowwolf** [loot/skyrimse#1196]
It keeps saying that mods are not installed or active for skyrim se, and such that are active, installed etc. Reinstalling them does not fix it, disabling reenabling them does not help either as well as purging mods with nexus and then redeploying em. Its even giving me a message saying this. You have a normal plugin and at least one light master sharing the FE load order index. Deactivate a normal plugin or all your light masters to avoid potential issues. I have tried to figure out what one it was but nothing worked every fe i could disable didn't do jack to change that message.  I have no idea even vortex has been giving me odd glitches today so no clue what's going on.

**Comment by MacSplody** [comment]
> You have a normal plugin and at least one light master sharing the FE load order index. Deactivate a normal plugin or all your light masters to avoid potential issues. I have tried to figure out what one it was but nothing worked every fe i could disable didn't do jack to change that message.

It's not one single plugin, it's counting your total number of plugins.
The limit is 255 for regular plugins, i.e. ones not flagged as an ESL.
All ESL flagged plugins use one of these regular plugin slots.

>  I have no idea even vortex has been giving me odd glitches today so no clue what's going on.

You don't need to use the LOOT application with Vortex as it has most of LOOTs features built into it.
If you have any questions about using Vortex, you'll need to ask on their support page.
