### ISSUE TITLE
SKSE 64 update 2.0.17->2.0.19 renders mods incompatible

### ISSUE THREAD

**Issue by luotinen** [loot/skyrimse#1292]
This not really a bug with LOOT, but I have this message appearing:
"It appears you do not have the latest version of Script Extender (SKSE 64). Some mods may require functionality added in the latest version of Script Extender (SKSE 64) to work."

However, if I do update SKSE then the mods stop working. So the text is not very helpful.

SKSE 2.0.17 works. SKSE 2.0.19 does not.

**Comment by MacSplody** [comment]
> However, if I do update SKSE then the mods stop working. So the text is not very helpful.

It's only there to inform users that a newer version is available.
What they do with that info is up to them, it's not forcing anyone to update.
If the older version is working for your setup then stick with it.
