### ISSUE TITLE
LOOT 13.1 Cyclic Interaction

### ISSUE THREAD

**Issue by missnasty07** [loot/skyrimse#130]
[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/2066211/LOOTDebugLog.txt)

It says a cyclic interaction detected between RealisticWaterTwo++Verdant+Patch.esp and ELE_SSE.esp. Back cycle: ELE_SSE.esp, Qw_ELE_CRF Patch.esp, RealisticWaterTwo.esp, RealisticWaterTwo++Verdant+Patch.esp.

**Comment by Ortham** [comment]
Try using the metadata editor to put `Qw_ELE_CRF Patch.esp` in the `Immersive Citizens` group or `RealisticWaterTwo+-+Verdant+Patch.esp` in the `Alternate Start` group.

**Comment by missnasty07** [comment]
Okay the Qw_ELE_CRF Patch.esp change to immersive citizens group does not work, still gives error, but the RealisticWaterTwo++Verdant+Patch.esp changed to Alternate Start group worked.
Thank you for the help!
