### ISSUE TITLE
Default ordering for mods

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1311]
_Originally posted by @swarnadeep in https://github.com/loot/loot/issues/413#issuecomment-696116141_

Hi, I really didn't want to necro a closed issue like this, but I wanted to point out that the default load order in loot for Relationship Dialogue Overhaul (RDO), Cutting Room Floor (CRF), Guard Dialogue Overhaul (GDO), Weapons Armor Clothing and Clutter Fixes (WACCF) and Alternate Start, Live another life (ASLAL) have the wrong load order. The correct order is 
-RDO
-CRF
-GDO
.
.
-WACCF
.
.
-ASLAL

---

Order at the moment for reference.
-WACCF
-CRF
-GDO (Order with WACCF depends on the version of GDO you're using)
-ASLAL
-RDO

**Comment by MacSplody** [comment]
Just a brief list.
Apologies for the layout, but lookng at the order of a few mods in a vacuum,
Isn't going to explain why some mods are sorted the way they are.

---

..Audio Overhaul Skyrim.
..
..??(Weather mods)
..
-ELFX Main plugin
-ELFX No Player Homes addon
..
-Relighting Skyrim
-Relighting Skyrim No Player Homes addon
..
..??(All vanilla player home mods)

..
-Quests Are in Skyrim
-Better Quest Objectives (Can be anywhere, earlier is safer)
..
..??(All mods that change Vanilla quests)

..
-Enhanced Landscapes
-Landscape Fixes
..??(Any quest/location mod that changes landscapes.)
..
-Touring Carriages
..
..??(Anything that would conflict with ICAIO. Vanilla player home exteriors, Idle markers, navmesh, the list goes on.)
-Immersive Citizens
..
-FCO - Follower Commentary Overhaul.esp
-AmazingFollowerTweaks ~ _FCO Breaks AFT, no patch available atm._
-Immersive Weapons
..
-RDO ~ _After ICAIO, AFT, FCO_
..
-CRF
..
-AI Overhaul
..??(Any mods that change NPC Appearance.)
..
-Convenient Horses
-Immersive Horses
-nwsFollowerFramework.esp
..
-GDO
..
-WACCF
..??(All mods that modify vanilla weapons & armour.)
-Joy of Perspective
-QUARK Amulets Show On Everything
..
-AnotherSortingMod_2017-SSE.esp
-iNeed - Extended.esp
..
-WACCF Armor and Clothing Extension
..
-Book Covers (ASM Replacer has CRF as a master)
-The Choice is yours
..
..??(All mods that modify leveled lists, containers.)
-MLU
-Zim's Immersive Artifacts
-CCOR
-CACO
-Hunterborn (This could be placed earlier than CACO, a newer patch means the order doesn't matter.)
-Realistic Needs and Diseases
..
-Ordinator
-Requiem
-Sacrosanct
-Better Vampires
..
..??(All mods that change the same Vanilla quests as ASLAL)
-ASLAL
-**Immersive Citizens** Actual Position
-Open Cities
-**Immersive Citizens** Requested Position
..
..??(Cell Settings Only, Regions, encounter zones, music, lighting etc.)
-Missing Encounter Zones
-Unique Region Names
-Lighting Enhancers (ELE, ELFX Enhancer, ELFX Hardcore)
-No grass in Caves
-Realistic Water Two
..
..??(WRLD Settings Only)
-Map Markers
-Paper Maps
-No grass in Cities

**Comment by swarnadeep** [comment]
Well yes, apologies for not giving a more detailed explanation. Truth is, I myself am unsure as to what the "right" order is. The authors of RDO, GDO and ASLAL said that this should be the correct load order. And i couldn't for the life of me make a Metadata edit rule in loot that would let me load RDO early.... Cos essentially it's impossible for me to edit the default plugin Metadata rules, which causes a cyclic conflict. I scoured the net, and decided to post here as a last ditch effort to hope atleast the guys making the loot rules are aware of this issue and can speak with those mod authors directly to confirm.

**Comment by MacSplody** [comment]
@swarnadeep Update your masterlist, the RDO after for ASLAL was removed.
