### ISSUE TITLE
Edits to Worldspace Object Bounds (NAM9 and NAM0)

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1317]
Opening this as I've been thinking about adding a message for these types of edits.
I don't have a message in mind as yet, so I'm just putting down what notes I have so far.

> **Worldspace Records**
> 
> NAM0, NAM9 subrecords: Used to determine the in-game cell dimension of a worldspace. These have been confirmed to be exempt from the Rule of One. *ANY* mod making changes to these sets of values will have those changes propagated into the game WITHOUT conflict management. Be aware of this if you are running two mods together which intentionally change these values for a worldspace. The outcome will not be predictable and you may end up with a worldspace size much larger than you're expecting. **This can lead to huge amounts of stuttering in the game that have no other identifiable cause.** If you have mods which are altering vanilla worldspaces, chances are these edits were NOT intentional unless the author specifically states they have done so. They can appear in a mod unintentionally and the author may not be aware it has happened.

> This is important. Some mods like ELFX - Exteriors *do* change the Worldspace object bounds...doing a search on the Nexus forum topic, the author [url=https://forums.nexusmods.com/index.php?/topic/834995-enhanced-lights-and-fx/?p=26495904]states[/url] that these edits were NOT intentional. If this is the case with just this single mod I looked at, other mods may have the same issue.

> As these records do not follow the rule of one, they need to be corrected for any mods that do this (unless by chance it was an intentional edit - likely it was not). It is not sufficient to forward the correct object bounds in a patch. You must correct it so that every mod for a particular Worldspace record shows the same NAM9 and NAM0 values.

**Source**
[Nebulous112 forum.step-project.com.](https://forum.step-project.com/topic/11024-worldspace-edits-nam9-and-nam0-object-bounds/)
And
[TES5Edit - Records that merge at runtime](https://www.afkmods.com/index.php?/topic/3940-skyrim-tes5edit-records-that-merge-at-runtime/)

---

Plugins that edit WRLD object bounds

[Perfect Terrain LOD](https://www.nexusmods.com/skyrimspecialedition/mods/39563) (Tamriel)

[EEKs Immersive Whiterun](https://www.nexusmods.com/skyrimspecialedition/mods/31214) 
`EEKs Immersive Whiterun.esp` JK Skyrim version (MarkarthWorld)

[Enhanced Lights and FX](https://www.nexusmods.com/skyrimspecialedition/mods/2424/)
`ELFX - Exteriors.esp` (SolitudeWorld)

[Enhanced Solitude](https://www.nexusmods.com/skyrimspecialedition/mods/27816)
`Enhanced Solitude SSE.esp` (SolitudeWorld)

[Enhanced Solitude Docks](https://www.nexusmods.com/skyrimspecialedition/mods/28349)
`Enhanced Solitude Docks.esp` (SolitudeWorld)
[
Interesting NPCs SE (3DNPC)](https://www.nexusmods.com/skyrimspecialedition/mods/29194)
`3DNPC.esp` (BloatedMansGrottoWorld)

[Holds The City Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/10609) (Tamriel)
`Holds Complete`
![image](https://user-images.githubusercontent.com/1944639/97780349-080e9480-1b7c-11eb-9909-be86be6642e4.png)

**Comment by sibir-ine** [comment]
Found some patches that do this:

[JKs Skyrim - AI Overhaul SSE Patch](https://www.nexusmods.com/skyrimspecialedition/mods/34194/)
`JKs Skyrim - AI Overhaul Patch.esp` (MarkarthWorld)

[JK's Skyrim - Open Cities Patch](https://www.nexusmods.com/skyrimspecialedition/mods/6289/) (on the JK's Skyrim page)
`JKs Skyrim_Open Cities_Patch.esp` (MarkarthWorld)

Weird that multiple plugins based off JK's Skyrim have these edits in MarkarthWorld, but JK's Skyrim doesn't.

**Comment by MacSplody** [comment]
> Weird that multiple plugins based off JK's Skyrim have these edits in MarkarthWorld, but JK's Skyrim doesn't.

If I recall correctly an older version did have those edits.

**Comment by MacSplody** [comment]
Closing for now.
I'd still need to do some testing to confirm if there even is an issue with these changes.

**Comment by Arthmoor** [comment]
I realize this issue is marked as closed, but what testing are you looking for? The NAM0/NAM9 issue is something I ran into directly in my Storefront mod when the values got ghost edited by the CK without my knowing. People reported massive lag and stuttering shortly after the release it was in and once I restored the WRLD record back to what it was supposed to be, the problem went away.

**Comment by MacSplody** [comment]
> I realize this issue is marked as closed, but what testing are you looking for? The NAM0/NAM9 issue is something I ran into directly in my Storefront mod when the values got ghost edited by the CK without my knowing. People reported massive lag and stuttering shortly after the release it was in and once I restored the WRLD record back to what it was supposed to be, the problem went away.

I mainly wanted to test for why the CK changes the value in the first place.

[Holds The City Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/10609) Holds SSE Complete - 0.0.9

`Holds.esp` changes `NAM0 - Min X` in the Tamriel worldspace from -57 to -60.

![image](https://user-images.githubusercontent.com/1944639/107199513-715d3980-69ee-11eb-8332-a5ee9dcf1839.png)

It seems to be because two new cell records are added outside the bounds of the worldspace.
I'd assume it could also happen if a persistent object was placed outside the worldspace bounds.

![image](https://user-images.githubusercontent.com/1944639/107200136-37d8fe00-69ef-11eb-9486-ec2166e3b719.png)
![image](https://user-images.githubusercontent.com/1944639/107200415-943c1d80-69ef-11eb-90e2-30fb89113094.png)

Yeah, same thing is happening in the Whiterun Worldspace for that file.

![image](https://user-images.githubusercontent.com/1944639/107201484-f1849e80-69f0-11eb-85f4-9f5734256994.png)
![image](https://user-images.githubusercontent.com/1944639/107201523-ffd2ba80-69f0-11eb-93b1-578f04194d11.png)
![image](https://user-images.githubusercontent.com/1944639/107201548-08c38c00-69f1-11eb-87e8-eb450f38151a.png)
![image](https://user-images.githubusercontent.com/1944639/107201567-10833080-69f1-11eb-826c-a04dd63b172a.png)

**Comment by Arthmoor** [comment]
Unfortunately nobody knows what specifically sets it off because even in mods that aren't adding more cells to a worldspace it can happen, like it did with my Storefront mod.
