### ISSUE TITLE
Circlet USSEP Fixes

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1323]
### [Circlet USSEP Fixes](https://www.nexusmods.com/skyrimspecialedition/mods/35576)

> This mod is to fix the problem of mods that overhaul circlet meshes not working well along with [Unofficial Skyrim Special Edition Patch](https://www.nexusmods.com/skyrimspecialedition/mods/266).
> 
> Currently, fixes are provided for the following mods.
> 
> [Gemling Queen Jewelry SE](https://www.nexusmods.com/skyrimspecialedition/mods/4294)
> [JS Circlet Replacer](https://www.nexusmods.com/skyrimspecialedition/mods/8686)
> 
> USSEP added new armor addon records to use its own circlet meshes for female elves. Thus, the mesh improvements done by circlet mods do not work at all on female elves. As you are most likely using USSEP already, I created this fix to help Skyrim modding community.
> 
> The meshes in this mod are from the original mods and I only changed the file paths of the circlet meshes to properly overwrite the meshes from USSEP. Since the fixes only contain mesh files, it is safe to install or uninstall anytime.

- [x] Add patch messages.

**Comment by sibir-ine** [comment]
None of the mods involved have plugins, only Gemling Queen Jewelry SE which has an optional plugin that has been deprecated as you mentioned in #1324. I don't think LOOT covers metadata for mods without plugins, right?

**Comment by MacSplody** [comment]
> I don't think LOOT covers metadata for mods without plugins, right?

Yeah that's right, but it could be added to USSEP's metadata.

**Comment by sibir-ine** [comment]
Ah, my bad! Should've thought of that.
