### ISSUE TITLE
Not detecting a present esp/mod

### ISSUE THREAD

**Issue by xazcxu** [loot/skyrimse#1335]
![Loot bug](https://user-images.githubusercontent.com/72061497/94513906-78ab5400-0252-11eb-865a-a15f955655ef.PNG)

**Comment by xazcxu** [comment]
these are not the only ones that were unable to find their masters despite them being presented in loot and enabled in mod organiser...

**Comment by MacSplody** [comment]
@xazcxu A green tick beside the plugin name means the plugin is active. Ordinator and the Apocalypse compatibility patch are not active in that picture.

> 
> 
> ![Loot bug](https://user-images.githubusercontent.com/72061497/94513906-78ab5400-0252-11eb-865a-a15f955655ef.PNG)

**Comment by xazcxu** [comment]
I guess I'm just an idiot... The mod itself is enabled on my mod organiser including the plugins, but loot doesn't seem to recognise it. It was okay at the one point, but suddenly I've been hit by the errors. Honestly not sure if it's due to another mod, mod organiser or loot itself. I've redownloaded them but to no avail... @MacSplody

**Comment by MacSplody** [comment]
> The mod itself is enabled on my mod organiser including the plugins, but loot doesn't seem to recognise it. It was okay at the one point, but suddenly I've been hit by the errors. Honestly not sure if it's due to another mod, mod organiser or loot itself.

If it's ticked in MO2's right panel then it should be enabled for all programs run through MO2, including LOOT.
LOOT can't enable or disable plugins, only your mod manager can change that.
![image](https://user-images.githubusercontent.com/1944639/94557189-24a26e80-0256-11eb-9da2-233f3d6055f7.png)

If you're still having issues then ask for help on the [MO2 Discord server](https://discord.com/invite/6GKR9jZ).

**Comment by xazcxu** [comment]
Thank you for the answer! I'll check further with the MO side @MacSplody

**Comment by MacSplody** [comment]
@xazcxu You're welcome.
