### ISSUE TITLE
Testing masterlist files with Invent tags

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1357]
[Interesting NPCs SE (3DNPC)](https://www.nexusmods.com/skyrimspecialedition/mods/29194/)
- [x] `3DNPC.esp`

[Bibliophile's Arcanaeum](https://www.nexusmods.com/skyrimspecialedition/mods/26772/)
- [x] `BA_(LegacyoftheDragonborn|LostLibrary)\.esp`

[Beasts of Tamriel](https://www.nexusmods.com/skyrimspecialedition/mods/5404/)
- [x] `Beasts of Tamriel.esp`

[Cloaks of Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/6369/)
- [x] `Cloaks.esp`

[Immersive College of Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/17004/)
- [x] `CollegeOfWinterholdImmersive.esp`, `ICOW_MOW_Patch.esp`.

[Crafting Supplies - All In One](https://www.nexusmods.com/skyrimspecialedition/mods/2359/)
- [x] `CraftingSupplies_AIO_ALL.esp`

[Cutting Room Floor](https://www.nexusmods.com/skyrimspecialedition/mods/276/')
- [x] `Cutting Room Floor.esp`

[Dawnguard Arsenal SSE](https://www.nexusmods.com/skyrimspecialedition/mods/25094/)
- [x] `DawnguardArsenal.esp`

[DLC Integration](https://www.nexusmods.com/skyrimspecialedition/mods/8032/)
- [x] `DLCIntegration.esp`

[Guards Armor Replacer](https://www.nexusmods.com/skyrimspecialedition/mods/22671/)
- [x] `Guards_Armor_Replacer.esp`

[Harvest Overhaul Redone](https://www.nexusmods.com/skyrimspecialedition/mods/2398/)
- [x] `HarvestOverhaul_Redone.esp`, `HarvestOverhaul_Redone_Creatures.esp`.

[The Definitive Hearthfire Supplies Mod](https://www.nexusmods.com/skyrimspecialedition/mods/5993/)
- [x] `Hearthfire Materials.esp`

[Immersive Horses](https://www.nexusmods.com/skyrimspecialedition/mods/13402/)
- [x] `Immersive Horses.esp`

[Immersive Jewelry](https://www.nexusmods.com/skyrimspecialedition/mods/5336/)
- [x] `Immersive Jewelry.esp`

[Legendary Armors - DeserterX Collection SSE](https://www.nexusmods.com/skyrimspecialedition/mods/2314/)
- [x] `LADX_SSE.esp`

[Lanterns Of Skyrim II](https://www.nexusmods.com/skyrimspecialedition/mods/30817)
- [x] `LoS II - Tamriel Master Lights.esp`

~[MorrowLoot Ultimate](https://www.nexusmods.com/skyrimspecialedition/mods/3058/)~
~- [ ] `MLU.esp`, `MLU - AAE Ultimate Edition.esp`, `MLU - Immersive Armors.esp`.~

[Poverty - You Hunger Reborn](https://www.nexusmods.com/skyrimspecialedition/mods/24712/)
- [x] `Poverty.esp`

[Heavy Armory - New Weapons](https://www.nexusmods.com/skyrimspecialedition/mods/6308/)
- [x] `PrvtI_HeavyArmory.esp`

[Rebalanced Leveled Lists](https://www.nexusmods.com/skyrimspecialedition/mods/26/)
- [x] `Rebalanced Leveled Lists( - Lite)?\.esp`

[Realistic Lighting Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/844/)
- [x] `RLO - Major City Exteriors - No Guard Torches.esp`

 [Skyrim Alchemy and Food Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/12343/')
- [x] `SAFO.esp`

[Scoped Bows](https://www.nexusmods.com/skyrimspecialedition/mods/912/)
- [x] `ScopedBows.esp`

[Skyrim Immersive Creatures](https://www.nexusmods.com/skyrimspecialedition/mods/12680/)
[Skyrim Immersive Creatures - Unofficial Patch](https://www.nexusmods.com/skyrimspecialedition/mods/18639/)
- [x] `Skyrim Immersive Creatures Special Edition.esp`

[Skyrim Revamped](https://www.nexusmods.com/skyrimspecialedition/mods/14338/)
- [x] `Skyrim Revamped.esp`, `Skyrim Revamped - Unique Loot Patch.esp`.

[Skyrim Revamped - Complete Enemy Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/14598/)
- [x] `Skyrim Revamped - Complete Enemy Overhaul.esp`

[Spell Research](https://www.nexusmods.com/skyrimspecialedition/mods/20983/)
- [x] `SpellResearch.esp`

[Whiterun Valley - Hold Expansion](https://www.nexusmods.com/skyrimspecialedition/mods/11917/)
- [x] `WhiterunValley2.esp`

**Comment by sibir-ine** [comment]
Had a look at Cutting Room Floor, and there are a lot of tags in the masterlist that are in the description, including Invent. I'll clean it up in a bit, but, regarding Invent, it only needs Invent.Add and Invent.Remove. Should I add them anyway such as in #1356?

**Comment by MacSplody** [comment]
> Had a look at Cutting Room Floor, and there are a lot of tags in the masterlist that are in the description, including Invent.

If it's in the plugin header, then you can remove it from the masterlist.

> but, regarding Invent, it only needs Invent.Add and Invent.Remove. Should I add them anyway?

You can add `Invent.Add` & `Invent.Remove` where `Invent` is listed in the header, and both tags are correct.

I did that for `MysticismMagic.esp`, mainly so everyone will know it has been checked.
![image](https://user-images.githubusercontent.com/1944639/95154259-5604c800-0789-11eb-917f-a70a2c7fca94.png)

**Comment by sibir-ine** [comment]
I'll also take a look at Scoped Bows (including the 3 replacers from [SBCK](https://www.nexusmods.com/skyrimspecialedition/mods/19495/)).

**Comment by sibir-ine** [comment]
I'm working on Skyrim Revamped at the moment.

**Comment by MacSplody** [comment]
> I'm working on Skyrim Revamped at the moment.

There may be some cross over with MLU due to [(SJG) OMEGA - The Modular Gameplay Overhaul for SSE](https://www.nexusmods.com/skyrimspecialedition/mods/17653) and [OMEGA Updated](https://www.nexusmods.com/skyrimspecialedition/mods/33718).

That includes a version of `Skyrim Revamped.esp`.
Hopefully they're not too different.

Tags I have for regular Morrowloot.

```yaml
  - name: 'MLU.esp'
    tag:
      - Actors.ACBS
      - Actors.AIData
      - Actors.CombatStyle
      - Actors.Spells
      - Actors.Stats
      - EnchantmentStats
      - -Invent
      - Invent.Add
      - Invent.Change
      - Invent.Remove
      - Keywords
      - Outfits.Add
      - Outfits.Remove
```

**Comment by sibir-ine** [comment]
Thanks for the heads up! I'll look into those versions too. I can take a look at Morrowloot as well.

**Comment by MacSplody** [comment]
> Thanks for the heads up! I'll look into those versions too. I can take a look at Morrowloot as well.

Well don't feel obligated to do both, there's a lot of work in those two mods.
I'd focus on `Skyrim Revamped.esp` first.
