### ISSUE TITLE
Incorrect Metadata Error on Thieves Guild Requirements.esp  4383E5A0

### ISSUE THREAD

**Issue by Avilyn238** [loot/skyrimse#1400]
I have Thieves Guild Requirements.esp  4383E5A0 installed; LOOT is telling me "This plugin requires "FileAccess Interface for Skyrim SE Scripts - FISSES" to be installed, but it is missing."  However, the version of Thieves Guild Requirements that I have is the one that does not require FISSES - there are 2 versions of the mod:  https://www.nexusmods.com/skyrimspecialedition/mods/33256?tab=files  and I verified that I am using the non-FISS version.

**Comment by sibir-ine** [comment]
Do you have a file named `TGRSettingsPreset.xml` at `data/SKSE/Plugins/FISS/`? That's what the entry actually looks for to determine whether to throw that error. You may have it left over from a previous installation.

**Comment by Avilyn238** [comment]
Ah, I did!  Apparently when I previously uninstalled FISS it didn't remove everything.  Thanks!

**Comment by sibir-ine** [comment]
No problem! The entry checks for that file as that's the only difference between the two versions; the ESPs are actually identical, so using checksums wouldn't work. Also, uninstalling FISS wouldn't remove the file as it's bundled with the FISS version of Thieves Guild Requirements.

**Comment by Avilyn238** [comment]
Ah, didn't realize the versions were identical otherwise; good to know.
