### ISSUE TITLE
Yet Another Cyclic Problem

### ISSUE THREAD

**Issue by gabe50200** [loot/skyrimse#141]
Seems to be same problem, but different .esp's:
Cyclic interaction detected between "JKs Skyrim_RWT_Patch.esp" and "ELE_SSE.esp". Back cycle: ELE_SSE.esp, Immersive Citizens - ELE patch.esp, RealisticWaterTwo.esp, JKs Skyrim_RWT_Patch.esp
[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/2074433/LOOTDebugLog.txt)
Apparently the Immersive Citizens fix didn't work for me, although it still seems to be involved.

**Comment by MacSplody** [comment]
Hi @gabe50200 can you change `Immersive Citizens - ELE patch.esp` and `JKs Skyrim_RWT_Patch.esp` group to to Alternate Start?

![image](https://user-images.githubusercontent.com/1944639/41010466-8ff5f3a4-692f-11e8-8cd1-79c44a90b01b.png)

**Comment by MacSplody** [comment]
@gabe50200 Is this issue still occurring?

**Comment by gabe50200** [comment]
Bingo, that did it. Thanks much.

**Comment by Ortham** [comment]
Closing this then.
