### ISSUE TITLE
DLC tags

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1422]
Dragonborn DLC change reverted by Improved Daedric Artifacts.

![image](https://user-images.githubusercontent.com/1944639/96823084-8bfda980-1423-11eb-9b0b-727db177a661.png)

- [x] Add Text tag to `Dragonborn.esm`

**Comment by sibir-ine** [comment]
I've also seen Survival Mode related keywords added by Update.esm get overwritten by older mods, so maybe adding `Keywords` would be wise? I don't actually have it, but I notice it's tagged with 'Keywords`. Does it already forward all the same keyword changes as Update.esm?

**Comment by MacSplody** [comment]
> Does it already forward all the same keyword changes as Update.esm?

It has been a while since I've looked at it, but it should, though it might have some differences.
Other mods can potentially use them, so maybe it should be added to `Update.esm` as well.

**Comment by sibir-ine** [comment]
I have a couple of tags I want to add to the masterlist, so I'll include these in a PR shortly.
