### ISSUE TITLE
Add version checks for SkyrimSE.exe & skse64_loader

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#146]
As suggested in issue #48  by @Arthmoor 

> This probably needs to be looked at again to provide for exe versions and SKSE64 loader versions in the same way the Fallout 4 list currently is since both are likely to change again in the future.

> @Arthmoor  Unable to get the true version of the SKyrimSE.exe at the moment. Quoting @WrinklyNinja 
> > Given that the executable version doesn't reflect the game version, I think it's pointless checking it. You could check the CRC instead, but I don't know if different regions get different executables (which would all have different CRCs)...

**Comment by MacSplody** [comment]
Going to try and get some CRC data on the SkyrimSE.exe

`1.5.39.0 CRC = CBD3BD78 `  Update: Same for EU & RU regions.

**Comment by MacSplody** [comment]
Reminder to check if version number is added to exe in next update.

**Comment by Freso** [comment]
Related: https://github.com/loot/loot-api/issues/36

**Comment by Arthmoor** [comment]
It was. "Product Version" in the Windows details tab shows 1.5.50 for SkyrimSE.exe. Is that setting enough?

**Comment by Freso** [comment]
@Arthmoor See https://github.com/loot/loot-api/issues/36

**Comment by MacSplody** [comment]
No change in version display with latest update
![image](https://user-images.githubusercontent.com/1944639/46422392-2f3fd100-c72c-11e8-8620-cd1c4e41ebd3.png)

**Comment by Arthmoor** [comment]
The product version. You're looking right at it. Although the one you're using has the wrong version number unless 1.5.53 is out.

**Comment by MacSplody** [comment]
@Arthmoor Can't use `product version` currently

**Comment by MacSplody** [comment]
Latest Update
`File Version: 1.0.0.0`
`Product Version: 1.5.62.0`
![image](https://user-images.githubusercontent.com/1944639/49623966-a5301500-f9c7-11e8-8e86-6ec931862ce3.png)

**Comment by MacSplody** [comment]
🎆
