### ISSUE TITLE
AllinoneFPSFix Load Order

### ISSUE THREAD

**Issue by KhrysINXS** [loot/skyrimse#1523]
AllinoneFPSFix
https://www.nexusmods.com/skyrimspecialedition/mods/21073

I don't think many folk use or know of this. It does work but on a very crucial note. This think technically needs to be the very highest mod in a load order when combined in a mod stack using Dyndolod. It even needs to be higher in priority then the Occlusion.esp from xLODGen

But I do gotta say, it works
I've used it forever but in my entire modding career, I didn't know that I wasn't Getting the FULL benefits it is intended to provide because I DIDNT know how important it is in the load order(edited)
Thought you may want to know about it. I have my LOOT ruled for a group that is higher in Priority then Occlusion.esp called "Very Last Misc"

**Comment by MacSplody** [comment]
The one issue with it is that it doesn't carry forward some changes from `Hearthfires.esm`

![image](https://user-images.githubusercontent.com/1944639/107001741-13c4b500-6782-11eb-8be3-d10bc3572fa6.png)

It changes are carried forward in both the `Bashed patch, 0.esp` and `DynDOLOD.esp`.
![image](https://user-images.githubusercontent.com/1944639/107007071-ef6cd680-6789-11eb-9a73-c5135b523e2f.png)

Also seems fine with `Occlusion.esp`.
![image](https://user-images.githubusercontent.com/1944639/107009859-7d968c00-678d-11eb-82f4-16aecf0792ee.png)

The mods I think it would conflict with are Paper maps, Map Markers or the [No Grass in Cities](https://www.nexusmods.com/skyrimspecialedition/mods/18768). Load order won't fix those though.
