### ISSUE TITLE
Loot cycling problem between two mods. From the nexus

### ISSUE THREAD

**Issue by HaloHazmat** [loot/skyrimse#1530]
My first post from nexus for background: "Hello, I've ran into an cyclic issue between immersive weapons and Ai overhaul that I can't seem to resolve. Ai overhaul says they are require to be loaded after immersive weapons by default yet immersive weapons has no option(besides AFT which I don't have) there by default. Loot still tries to put them behind each other resulting in the cyclic issue. Could this be from other mods I have or Loot itself? Because I don't remember having this issue before I updated and neither of the two mods require anything else in the load order that I have when looking in the metadata."

It still wasn't working after making sure the user data was cleared between them. Here is the debug log you asked for:
[LOOTDebugLog.txt](https://github.com/loot/loot/files/5668974/LOOTDebugLog.txt)

**Comment by MacSplody** [comment]
[AI Overhaul SSE](https://www.nexusmods.com/skyrimspecialedition/mods/21654)
[Immersive Weapons](https://www.nexusmods.com/skyrimspecialedition/mods/16788)

> Error: Failed to sort plugins. Details: <p>Cyclic interaction detected between &quot;Immersive Weapons.esp&quot; and &quot;AI Overhaul.esp&quot;: </p>
> <p>Immersive Weapons.esp<br>&emsp;[Masterlist Load After]<br>AI Overhaul.esp<br>&emsp;[Master]<br>Immersive Weapons.esp</p>

So the masterlist has `AI Overhaul.esp` set to load after `Immersive Weapons.esp`.
But your copy of `Immersive Weapons.esp` has `AI Overhaul.esp` as a master file.
Master Files always load before any files that require them.
I'm assuming you modified the file as I can't find a version of `Immersive Weapons.esp` that requires `AI Overhaul.esp`.
If that's the case, then you can fix the sorting issue by reinstalling Immersive Weapons to revert changes to its plugin.
If you need to patch the two mod, you'll have to put those changes in a new module.

**Comment by HaloHazmat** [comment]
huh, I must have done something in SSEdit a year ago that I forgot. Sorry for the misunderstanding and thank you for the help

**Comment by pStyl3** [comment]
This issue seems to be resolved, as such, I'm closing it.
