### ISSUE TITLE
Adding a warning to Immersive Jewelry?

### ISSUE THREAD

**Issue by Infernio** [loot/skyrimse#1536]
Right now it breaks the BP, because it wasn't converted properly to SSE and so its WEAP\CRDT subrecords have a really weird size (20 bytes, whereas 16 is the LE version and 24 is the SE version).
Resaving it in the CK seems to fix this, since it doesn't actually use any critical effects that resaving can break (they're all NULL).

**Comment by pStyl3** [comment]
It's [this modpage](https://www.nexusmods.com/skyrimspecialedition/mods/5336), right?

Does the problem only occur with v1.05 or with v1.06a aswell?

**Comment by Infernio** [comment]
Ah right, forgot to link the modpage. It is that one, and yeah it seems to be fixed in 1.06a. So probably a warning to upgrade to 1.06a if the 1.05 version is detected?

**Comment by Infernio** [comment]
The mod has version numbers in its description that LOOT recognizes, so `version()` should work (rather than messing around with CRCs).
