### ISSUE TITLE
Guard Dialog Overhaul has a new version (2.15) invaliding checksum on load after rules for WAACF Fixes

### ISSUE THREAD

**Issue by ghost** [loot/skyrimse#1537]
New GDO: https://www.nexusmods.com/skyrimspecialedition/mods/22075?tab=files  V2.15

_Weapons Armor Clothing & Clutter Fixes.esp_
expects load after rule for _Guard Dialog Overhaul.esp_ checksum to be 0x6ABC1129

New GDO checksum appears to be 0x15C41030.  Not confident enough to implement this via a pull request.

This issue is caught and reported by **SSEEdit** as a misordering of the two mods.  Temporarily fixed by added a user rule to **LOOT** for _Weapons Armor and Clutter Fixes.esp_ without the checksum condition.

**Comment by sibir-ine** [comment]
Just submitted a pull request to address this. I'd recommend keeping the user rule unless you switch to a version of GDO that doesn't require WACCF to load after to avoid this in the future.
