### ISSUE TITLE
Immersive Fort Dawnguard has both .ESP and ESPFE patchs for PCE and LotD

### ISSUE THREAD

**Issue by ghost** [loot/skyrimse#1540]
The FDI mod has both .ESPFE and .ESP versions of the PCE and LOTD patches available:

> fortdawnguardimmersive.esp  
> Actors.ACBS, Actors.AIPackages, Actors.Stats, C.Climate, C.Light, C.Water, Factions, ObjectBounds
> You seem to be using Legacy of the Dragonborn, but you have not enabled a compatibility patch for this mod. A compatibility patch is included with this plugin's installer.
> 
> You seem to be using Palaces and Castles Enhanced, but you have not enabled a compatibility patch for this mod. A compatibility patch is included with this plugin's installer.

From explorer inside the FDI mod folder:
FDILOTDBPatch.esp
FDIPCEnhancedPatch.esp

These patches are both loaded into FE:xxx mod index space.

**Comment by MacSplody** [comment]
> Which game is this for, Skyrim LE or SE?

SSE, I'll transfer it over.

---

Looking at the archive from [Immersive Fort Dawnguard](https://www.nexusmods.com/skyrimspecialedition/mods/40436), the ESL flagged files have a different name.

![image](https://user-images.githubusercontent.com/1944639/104127559-a4160280-535a-11eb-9930-e8c51e83d76c.png)

Just need to update the message conditions to check for both patches.
