### ISSUE TITLE
LOOT.exe launched from MO2, LOOT failed to sort. Error: canonical: The system cannot find the file specified.

### ISSUE THREAD

**Issue by sholt0r** [loot/skyrimse#1541]
I have been unable to find any information on a similar issue. My plugins are displaying in LOOT correctly, however they will not sort. I have uploaded my debug log, let me know if you need anything further.
[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/5801913/LOOTDebugLog.txt)

**Comment by ddbb07** [comment]
Did you use the built in feature of mo2 to sort or did you start standalone loot, and does the error specify a file.

**Comment by Ortham** [comment]
The error message is

```
[22:57:57.157005] [error]: Failed to sort plugins. Details: canonical: The system cannot find the file specified.: "G:\Steam\steamapps\common\Skyrim Special Edition\Data\3BBB.esp"
```

This looks like another case of trouble with MO2's virtual filesystem, there's not really anything that can reasonably be done about it on LOOT's end, as it's just using the standard filesystem APIs as provided by Microsoft.

**Comment by sholt0r** [comment]
@ddbb07 I use the standalone LOOT launched through MO2. The error always specifies one of the ESP files. As @Ortham believes that this is most likely an issue with MO2's VFS, I will close this case and raise it with the MO2 team as from the past couple of days testing, this seems to be the most likely cause. Thank you for your assistance.
