### ISSUE TITLE
Evenstar - Minimalistic Standing Stones of Skyrim and Morningstar - Minimalistic Races of Skyrim bash tags

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#1549]
Mod link: [Evenstar - Minimalistic Standing Stones of Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/41256)

Maybe it could benefit from having some bash tags, as users reported in the posts that the text descriptions from this mod do not carry over into the game at times. USSEP seems to be overriding it since that mod has the Text tag.

Some of the tags that I suggest and might be helpful are these, there could be tags more or less warranted though:

```
- EffectStats
- Graphics
- Keywords
- Names
- Sound
- SpellStats
- Text
```

A very similar mod by the same mod author, [Morningstar - Minimalistic Races of Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/22298), might also benefit from some bash tags for the changes to vanilla racial abilities.

Edit: If one wanted to go further, EnaiSiaion's latest mod [Sacrilege - Minimalistic Vampires of Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/42408) probably could benefit from Text and maybe other tags as well.

**Comment by Infernio** [comment]
Started tackling this at https://github.com/Infernio/skyrimse/tree/inf-enai
