### ISSUE TITLE
Change in .git return format confounds LOOT

### ISSUE THREAD

**Issue by me-dog** [loot/skyrimse#1550]
LOOT is unable to update the masterlist.yaml file. Error message:

[20:57:27.977894] [error]: Exception while executing query: Git operation failed. Details: -1; failed to send request: An invalid argument was supplied.
: libgit2 error
[20:57:27.978874] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5723: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5723:9239)

Could it be due to GitHub returning an HTML-file instead of raw data since this is what is currently received with wget? Manually accessing the page and copying the raw data to masterlist.yaml works as a workaround.

**Comment by Ortham** [comment]
What game's masterlist are you getting the error with?

**Comment by me-dog** [comment]
Oops, sorry, editing out irrelevant debug info also removed some relevant bits. It's Skyrim SE, https://github.com/loot/skyrimse.git, fresh install of LOOT on Windows 10,

**Comment by Ortham** [comment]
Try replacing your `loot.dll` with this one: https://dl.bintray.com/loot/snapshots/libloot-0.16.1-5-g35e81c1_master-win32.7z

**Comment by me-dog** [comment]
I begin to suspect PEBKAC. Sorry for the inconvenience. I've been fiddling around with MO2 lately and quite probably fiddled more than my skills supported. After removing and reinstalling MO2 the issue went away. Don't know exactly what I did but probably something involving paths. D'oh is all I can add.

**Comment by MacSplody** [comment]
> 
> 
> I begin to suspect PEBKAC. Sorry for the inconvenience. I've been fiddling around with MO2 lately and quite probably fiddled more than my skills supported. After removing and reinstalling MO2 the issue went away. Don't know exactly what I did but probably something involving paths. D'oh is all I can add.

It usually happens if you run LOOT for the first time inside MO2 and download the masterlist.
First run and sort should be performed outside MO2.
