### ISSUE TITLE
Unnessecary compatibility patch notification (True Storms, Wet & Cold, Catherdarl Weathers Diverse Seasons)

### ISSUE THREAD

**Issue by Giltintur** [loot/skyrimse#1563]
I have the Cathedral Weathers - Diverse Seasons full patch for True Storms, Wet and Cold, and Improved Rain and Fog for Cathedral Weathers, but loot suggests that I download the wet and colt and true storms patch.

This seems to be incorrect, as the patching is done by the diverse seasons patch. 
The patch is here: https://www.nexusmods.com/skyrimspecialedition/mods/28612

**Comment by MacSplody** [comment]
@Giltintur Done, the message will be hidden if `CathedralWeathersSeasons.esp` is active.
