### ISSUE TITLE
Inigo Cleaning Message

### ISSUE THREAD

**Issue by avigorus** [loot/skyrimse#1567]
Inigo is not supposed to be cleaned, yet LOOT is telling me to clean it.

**Comment by MacSplody** [comment]
> Inigo is not supposed to be cleaned, yet LOOT is telling me to clean it.

LOOT doesn't ever actually tell anyone to clean plugins in those messages.
It only provides the cleaning information to inform each user of files that are dirty.
It's up to each user whether or not they want to clean the files.

From the description page of [Inigo](https://www.nexusmods.com/skyrimspecialedition/mods/1461?tab=description).

> -------------------------------------------------------------------Cleaning-------------------------------------------------------------------
> Inigo has been cleaned with SSEEdit. Landscape edits are intentional. Later versions of TES5Edit uncover a small number of Nav related ITMs. These are simply verts linked to edited verts. You can clean them if you wish, but there is no need to do so.
> 

The Navmesh ITMs themselves may not cause any issues in most load orders.
You could potentially have issues if you have another mod that also makes changes to those records.
The only mod I can recall editing some of the same cells is [Caranthir Tower Reborn](https://www.nexusmods.com/skyrimspecialedition/mods/4269), but there could be more.
Again it's something each user will have to check for in their load order.
