### ISSUE TITLE
Load Follower Commentary Overhaul Between ICAIO and RDO?

### ISSUE THREAD

**Issue by Graybark** [loot/skyrimse#159]
The author suggests
ICAIO
FCO
RDO
https://www.nexusmods.com/skyrimspecialedition/mods/16865?tab=posts

**Comment by MacSplody** [comment]
@ArtaiosGreybark I added a rule to load RDO after FCO yesterday in #158 , there are no conflicts between Immersive citizens & Follower Commentary Overhaul so they can be loaded either way.
