### ISSUE TITLE
Synthesis

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1658]
https://github.com/Mutagen-Modding/Synthesis

> A framework and GUI to construct a single Bethesda game patch from many patcher sources.

Dynamically creates a single plugin `Synthesis.esp`.
Placement should probably be right before `DynDOLOD.esp` and `Occlusion.esp'` in the Late Fixes & Changes group.

**Comment by sibir-ine** [comment]
This was [discussed](https://discord.com/channels/537706885965676554/537710082755133460/815169410548891648) in the Wrye Bash Discord, but Synthesis can create massive plugins that cause Bashed Patch building to hang, so Synthesis should probably be run & loaded after it. A custom message could even be added to reflect this, like the message for `Occlusion.esp`.

From @Infernio:
> That seems sensible. Usually you want the BP to take everything it can into account, but if Synthesis really creates these stupidly huge plugins, you kind of need to run it after the BP.

The discussion on Discord:

<img width="855" height="957" alt="Image" src="https://github.com/user-attachments/assets/780c188e-9ed2-4e76-96b5-be7e89987a9e" />

<img width="855" height="957" alt="Image" src="https://github.com/user-attachments/assets/b398de4e-c30a-47cc-967a-ce9c1ca986be" />

<img width="876" height="173" alt="Image" src="https://github.com/user-attachments/assets/b5d5eca1-c324-479a-b544-fa1cc058dd7b" />

**Comment by MacSplody** [comment]
Okay, I've added it to the appropriate group, so it will be after the Bashed Patch.
I'll leave this open for now as I didn't add any message for it.
