### ISSUE TITLE
"ELFX - Weather" "True Storms Special Edition" "Obsidian Weathers" compatibility patches

### ISSUE THREAD

**Issue by Zipfer** [loot/skyrimse#1700]
Here are two compatibility patches that are not described in the compatibility list:
https://www.nexusmods.com/skyrimspecialedition/mods/19837
https://www.nexusmods.com/skyrimspecialedition/mods/17198

Not sure if there is the ability to use all of them at the same time. I'm testing it right now

**Comment by sibir-ine** [comment]
@Zipfer Both patches are mentioned in the entries for [True Storms](https://github.com/loot/skyrimse/blob/03792ebd2153552824600007cb100c17d7468485/masterlist.yaml#L4007-L4049) & [Obsidian Weathers](https://github.com/loot/skyrimse/blob/03792ebd2153552824600007cb100c17d7468485/masterlist.yaml#L3902-L3956), respectively. They both have entries of their own [here](https://github.com/loot/skyrimse/blob/03792ebd2153552824600007cb100c17d7468485/masterlist.yaml#L4078-L4096) & [here](https://github.com/loot/skyrimse/blob/03792ebd2153552824600007cb100c17d7468485/masterlist.yaml#L4133-L4152) as well. Is there anything else you'd like to report regarding the two?

**Comment by sibir-ine** [comment]
> Not sure if there is the ability to use all of them at the same time. I'm testing it right now

Also, they likely won't all work together. I don't personally know with 100% certainty, but weather overhauls like ELFX Weathers & Obsidian tend not to be compatible with each other. We even have them explicitly [labeled](https://github.com/loot/skyrimse/blob/03792ebd2153552824600007cb100c17d7468485/masterlist.yaml#L3914) as incompatible with each other. True Storms is more focused on one aspect of weather in SSE, so it's more easily woven into other broader weather mods.

**Comment by Zipfer** [comment]
@sibir-ine Thank you for your quick response. I thought that ELEX is about lightning not about the weather.
https://www.nexusmods.com/skyrimspecialedition/mods/2424

**Comment by sibir-ine** [comment]
> I thought that ELEX is about lightning not about the weather.

@Zipfer Yes, it's mostly a lighting mod, but it also has an add-on in the installer named **ELFX - Weathers.esp**. The [first patch](https://www.nexusmods.com/skyrimspecialedition/mods/19837/) you linked is for it & True Storms.

**Comment by Zipfer** [comment]
I see. I actually also found it. And I also realized that some patches allow enabling conflicting options. 
So, I disabled the weather option from ELEX and now it seems to be working fine.
That's why I've got this mess with required patches. I can't remember right now what was the initial setup. So, it fixed for me.
Thank you!
And thank you for your great app!
