### ISSUE TITLE
"3D Trees Patches + Better Dynamic Snow V3.0" FLAG if Both Esp's Present

### ISSUE THREAD

**Issue by easelgames** [loot/skyrimse#1726]
Just bringing this up as I stumbled upon it. Skyrim Mod "Skyrim 3D Trees Patches" No longer needs the BDS "Better Dynamic Snow" patch if using BDS version 3.0.

3D Trees Patches Page + [Post](https://forums.nexusmods.com/index.php?/topic/8761528-skyrim-3d-trees-patches/page-6#entry89188868) stating this.

Simply bringing it to your attention to flag "No longer needed" under "S3DTrees Better Dynamic Snow Patch.esp" if it detects v3.0 of Better Dynamic Snow. I'm not sure redundant plugins really matter in this case, but I've seen this kinda stuff in Loot messages before so I figured I'd mention it here.

**Comment by sibir-ine** [comment]
@easelgames From the looks of it, BDS 3.0+ renamed the plugin from `Better Dynamic Snow.esp` to `Better Dynamic Snow SE.esp`. `S3DTrees Better Dynamic Snow Patch.esp` has `Better Dynamic Snow.esp` as a master, so, if you're using BDS 3.0+, you'll get a missing masters error anyway. We could also add a message to indicate that the patch has been included in or otherwise fixed by BDS 3.0+ (if that's the case) to be a little more descriptive.

**Comment by easelgames** [comment]
> @easelgames From the looks of it, BDS 3.0+ renamed the plugin from `Better Dynamic Snow.esp` to `Better Dynamic Snow SE.esp`. `S3DTrees Better Dynamic Snow Patch.esp` has `Better Dynamic Snow.esp` as a master, so, if you're using BDS 3.0+, you'll get a missing masters error anyway. We could also add a message to indicate that the patch has been included in or otherwise fixed by BDS 3.0+ (if that's the case) to be a little more descriptive.

You know I actually played with this mod + patch + 3.0 installed and never saw any errors now that I think on it.. (tons of hours) This may need more investigating.

**Comment by sibir-ine** [comment]
> You know I actually played with this mod + patch + 3.0 installed and never saw any errors now that I think on it.. (tons of hours) This may need more investigating.

@easelgames Do you still have `Better Dynamic Snow.esp` installed & active?

**Comment by easelgames** [comment]
> > You know I actually played with this mod + patch + 3.0 installed and never saw any errors now that I think on it.. (tons of hours) This may need more investigating.
> 
> @easelgames Do you still have `Better Dynamic Snow.esp` installed & active?

... OK yes. I have it listed as Better Dynamic Snow.esp on MO2. Which is really strange considering I'm running 3.3 and it even shows as 3.3 in MO2. This must be an oddity response to having had 2.0 and using the "merge" when updating command. I can't think of what else it would be. That is weird

EDIT: OK it kept the old one too in MO2. So because I merged and didn't know he changed plugin names, I have BOTH listed ESPs... what

**Comment by sibir-ine** [comment]
> This must be an oddity response to having had 2.0 and using the "merge" when updating command. I can't think of what else it would be.

@easelgames Yeah, it's because you merged instead of replacing when you installed. It's not odd behavior, it's what you'd expect (& frankly hope for) from merging since the plugin got renamed to `Better Dynamic Snow SE.esp` in 3.0. When updating, you're better off replacing so that not only do updated files overwrite outdated ones, deprecated & unused files are removed as well. MO2 also gives you the option to keep a backup during the mod overwrite popup, so you can make use of that in case something goes wrong in the process of replacing (like settings getting reverted). I'll add a message to use only one of the ESPs to address this.

Anyway, BDS's entry in LOOT hasn't been updated since 2.11.0, so this is a good opportunity to update it. Thanks for the report!

**Comment by easelgames** [comment]
Thanks again. I'm not sure how this effected my in-game as I honestly never noticed but maybe this was because I had been using the patch. Does the SE  named plugin just get ignored then if both are in with the other version higher? I would assume so based on priority...

**Comment by sibir-ine** [comment]
> Does the SE named plugin just get ignored then if both are in with the other version higher? I would assume so based on priority...

@easelgames Neither would get ignored unless you deactivated one of them; they would just be treated like they're separate mods. If the old version loaded after, it would revert some changes made in 3.0+, but it doesn't look like there are any catastrophic conflicts.

**Comment by easelgames** [comment]
> > Does the SE named plugin just get ignored then if both are in with the other version higher? I would assume so based on priority...
> 
> @easelgames Neither would get ignored unless you deactivated one of them; they would just be treated like they're separate mods. If the old version loaded after, it would revert some changes made in 3.0+, but it doesn't look like there are any catastrophic conflicts.

OK looking into this further. It may be worth mentioning that these mods: https://www.nexusmods.com/skyrimspecialedition/mods/20102?tab=posts
https://www.nexusmods.com/skyrimspecialedition/mods/22741?tab=posts

Plugins no longer work with BDS v3.0 or higher. (redundant) Thanks!

**Comment by sibir-ine** [comment]
@easelgames Thanks for the additional reports!

**Comment by easelgames** [comment]
> @easelgames Thanks for the additional reports!

One more thing that will need testing that I'm NOT sure on.. IF mods like Obscures College Of Winterhold, or WiZkiD-Compendium-Patches for BDS, are looking for the old BetterDynamicsnow.esp name. Loot correctly flags this so it's not really a loot issue, but worth mentioning as I'm not sure how 3.0 works currently if you take those patches out with said mods in question.

**Comment by sibir-ine** [comment]
@easelgames I updated the entry for BDS & added messages for the patches you mentioned. Most seem to require the old BDS as a master, so the warning message to only use one version of BDS combined with the missing masters message should hopefully be enough for any others. However, feel free to report any more you find so we can provide the supplemental message. Thanks for reporting these to us!
