### ISSUE TITLE
JK's The Winking Skeever + Alternate Start LAL

### ISSUE THREAD

**Issue by easelgames** [loot/skyrimse#1764]
JKs_The_Winking_Skeever_AlternateStartMods.esp 
https://www.nexusmods.com/skyrimspecialedition/mods/43991?tab=files
Needs to load AFTER "alternate start - live another life" and other alternate start mods. According to mod author of JK. Not sure on validity of this in practice if it makes a difference. The current loot list as of writing this placed this ESP before LAL for me. 

![delete me 1](https://user-images.githubusercontent.com/46850157/114280668-63d12980-9a08-11eb-97a6-bbf7520d201e.png)

Thanks!

PS: NOT RELATED: Unsure if I should make a new issue for this or not.. but using "Useless Patch Collection" Their is a mod plugin that needs to be flagged as "DO NOT USE" based on mod authors post. (last mod update dated now, likely wont be updated) 
https://www.nexusmods.com/skyrimspecialedition/mods/27667?tab=files

![delete me 2](https://user-images.githubusercontent.com/46850157/114280755-c3c7d000-9a08-11eb-8ee1-5820aa1d3237.png)

NOTE: UPC uses a FOMOD but it is one that does NOT auto detect/lock plugins so user must manually check these. Makes not using easier for specific plugins...

**Comment by MacSplody** [comment]
> JKs_The_Winking_Skeever_AlternateStartMods.esp
> https://www.nexusmods.com/skyrimspecialedition/mods/43991?tab=files
> Needs to load AFTER "alternate start - live another life" and other alternate start mods. According to mod author of JK. Not sure on validity of this in practice if it makes a difference. The current loot list as of writing this placed this ESP before LAL for me.

That looks correct, at least for ASLAL.

![image](https://user-images.githubusercontent.com/1944639/114287074-ff3fba00-9a5b-11eb-813a-91bbc076d280.png)

---

> PS: NOT RELATED: Unsure if I should make a new issue for this or not.. but using "Useless Patch Collection" Their is a mod plugin that needs to be flagged as "DO NOT USE" based on mod authors post. (last mod update dated now, likely wont be updated)
> https://www.nexusmods.com/skyrimspecialedition/mods/27667?tab=files
> 
> NOTE: UPC uses a FOMOD but it is one that does NOT auto detect/lock plugins so user must manually check these. Makes not using easier for specific plugins...

If the author wasn't active it might make sense, but they are and it's something they can easily fix by themselves.

**Comment by MacSplody** [comment]
Also needs a `C.Water` tag.

![image](https://user-images.githubusercontent.com/1944639/114287232-44182080-9a5d-11eb-804a-59ef24b2e370.png)

---

Load after ICAIO
One navmesh conflict, JK's makes a larger number of changes and adds some new doors.

![image](https://user-images.githubusercontent.com/1944639/114287238-5abe7780-9a5d-11eb-80b0-03c02d104118.png)

**Comment by MacSplody** [comment]
One ITM that may block a change from Open Cities.

Test file containing the ITM.

![image](https://user-images.githubusercontent.com/1944639/114287526-6a3ec000-9a5f-11eb-9b3d-b7f8fef45c78.png)

```yaml
  - name: 'JK's The Winking Skeever.esp'
    dirty:
      - <<: *quickClean
        crc: 0x41D5106D
        util: '[SSEEdit v4.0.3f](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 1
```
