### ISSUE TITLE
Reliquary of Myth - ISC.esp + MLU.esp Sorting Backwards

### ISSUE THREAD

**Issue by easelgames** [loot/skyrimse#1765]
In: Reliquary of Myth - Artifact Overhaul
https://www.nexusmods.com/skyrimspecialedition/mods/31612

The **RoM - ISC + MLU Patch.esp** Needs to load AFTER MLU.esp
Currently based on xedit.
![loot error 01](https://user-images.githubusercontent.com/46850157/114304854-6f256300-9aa3-11eb-8ae4-e06d5ec6b747.png)
_affects all red listed armor/weapons on left_

**Comment by sibir-ine** [comment]
@easelgames Yeah, it doesn't have MLU as a master, & MLU is in a later group than it. We can add a requirement to sort it correctly. Thanks for the report!

**Comment by easelgames** [comment]
> @easelgames Yeah, it doesn't have MLU as a master, & MLU is in a later group than it. We can add a requirement to sort it correctly. Thanks for the report!

Should I mention this master suggestion on the RoM page?

**EDIT: Already pointed out on the RoM posts page. Not addressed yet so glad I brought it up here I suppose lol**

**Comment by sibir-ine** [comment]
> Should I mention this master suggestion on the RoM page?

@easelgames Yeah, I don't see why the mod shouldn't have MLU as a master even if it technically doesn't need it.
