### ISSUE TITLE
Celtic Music In Skyrim - Minor Plugin Order Suggestion

### ISSUE THREAD

**Issue by easelgames** [loot/skyrimse#1770]
Just a VERY simple ask. When using Celtic Music in Skyrim found here:
https://www.nexusmods.com/skyrimspecialedition/mods/2980?tab=files

I noticed that the music wasn't working and I believe I fixed it by adding custom loot rules for the optional installs to load AFTER the main .esp. It's probably a niche` mod that not to many use or have issues with but it's probably worth me submitting anyway. Not even entirely sure if necessary.

- Celtic_Music_In_Skyrim_SE.esp
- Celtic Music in Skyrim - Combat.esp
- Celtic_Music_In_Skyrim_SE_Dungeon.esp

I believe since loot doesn't currently have orders set for these that it means that the whatever order you installed them they get placed.. Don't know how Combat/Dungeon ended up above in the load order in my LO but they did. Thanks again, I'm always happy to submit stuff. Though I do feel like it may be nitpicky sometimes.

**Comment by sibir-ine** [comment]
> It's probably a niche` mod that not to many use or have issues with but it's probably worth me submitting anyway.

> Though I do feel like it may be nitpicky sometimes.

@easelgames We always appreciate reports; there's only so much we can find out in our own time, so we depend on reports from users, especially for niche mods that we probably haven't heard of.

In this case, load order doesn't matter as the plugins don't conflict (verified in xEdit), & there are no BSA conflicts. However, what may be causing you issues is the fact that the combat add-on's BSA has a different name to its plugin. This would prevent the songs it adds from being loaded into the game, so we can add a message to tell users to rename the BSA.

- [x] Add `*renameXtoY` message to `Celtic Music in Skyrim - Combat.esp` for BSA (`Celtic_Music_In_Skyrim_SE_Combat.bsa` to `Celtic Music in Skyrim - Combat.bsa`)

**Comment by easelgames** [comment]
Hmm well it did get it fixed for me. But I also use Immersive Sound Compendium + Audio Overhaul Skyrim . When I added AOS prior to rearranging the celtic I heard the original music. Though this could just be random luck as the mod does keep the vanilla music in-game it just lowers the chances. I still figured it a safe bet based on most cases to have the main mods plugin loading first, rather then last compared to its add-ons.

**Comment by sibir-ine** [comment]
> Though this could just be random luck

@easelgames Unless there's some subtle mechanic going on that I'm not aware of, it's most likely that. 

> I still figured it a safe bet based on most cases to have the main mods plugin loading first

Since I think it's for the best not to add unnecessary load rules for maximum compatibility across everyone's different mod lists, we should just let LOOT's algorithm handle it. Since the mods don't conflict & LOOT minimizes unnecessary changes (like changing the order of mods that don't conflict), it'll just leave these in whatever order they were in relation to one another.
