### ISSUE TITLE
Cyclic interaction detected between "Unofficial Skyrim Special Edition Patch.esp" and "BS_DLC_patch.esp". Back cycle: BS_DLC_patch.esp, Lanterns Of Skyrim - All In One - Main.esm, Unofficial Skyrim Special Edition Patch.esp

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#178]
[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/2109232/LOOTDebugLog.txt)

Reported on nexus

**Comment by Ortham** [comment]
The relationships are:

```
Unofficial Skyrim Special Edition Patch.esp
    -> BS_DLC_patch.esp (group)

BS_DLC_patch.esp
    -> Lanterns Of Skyrim - All In One - Main.esm (group)

Lanterns Of Skyrim - All In One - Main.esm
    -> Unofficial Skyrim Special Edition Patch.esp (load after)
```

The Lanterns of Skyrim / USSEP load after metadata is correct according to the LoS Nexus page, so I think LoS should go in the `earlyLoadersGroup` to resolve this cycle.

**Comment by MacSplody** [comment]
Okay thanks, I'll make an update to move it there.

I couldn't spot anything in the log. I have those plug-ins as well and couldn't duplicate it.

**Comment by MacSplody** [comment]
#179 Should be resolved now, I'll wait to close this until I receive confirmation on nexus.

**Comment by MacSplody** [comment]
Confirmed as fixed.
