### ISSUE TITLE
Skyrim Special Edition: Convenient Horses Patches

### ISSUE THREAD

**Issue by Ensrick** [loot/skyrimse#1819]
The mod recommended for creating patches that encompass the new lands now is merged into a single plugin by the author of the patches. The installation process takes the user through a variety of options and then selects one of many possible merged patch plugins. LooT doesn't recognize the merged patch I'm using for Convenient Horses that covers Wyrmstooth, Bruma, Northpoint, Midvale Isle, and Beyond Reach. The new optional and miscellaneous that patch other mods were added in April this year. Given that LooT doesn't have the metadata to recognize these patches, I think it's safe to assume that it wouldn't recognize the other patches or the need for compatibility patches in load orders that are missing them.

**Comment by MacSplody** [comment]
For [Bruma and Other Patches for Convenient Horses](https://www.nexusmods.com/skyrimspecialedition/mods/13812/), they've changed some of the patch names, so those will need to be updated.

**Comment by MacSplody** [comment]
I think we should just remove the messages for these patches, it has some patches under misc files that we can't account for.
