### ISSUE TITLE
Arena - An Encounter Zone Overhaul should sort after Morrowloot Ultimate

### ISSUE THREAD

**Issue by ketsuban** [loot/skyrimse#1836]
LOOT already includes rules for sorting `MLU - Vanilla Encounter Zones.esp` after `MLU.esp`, as well as [Rebalanced Encounter Zones](https://www.nexusmods.com/skyrimspecialedition/mods/25); [Arena - An Encounter Zone Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/33487) (`Arena.esp`) is the same, in that the main reason to install both is to override Morrowloot Ultimate's static encounter zones with Arena's.

**Comment by sibir-ine** [comment]
@ketsuban Added, thanks for the report!
