### ISSUE TITLE
Arena Encounter Zone Overhaul - Cleaning & Load Order

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1839]
[Arena - An Encounter Zone Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/33487/)
Version 1.1.0

Requested change on [Discord](https://discord.com/channels/473542112974077963/496196499890241546/849008892637216778)

![image](https://user-images.githubusercontent.com/1944639/120239109-7e2fc280-c255-11eb-80da-d832907387aa.png)

> The mod in question is Arena - An Encounter Zone Overhaul.
> The ITMs in question basically serve as a patchless compatibility tool that allow the mod to be combined with popular mods like Morrowloot, Skyrim Revamped, Inez, and that new Open World Loot mod. Without the ITMs I'd need patches for every possible combination, so this is a pretty clear use-case for intentional ITMs.
> (And yeah, people combine it with all of those mods and more, I don't understand users :laughing: )
> I've seen a fair number of automatic patchers for this record type, thus my concern about breaking them by changing the EditorIDs. I don't know for sure that it would do it, since I hardly know how each automated patcher works, but like I said it's happened before in other contexts.

- [x] Remove cleaning info.
~~- [ ] Add afters for conflicting mods.~~

**Comment by sibir-ine** [comment]
I already added an after for Morrowloot, it doesn't conflict with Skyrim Revamped, & LOOT automatically sorts it after Inez & Open World Loot.

**Comment by MacSplody** [comment]
> I already added an after for Morrowloot, it doesn't conflict with Skyrim Revamped, & LOOT automatically sorts it after Inez & Open World Loot.

There's the two encounter zone patches for MLU, did you check those?

**Comment by sibir-ine** [comment]
> There's the two encounter zone patches for MLU, did you check those?

Yes, it loads after them automatically with the after for MLU.
