### ISSUE TITLE
Immersive Weapons / WACCF incorrect/incomplete patch suggestion

### ISSUE THREAD

**Issue by fwdekker** [loot/skyrimse#1957]
I have `Immersive Weapons` and `Weapons Armor Clothing and Clutter Fixes` installed as mods. LOOT then correctly states that I should download a patch from `kryptopyr's Patch Hub`. However, after installing the appropriate patch, the suggestion to install that patch remains. Based on the current master list, I think this is because the condition reads
```
condition: 'active("Weapons Armor Clothing & Clutter Fixes.esp") and not active("Complete Crafting Overhaul_Remastered.esp") and not active("Immersive Weapons_WACCF_Patch.esp")'
```

I do not have `Complete Crafting Overhaul Remastered` (CCOR) installed. Installing this mod removes the suggestion from LOOT. However, LOOT never told me about CCOR. I'm also not sure why CCOR is required. Does it patch the behaviour between the two mods? If not, it should be removed. If it is helpful, then the message should be updated to also link to CCOR.

**Comment by MacSplody** [comment]
> However, after installing the appropriate patch, the suggestion to install that patch remains.

The patch needs to be enabled as well.
![image](https://user-images.githubusercontent.com/1944639/127058371-9ded9764-8128-4f00-8a91-45fdce5c68b9.png)

You'll know LOOT sees it as enabled when there's a green tick beside the plugin name.
![image](https://user-images.githubusercontent.com/1944639/127058278-bfd712e3-6221-4517-948a-8dd3b7cf76f5.png)

**Comment by fwdekker** [comment]
I can confirm that `Immersive Weapons_WACCF_Patch.esp` is enabled (not just listed, it's enabled with priority 157) in my plugins, and I still get the suggestion. It has a green tick in LOOT. Only when I also install CORR does the suggestion disappear.

**Comment by MacSplody** [comment]
> I can confirm that `Immersive Weapons_WACCF_Patch.esp` is enabled (not just listed, it's enabled with priority 157) in my plugins, and I still get the suggestion. It has a green tick in LOOT. Only when I also install CORR does the suggestion disappear.

I can't troubleshoot it without more information.
Can you supply a full debug log for when the issue is happening?
[How To Report Issues Helpfully](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html)
Make sure to turn on debug logging in settings.
![image](https://user-images.githubusercontent.com/1944639/127061796-99c1ba4c-e887-4ed6-9aef-03dc13400e1a.png)

**Comment by fwdekker** [comment]
## Steps to reproduce
1. Create a clean Skyrim SE install.
2. Install [Unofficial Skyrim Special Edition Patch](https://www.nexusmods.com/skyrimspecialedition/mods/266) v4.2.5b.
3. Install [Immersive Weapons](https://www.nexusmods.com/skyrimspecialedition/mods/16788) v2.
4. Install [Weapons Armor Clothing and Clutter Fixes](https://www.nexusmods.com/skyrimspecialedition/mods/18994) v2.5.
5. Install _Immersive Weapons \_\_ WACCF_ v2.0 from [kryptopyr's Patch Hub](https://www.nexusmods.com/skyrimspecialedition/mods/19518).
6. Enable the following plugins:
    ```
    Skyrim.esm
    Update.esm
    Dawnguard.esm
    HearthFires.esm
    Dragonborn.esm
    Unofficial Skyrim Special Edition Patch.esp
    Weapons Armor Clothing & Clutter Fixes.esp
    Immersive Weapons.esm
    WACCF_ImmersiveWeapons_Patch.esp
    ```
7. Run LOOT. Update the master list and sort the entries.

LOOT now displays the following message with the `Immersive Weapons.esp` mod:
> You seem to be using Weapons Armor Clothing and Clutter Fixes, but you have not enabled a compatibility patch for this mod. A third party patch is available here: kryptopyr's Patch Hub

![LOOT's message for Immersive Weapons](https://user-images.githubusercontent.com/13442533/127064422-a3eed08f-ee11-498f-8ef7-fb5301c5ba51.PNG)

To remove the message, run the following steps.

8. Install [Complete Crafting Overhaul Remastered](https://www.nexusmods.com/skyrimspecialedition/mods/28608) v2.2.
9. Enable `Complete Crafting Overhaul_Remastered.esp` in the load order.
10. Remove _Immersive Weapons \_\_ WACCF_ v2.0 from [kryptopyr's Patch Hub](https://www.nexusmods.com/skyrimspecialedition/mods/19518).
11. Install _Immersive Weapons \_\_ WACCF_CCOR_ v2.0 from [kryptopyr's Patch Hub](https://www.nexusmods.com/skyrimspecialedition/mods/19518).
12. Enable `Immersive Weapons_CCOR_Patch.esp` in the load order.
13. Run LOOT. Update the master list and sort the entries.

Observe that a message is no longer displayed for the _Immersive Weapons_ mod.
![LOOT displays no message for Immersive Weapons after the above steps](https://user-images.githubusercontent.com/13442533/127064936-d2c5d28c-dc4e-43d3-a726-1f90d40c4e1f.PNG)

## Actual behaviour
LOOT informs the user that a patch from _kryptopyr's Patch Hub_ resolves a certain incompatibility, but after installing that patch the message is still displayed. The message is only fixed by installing the mod _Complete Crafting Overhaul Remastered_, but this is not explained by LOOT.

## Desired behaviour
I see two ways in which this issue can be resolved:
1. If _Complete Crafting Overhaul Remastered_ is not actually necessary to fix the incompatibility, this requirement should be removed from the message's condition.
2. If _Complete Crafting Overhaul Remastered_ is indeed required, then the message should be adjusted so that it informs the user of this requirement.

## Version information
| Tool | Version |
| --- | --- |
| Skyrim SE | v1.5.97.0 |
| ModOrganizer 2 | v2.4.2 |
| LOOT | v0.16.1 |
| Masterlist | `ea14cc8` |

**Comment by MacSplody** [comment]
Right I see where the problem is.
LOOT is checking for `Immersive Weapons_WACCF_Patch.esp`
And you have `WACCF_ImmersiveWeapons_Patch.esp`, which is the old version of the patch for WACCF v1.

**Comment by fwdekker** [comment]
Oh I see, that solved it. I thought I had checked that, but somehow I still ended up using an old version. Thank you!
