### ISSUE TITLE
The currently recommended AI Overhaul / Open Cities patch is not recognized by LOOT.

### ISSUE THREAD

**Issue by Earnest-Williams** [loot/skyrimse#1977]
The recommended patch can be found here: https://www.nexusmods.com/skyrimspecialedition/mods/4635?tab=files

**Comment by MacSplody** [comment]
> The recommended patch can be found here: https://www.nexusmods.com/skyrimspecialedition/mods/4635?tab=files

Right, I'll have a look at those now and compare the patches.

**Comment by MacSplody** [comment]
There are some problems with that patch.

It's based on the order:
Open Cities Skyrim.esp
AI Overhaul.esp
AIOHisyOCS.esp

Which isn't a problem if it's patched correctly, but it's not.
It's reverting changes to the cells that objects are being placed into.

![image](https://user-images.githubusercontent.com/1944639/130712080-62b20835-18d9-4b05-80f6-ab72346750a7.png)

![image](https://user-images.githubusercontent.com/1944639/130712866-da13a810-f1a0-4c8e-98ec-c1848ae328f9.png)


Neither patch covers this conflict
![image](https://user-images.githubusercontent.com/1944639/130712833-cde6e6ca-6a88-4eef-be0c-3896977d347a.png)

It also needs some cleaning.
![image](https://user-images.githubusercontent.com/1944639/130712275-e30e5c66-0c30-4ba1-a6e0-4394c601dfbe.png)

**Comment by MacSplody** [comment]
@Earnest-Williams I've posted an updated patch on [Random Open Cities Patches](https://www.nexusmods.com/skyrimspecialedition/mods/4635), hopefully they use the updated file.
I don't think either patch is useful alone at the moment, as they both have issues, so I'll disable the message for now.

**Comment by MacSplody** [comment]
I'll close this for now, if either page ever updates the patch we can add the message again.
