### ISSUE TITLE
Unable to update masterlist: there is an issue

### ISSUE THREAD

**Issue by Mishchap** [loot/skyrimse#2]
So I used this masterlist for skyrim special edition and this happened. Thought I'd let you guys know.
"Masterlist revision 2406b3b: yaml-cpp: error at line 15, column 5: bad conversion. The latest masterlist revision contains a syntax error, LOOT is using the most recent valid revision instead. Syntax errors are usually minor and fixed within hours."

**Comment by Ortham** [comment]
You're probably using an outdated snapshot build.

**Comment by doxxx** [comment]
I got a similar error using Loot 0.9.2.

> Error code: 0; Failed to update the masterlist. Details: Masterlist revision 8c511a1: yaml-cpp: error at line 27, column 9: bad conversion: 'str' key missing from 'message content' object.

**Comment by Ortham** [comment]
0.9.2 doesn't support the v0.10 syntax.

**Comment by doxxx** [comment]
Ah, that would explain it. I'll wait for a new release. Thanks!
