### ISSUE TITLE
Cyclic Interaction - Andromeda & FloraRespawnFix

### ISSUE THREAD

**Issue by SierraKomodo** [loot/skyrimse#2001]
LOOT Version: 0.16.1
Masterlist Revision :fa92c7a
Masterlist Date: 2021-08-28

```
Cyclic interaction detected between "Andromeda - Unique Standing Stones of Skyrim.esp" and "FloraRespawnFix.esp":

Andromeda - Unique Standing Stones of Skyrim.esp
 [Group]
Complete Alchemy & Cooking Overhaul.esp
 [Master]
CACO_Beyond Skyrim Bruma_Patch.esp
 [Master]
FloraRespawnFix.esp
 [Group]
Andromeda - Unique Standing Stones of Skyrim.esp
```

As a note, this is the `FloraRespawnFix.esp` file generated using the xedit script, not the esp file from nexus mods.

**Comment by sibir-ine** [comment]
@SierraKomodo Moving **FloraRespawnFix.esp** to the **default** group should fix it. That group assignment should probably be removed in the masterlist too on account of the xEdit script.

**Comment by MacSplody** [comment]
Are those two not incompatible `Complete Alchemy & Cooking Overhaul.esp` and `FloraRespawnFix.esp`?
Since `Complete Alchemy & Cooking Overhaul.esp` includes [Wiseman303's Flora Fixes](https://www.nexusmods.com/skyrim/mods/70656/).
Or am I missing something?

![image](https://user-images.githubusercontent.com/1944639/131556873-083fbcce-a220-4619-82e0-5079b1009f8c.png)

> 
> 
> @SierraKomodo Moving **FloraRespawnFix.esp** to the **default** group should fix it. That group assignment should probably be removed in the masterlist too on account of the xEdit script.

Yeah, that sounds fine.

**Comment by SierraKomodo** [comment]
> 
> 
> Are those two not incompatible `Complete Alchemy & Cooking Overhaul.esp` and `FloraRespawnFix.esp`?
> Since `Complete Alchemy & Cooking Overhaul.esp` includes [Wiseman303's Flora Fixes](https://www.nexusmods.com/skyrim/mods/70656/).
> Or am I missing something?

My understanding is the xedit generated version is compatible, since it incorporates all loaded plugins, and it has better inclusion/compatibility with any other mod loaded that flora fixes for the same reasons. There was a discussion on reddit somewhere about all this that I'd found while putting together my current mod list a few days ago, but I can't find it now. To be honest that information could entirely be wrong.


> 
> 
> @SierraKomodo Moving **FloraRespawnFix.esp** to the **default** group should fix it. That group assignment should probably be removed in the masterlist too on account of the xEdit script.

I'll give that a try. My current workaround has been temporarily disabling the SSEEdit mod group in mod organizer whenever I run loot - The generated .esp file is meant to be at the bottom of the load order anyway.

**Comment by MacSplody** [comment]
> 
> 
> > Are those two not incompatible `Complete Alchemy & Cooking Overhaul.esp` and `FloraRespawnFix.esp`?
> > Since `Complete Alchemy & Cooking Overhaul.esp` includes [Wiseman303's Flora Fixes](https://www.nexusmods.com/skyrim/mods/70656/).
> > Or am I missing something?
> 
> My understanding is the xedit generated version is compatible, since it incorporates all loaded plugins, and it has better inclusion/compatibility with any other mod loaded that flora fixes for the same reasons. There was a discussion on reddit somewhere about all this that I'd found while putting together my current mod list a few days ago, but I can't find it now. To be honest that information could entirely be wrong.

Maybe there something to it, we could only disable the incompatibility if they're not using the normal version of `FloraRespawnFix.esp`.

Edit: I moved that to a separate issue.

**Comment by MacSplody** [comment]
I've tried it and you end up with this in the generated `FloraRespawnFix.esp`.

Both scripts applied to some records.
![image](https://user-images.githubusercontent.com/1944639/131559258-aacca080-6068-4872-a605-779d9bb41046.png)

The Flora Respawn Fix alone applied to other records.
![image](https://user-images.githubusercontent.com/1944639/131559929-58f0a4a9-3943-4b59-8838-1f0bbfba123b.png)

Now the question is, is there any negative effect from having both scripts applied to the same records?
