### ISSUE TITLE
Wrong metadata from Immersive Creatures and SkyTEST

### ISSUE THREAD

**Issue by AndreTheHunter** [loot/skyrimse#2056]
LOOT is telling me:
> You seem to be using [SkyTEST - Realistic Animals and Predators](https://www.nexusmods.com/skyrimspecialedition/mods/1104/), but you have not enabled a compatibility patch for this mod. A third party patch is available here: [SkyTEST Integration Project](https://www.nexusmods.com/skyrimspecialedition/mods/13428/)

However, going to SkyTEST Integration Project SE
 https://www.nexusmods.com/skyrimspecialedition/mods/13428/?tab=description, shows that the patch is now being maintained by https://www.nexusmods.com/skyrimspecialedition/mods/54930?tab=description

**Comment by MacSplody** [comment]
> 
> 
> LOOT is telling me:
> 
> > You seem to be using [SkyTEST - Realistic Animals and Predators](https://www.nexusmods.com/skyrimspecialedition/mods/1104/), but you have not enabled a compatibility patch for this mod. A third party patch is available here: [SkyTEST Integration Project](https://www.nexusmods.com/skyrimspecialedition/mods/13428/)
> 
> However, going to SkyTEST Integration Project SE
> https://www.nexusmods.com/skyrimspecialedition/mods/13428/?tab=description, shows that the patch is now being maintained by https://www.nexusmods.com/skyrimspecialedition/mods/54930?tab=description

The patch hasn't been released yet, it can be updated when lifestorock releases the patch, should be soon going by the comments.

![image](https://user-images.githubusercontent.com/1944639/132511559-40d584d2-cc26-4562-bf9b-5eadd4ab928c.png)

**Comment by MacSplody** [comment]
@AndreTheHunter Done, thanks for reporting it.
