### ISSUE TITLE
LOOT 

### ISSUE THREAD

**Issue by Ray5868** [loot/skyrimse#2082]
LOOT will not work with Skyrim SE or Fallout 4. I have uninstalled and reinstalled LOOT with no change. Getting error msg saying no game installed

**Comment by sibir-ine** [comment]
Read this [section of the FAQ](https://loot.github.io/docs/help/LOOT-FAQs.html#game-not-detected). If they don't apply, manually enter the install path in each game's entry in LOOT's settings.

![image](https://user-images.githubusercontent.com/69141501/134099493-5adf8384-262f-4257-80cf-b33bc9bbaaea.png)

**Comment by Ray5868** [comment]
All info matches the sample with the exception of the file path, which on
my system is F:

**Comment by sibir-ine** [comment]
You've entered the file paths that contain **SkyrimSE.exe**/**Fallout4.exe** & LOOT still gives you the error after exiting & restarting it? Then please enable debug logging in the settings menu & [supply a debug log](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by sibir-ine** [comment]
Since you filed a new issue, I'll close this one.
