### ISSUE TITLE
Relighting Skyrim SSE Updates

### ISSUE THREAD

**Issue by TechAngel85** [loot/skyrimse#2093]
**Relighting Skyrim SSE** should be loaded before _Luminosity Lighting Overhaul_ (both versions) and _Enhanced Lighting for ENB_...probably most of the mods in that group. RS only edits object reference placements and those mods edit Cell records containing those objects, thus, they should be loaded _**after**_ Relighting Skyrim or their changes are nullified by the RS plugin. Loading them after RS will merge the changes of both mods. Win-win.

It should also no longer be dirty (main file v1.2.1).

**Comment by MacSplody** [comment]
> **Relighting Skyrim SSE** should be loaded before _Luminosity Lighting Overhaul_ (both versions) and _Enhanced Lighting for ENB_...probably most of the mods in that group. RS only edits object reference placements and those mods edit Cell records containing those objects, thus, they should be loaded _**after**_ Relighting Skyrim or their changes are nullified by the RS plugin. Loading them after RS will merge the changes of both mods. Win-win.
> 
> It should also no longer be dirty (main file v1.2.1).

It already does that with default sorting by using groups.

![image](https://user-images.githubusercontent.com/1944639/135667902-f6bd6450-2f19-4c77-b7fd-33f65fa2e14f.png)

![image](https://user-images.githubusercontent.com/1944639/135668427-6ed873dc-455c-4d21-8daf-5efb05958457.png)

![image](https://user-images.githubusercontent.com/1944639/135668166-b49fb9e0-4f93-4e2d-85db-ab8aac9ba0c5.png)

![image](https://user-images.githubusercontent.com/1944639/135668217-2209b9ee-7950-4c07-a832-7aadb7b0989d.png)


Of course there's nothing preventing users from overriding that by changing groups or using load after rules.
They'd also get different sorting results if they don't have the masterlist downloaded.

**Comment by TechAngel85** [comment]
I noticed I got a list update and it changed. Thanks. I'll close this.

**Comment by MacSplody** [comment]
> 
> 
> I noticed I got a list update and it changed. Thanks. I'll close this.

We can update the cleaning data, so I'll leave it open until then.
