### ISSUE TITLE
Unique Region Names shouldn't require Regional Save Names

### ISSUE THREAD

**Issue by pragasette** [loot/skyrimse#2102]
I expanded on the topic here: https://github.com/loot/skyrimse/commit/22680817e05365e7aa0e6ba1644e023938b542fd#r57571726, the bottom line being URN could be installed on its own without warning, and rather a message should be displayed (if possible) when using RSN without [its requirements](https://www.nexusmods.com/skyrimspecialedition/mods/49698).

**Comment by sibir-ine** [comment]
We don't display metadata for individual SKSE plugins, so the message can just be removed.

**Comment by pragasette** [comment]
Thanks, closing after f628367.
