### ISSUE TITLE
Opulent Thieves Guild

### ISSUE THREAD

**Issue by sibir-ine** [loot/skyrimse#2134]
[Opulent Thieves Guild](https://www.nexusmods.com/skyrimspecialedition/mods/931)

> The file actually has a wild edit in **00016BCF** since it adds back the encounter zone value removed by **Update.esm** (the same wild edit that's recommended to be cleaned from Dawnguard)... note that the **OpulentThievesGuildPatch.esp** plugin on the mod's page reverts the wild edit, so the message wouldn't need to be displayed if it's active.

- [x] Sort entry alphabetically in section
- [x] Add wild edits message
- Investigate various patches & fixes
  - [x] [Enhanced Lights and FX Patch](https://www.nexusmods.com/skyrimspecialedition/mods/18299) (more up-to-date patch with same name in Opulent Thieves Guild Patch Collection)
  - [x] [Ethereal Elven Overhaul patch](https://www.nexusmods.com/skyrimspecialedition/mods/7351) (hidden)
  - [x] [Opulent Thieves Guild - FPS Fix](https://www.nexusmods.com/skyrimspecialedition/mods/41309)
  - [x] [Opulent Thieves Guild Patch Collection](https://www.nexusmods.com/skyrimspecialedition/mods/35261)

_Originally posted by @sibir-ine in https://github.com/loot/skyrimse/pull/2132#discussion_r734909164_

**Comment by Sabre142** [comment]
[Ethereal Elven Overhaul patch](https://www.nexusmods.com/skyrimspecialedition/mods/7351/) has been set to hidden.

Hidden at 03 Mar 2022, 10:30PM by [AngelTrump](https://www.nexusmods.com/users/39775535).

**Comment by sibir-ine** [comment]
Closed by #2376.
