### ISSUE TITLE
Doesn't recognize Relationship Dialogue Overhaul - Immersive Horses Patch

### ISSUE THREAD

**Issue by Corderoa** [loot/skyrimse#216]
There is a [compatibility patch available for RDO and immersive horses](https://www.nexusmods.com/skyrimspecialedition/mods/17700), which is not recognized by LOOT; it still shows an error when using the two together with the patch.

**Comment by MacSplody** [comment]
@Corderoa It's not an error, it's a warning message. LOOT will still sort, an actual error will prevent sorting.

Works fine on my end.
Is the patch enabled or has it been merged into a bashed patch? 

![image](https://user-images.githubusercontent.com/1944639/42412940-fa236e9a-820d-11e8-8cce-466fb25478c3.png)
