### ISSUE TITLE
JK's The Bannered Mare - SPO compatibility patch message

### ISSUE THREAD

**Issue by Meryl** [loot/skyrimse#2168]
The following message shows for [JK's The Bannered Mare](https://www.nexusmods.com/skyrimspecialedition/mods/33845) even if you have the relevant patch (from [JK's Interior Patch Collection](https://www.nexusmods.com/skyrimspecialedition/mods/35910)) installed:

> You seem to be using **Skyrim Project Optimization**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page.

The rule for this message seems to be

`active("Skyrim Project Optimization - .*\.esm") and not active("JK's The Bannered Mare SPO Patch.esp")`

But the esp-file that's provided by the patch collection is actually called _JKs Bannered Mare - SPO Patch.esp_, so the correct rule would be:

`active("Skyrim Project Optimization - .*\.esm") and not active("JKs Bannered Mare - SPO Patch.esp)`

**Comment by MacSplody** [comment]
Yeah, it must have been renamed at some point.
And it used to be on the K's The Bannered Mare mod page.

![image](https://user-images.githubusercontent.com/1944639/141111281-66153ddf-da77-40c5-9c0f-912d0c5b880c.png)

Will have to change the message type and condition.

**Comment by MacSplody** [comment]
@Meryl Done, thanks for reporting it.
