### ISSUE TITLE
Legacy of the Dragonborn has an Open Cities Skyrim compatibility patch

### ISSUE THREAD

**Issue by ghost** [loot/skyrimse#217]
Legacy of the Dragonborn : https://www.nexusmods.com/skyrimspecialedition/mods/11802
It is under the optional Legacy of the Dragonborn Patches SE file.

Open Cities Skyrim : https://www.nexusmods.com/skyrimspecialedition/mods/281/

The patch ESP is : DBM_OpenCities_Patch.esp

**Comment by bpipher0225** [comment]
LOTD is probably worth a group on its own, let me know what info you might need and I could even write up something to handle most of the legwork.
