### ISSUE TITLE
why it reports USSEP 4.2.5b require skyrimse 1.6.318.0 or higher?

### ISSUE THREAD

**Issue by rainmanhhh** [loot/skyrimse#2187]
nexus says 4.2.5b is for 1.5.97

**Comment by sibir-ine** [comment]
What is the version number of USSEP detected by LOOT (the grey number next to the plugin name)?

![image](https://user-images.githubusercontent.com/69141501/141669533-3fb59838-dfc9-4c28-98e7-1a9d40116927.png)

**Comment by rainmanhhh** [comment]
4.2.5b

**Comment by sibir-ine** [comment]
Huh, I can't reproduce this, & I can't see anything wrong with the message's condition. Can you please restart LOOT, make sure your masterlist is up-to-date, & sort? You don't have to apply the sort.

**Comment by rainmanhhh** [comment]
fixed by upgrade to 0.16.1
