### ISSUE TITLE
Load Order Issue

### ISSUE THREAD

**Issue by insane46** [loot/skyrimse#22]
Immersive Sounds - Compendium.esp should be loaded after Reverb and Ambience Overhaul - Skyrim.esp, not before.

**Comment by Spu00Key** [comment]
> 99% Compatible with Immersive Sounds - just load that mod after this one to solve any issues.

What issues have you found loading it before?

Edit: Both Author's contacted.

**Comment by Spu00Key** [comment]
I've had these two files swapped for a long time now without experiencing an issue.

It has been a week with no reply from @insane46 or either author.
I am no longer following this issue.  That will change if I get something from an author.

**Comment by Spu00Key** [comment]
I have word back from an Author; will update in a few days.

**Comment by Spu00Key** [comment]
Closed with PR #35.
