### ISSUE TITLE
Group order - Changes may be required

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#2200]
Keeping notes for possible group changes.
WIP

---

At the moment the order works fine for most cases by default.
But it may be optimal to change the order slightly.

`Lux.esp` (Interior Lighting)
Can now be placed after PCE, Patch included.

`RLO - Interiors.esp` (Interior Lighting)
Should be before PCE, but may have to be placed after for group consistency.

Palaces Castles Enhanced.esp (High Priority Overrides Group)

`Open Cities Skyrim.esp` (High Priority Overrides Group)
Must load after PCE and ideally should be kept after Lux due to navmesh and doors.

`OCW_CellSettings.esp` (Cell Settings Group)
Needs to be after lighting and music mods, very few conflicts with other mods.
Could be moved to later group (Late Loaders?) and the cell settings group removed.

Water mods (Late Loaders Group)
May have to be moved to an earlier group.
Conflicts with some mods that Lux needs to be after like `fortdawnguardimmersive.esp`.

Map Marker mods
Could also be moved to an earlier group.
Conflicts with OCS, Lux and some mods that need to be before Lux.
Atlas map markers OCS version could be put into default group.

Possible new group order, not complete.
![image](https://user-images.githubusercontent.com/1944639/142952609-72788600-c08e-4c52-8899-553e762d13a6.png)

**Comment by sibir-ine** [comment]
IIRC, _Cutting Room Floor_ does get sorted after _Relationship Dialogue Overhaul_ by default unless you have _Immersive Citizens_ installed. _ICAIO_ is in the **Core Mods** group (which loads after the default group) & _RDO_ is set to load after it on the advice of both authors (_RDO_ incorporates _ICAIO_ changes in overlapping records), so _ICAIO_ will essentially hoist _RDO_ later in your load order & therefore later than _CRF_ (which is in the default group). I think this has come up several times &, IIRC, we haven't sorted everything out yet as it may require an overhaul to our groups for SSE.

_Originally posted by @sibir-ine in https://github.com/loot/skyrimse/issues/2365#issuecomment-1082640959_

**Comment by MacSplody** [comment]
Closing, as I'm happy enough with the order for later mods atm.
