### ISSUE TITLE
Holy Mountains Load Order

### ISSUE THREAD

**Issue by bartmoss** [loot/skyrimse#2276]
According to the mod page, Holy Mountains should be loaded after Majestic Mountains, even though it no longer depends on it.
I am not confident enough to submit an edit directly, and I don't want to break anything, hence I am opening this issue. Hope this is OK.

Explicit Loadorder statement by author: https://forums.nexusmods.com/index.php?/topic/10589728-holy-mountains-majestic-mountains-addon/page-7#entry103406333

Holy Mountain mod page: https://www.nexusmods.com/skyrimspecialedition/mods/56828
Majestic Mountains: https://www.nexusmods.com/skyrimspecialedition/mods/11052

Holy Mountains ESP filename:
Holy Mountains.esp
(contains a space)

Majestic Mountains ESP filenames:
MajesticMountains.esp
MajesticMountains_Landscape.esm
MajesticMountains_Moss.esp

(there may be others, that's my install)

**Comment by MacSplody** [comment]
@bartmoss Done, thanks for reporting it.
