### ISSUE TITLE
Realistic Water Two must load after Sounds of Skyrim Complete

### ISSUE THREAD

**Issue by lued123** [loot/skyrimse#23]
Exactly what it says on the tin. If Sounds of Skyrim Complete (haven't tested individual versions) is allowed to overwrite, water seems appear all over Skyrim.

**Comment by Spu00Key** [comment]
PR #24 submitted with the combination and 3 separate ESP versions included.

> **Realistic Water Two:** This mod must be placed after any mod that modifies a cell near a body of water. In order to avoid seeing "seams" in the water, I recommend placing this mod VERY low in your load order.

XEdit shows several water tag conflicts between the two mods.

No author contacted.

**Comment by Ortham** [comment]
Closed by #24.
