### ISSUE TITLE
patch3rdParty_SRPC & patch3rdParty_SRPC_Redux

### ISSUE THREAD

**Issue by cecell** [loot/skyrimse#2315]
@sibir-ine, you had helped setup the 'interfunctionality' between the patch3rdParty_SRPC & patch3rdParty_SRPC_Redux anchors.  For the items that still have patch3rdParty_SRPC message (and the redux anchor) I'm still getting that message even even though I have patch3rdParty_SRPC_Redux installed.  How can we fix this?

**Comment by cecell** [comment]
Correction, they don't have the Redux message but they are supported. Can we add an and not active condition for the patches added by Redux? EDIT: I'll add the condition but sibir had made a judgment call when the new anchor was added to only include the non _Redux version because of a comment somewhere that the older was preferred

**Comment by sibir-ine** [comment]
Both `patch3rdParty_SRPC` & `patch3rdParty_SRPC_Redux` recommend & are hidden by an active Redux patch, but `patch3rdParty_SRPC` is also hidden by an active original patch for users who prefer it for whatever reason. `patch3rdParty_SRPC` should only be applied to mods patched by both the original & Redux, &, `patch3rdParty_SRPC_Redux`, to mods only patched by Redux.

Which plugins do you feel have the wrong message or are missing either message? It's very possible that I missed some when I split them. I don't see anything wrong the conditions of the messages themselves, they operate as I laid out previously.

**Comment by cecell** [comment]
I have the Redux version active yet the following files are showing the message "You seem to be using Spell Research v2.2+, but you have not enabled a compatibility patch..."
iHarvest.esl
cutting room floor.esp
elemental destruction.esp
caranthirtowerreborn.esp
shadowspellpackage.esp
forgottenmagic_redone.esp
mining for mages redux.esp
complete alchemy & cooking overhaul.esp
apocalypse - magic of skyrim.esp
apocalypse - more apocalypse.esp

I agree, a user may prefer one over the other and thus I have no argument about them being presented with more than one option but if they have either installed they shouldn't be told "you have not enabled a compatibility patch for this mod." when in fact they have.

**Comment by sibir-ine** [comment]
I've tested each plugin, & I can't replicate this. For the Redux patch, the message condition looks for the name of the patch as downloaded from its page, i.e., `Spell Research - Even More Patches.esp`. It also checks to make sure it's active. Can you please double-check that you haven't changed the name of the patch or deactivated it? Can you please also press the Update Masterlist button to make sure your masterlist is up-to-date? You may then need to sort to make sure everything has been refreshed, but you don't have to apply the sorted order.

**Comment by cecell** [comment]
Neither can I.  I've apparently updated my master list now without realizing that I did because the problem isn't showing anymore.  (sigh) Thank you for your help and I apologize for wasting time

**Comment by sibir-ine** [comment]
No worries!
