### ISSUE TITLE
Thane of Whiterun and Thane of Riften mods by Endoroc

### ISSUE THREAD

**Issue by SkyLover264** [loot/skyrimse#2330]
LOOT appears to be placing Endoroc's Riften thane mod after his Whiterun thane mod in load order sorting, but Endoroc has stated that the Whiterun mod needs to be loaded last.

**Comment by sibir-ine** [comment]
Can you please provide links to all the mods involved?

**Comment by SkyLover264** [comment]
[Thane of Riften Requires Favors](https://www.nexusmods.com/skyrimspecialedition/mods/61205)
[Thane of Whiterun Requires Favors](https://www.nexusmods.com/skyrimspecialedition/mods/61206)

**Comment by sibir-ine** [comment]
@SkyLover264, thanks for the report, added.
