### ISSUE TITLE
Flat World Map Framework

### ISSUE THREAD

**Issue by GunthorNC** [loot/skyrimse#2335]
One bit of manual sorting I had to do was for 

[Flat World Map Framework](https://www.nexusmods.com/skyrimspecialedition/mods/29932)

It would not display at all unless I manually moved 
FWMF SE Marked Old Map 4k.esp
FWMF SE Marked Old Map 4k NAT fix.esp
FWMF SE Marked Old Map 4k Vivid Weathers Fix.esp

to the very bottom of my load order. I dunno what the proper placement of them is, but moving them down there allowed my world map to display

Thank you Ortham!

**Comment by MacSplody** [comment]
> One bit of manual sorting I had to do was for
> 
> https://www.nexusmods.com/skyrimspecialedition/mods/62705
> 
> It would not display at all unless I manually moved FWMF SE Marked Old Map 4k.esp FWMF SE Marked Old Map 4k NAT fix.esp FWMF SE Marked Old Map 4k Vivid Weathers Fix.esp
> 
> to the very bottom of my load order. I dunno what the proper placement of them is, but moving them down there allowed my world map to display
> 
> Thank you Ortham!

Other paper map mods are being placed in the Worldspace Settings group, so it should be fine there as well.
Even with that grouping or placing it last for that matter, it may still require patching with other mod changing the Worldspace records. Things like map markers, lighting overhauls, water mods, paper maps will modify Worldspace records.

I'm also reviewing the groups in #2200 
It might be best to split paper maps into their own group.
