### ISSUE TITLE
Dungeons Revisited - Conflicts with ELFX Enhancers

### ISSUE THREAD

**Issue by GunthorNC** [loot/skyrimse#2361]
https://www.nexusmods.com/skyrimspecialedition/mods/51798?tab=posts

Found this while browsing. 

"Be advised 

if you have huge holes that peaks into the void, make sure to load this mod after ELFX since LOOT wont sort it properly, and that mean you have to do it every time you run loot again."

4th stickied post down.

This also applies to

https://forums.nexusmods.com/index.php?showtopic=11124618/#entry106949293

Where the poster is told to load that mod after ELFX Shadows as well.

**Comment by MacSplody** [comment]
> https://www.nexusmods.com/skyrimspecialedition/mods/51798?tab=posts
> 
> Found this while browsing.
> 
> "Be advised
> 
> if you have huge holes that peaks into the void, make sure to load this mod after ELFX since LOOT wont sort it properly, and that mean you have to do it every time you run loot again."
> 
> 4th stickied post down.
> 
> This also applies to
> 
> https://forums.nexusmods.com/index.php?showtopic=11124618/#entry106949293
> 
> Where the poster is told to load that mod after ELFX Shadows as well.

I'm going to assume it's the lighting enhancers causing the problem, the main ELFX module should be sorting before most files.
It will need some testing and reviews in xEdit.

**Comment by MacSplody** [comment]
Seems to be sorting correctly, it might a case of a user grouping ELFX or adding a rule that's affecting it.

![image](https://user-images.githubusercontent.com/1944639/171777408-6bce32ae-7809-4492-9b71-8d562b6c79fc.png)

**Comment by MacSplody** [comment]
Okay so it's the enhancer plugins that are overwriting it.

![image](https://user-images.githubusercontent.com/1944639/171779261-adc7397c-d8ae-4c21-bf83-51c084197aab.png)

**Comment by sibir-ine** [comment]
There appears to be a patch for the hardcore enhancer [here](https://www.nexusmods.com/skyrimspecialedition/mods/59610), I'll take a look at it.

**Comment by sibir-ine** [comment]
Thanks for the report!
