### ISSUE TITLE
THE PEOPLE OF SKYRIM COMPLETE FALSKAAR PATCH

### ISSUE THREAD

**Issue by Nesbit098** [loot/skyrimse#2385]
Hi Loot Team,
an update for you re a three-way patch. As always appreciate your efforts and time.

https://www.nexusmods.com/skyrimspecialedition/mods/13906?tab=description

V10.7.2 for the combo patch for alt start TPOSC and Falskaar.

Please note if you use the integrated patch you will get this LOOT warning until they update their system as the Loot program only recognizes the individual patches to date.
https://i.postimg.cc/D0GPwBS4/LOOT-15-02-2022-17-04-09-2.png

**Comment by sibir-ine** [comment]
Done, thanks for the report!
