### ISSUE TITLE
Better Vampire NPC's and NPC Replacer mods are not sorted properly

### ISSUE THREAD

**Issue by bradcrabtree** [loot/skyrimse#2401]
I have a number of NPC Replacers like BBs Lasses of Skyrim Redux that I had loaded after the 2.0 version of Better Vampire NPC's.esp, the no appearance changes (NAC) version of the mod and after I ran LOOT, all the vampires are vanilla looking and they looked nice before LOOT. Loot incorrectly places the Better Vampires NAC 2.0 below that mod and for some reason, undoes the NPC changes despite me using the NAC version.

[Better Vampire NPCs 2.0 SE](https://www.nexusmods.com/skyrimspecialedition/mods/9510/)
[BB's Lasses of Skyrim Redux](https://www.nexusmods.com/skyrimspecialedition/mods/64872/)
[Modpocalypse NPCs - All Vanilla NPCs](https://www.nexusmods.com/skyrimspecialedition/mods/54422/)

**Comment by MacSplody** [comment]
> I have a number of NPC Replacers like BBs Lasses of Skyrim Redux that I had loaded after the 2.0 version of Better Vampire NPC's.esp, the no appearance changes (NAC) version of the mod and after I ran LOOT, all the vampires are vanilla looking and they looked nice before LOOT. Loot incorrectly places the Better Vampires NAC 2.0 below that mod and for some reason, undoes the NPC changes despite me using the NAC version.

@bradcrabtree Can you give provide links to the mods?
Also a list of expected plugin order verses how LOOT is sorting them would be useful.

**Comment by bradcrabtree** [comment]
Better Vampire NPC's NAC version. It's being placed after both ModApocalpyse NPCs and then after BB's Lasses of Skyrim. Rest of my cosmetic mods are sorted properly.

Mod links:
https://www.nexusmods.com/skyrimspecialedition/mods/9510
https://www.nexusmods.com/skyrimspecialedition/mods/64872

I like the logic of LOOT for individual ESL NPC Replacer mods... so far these individual NPC replacer plugins are all placed below the multiple NPC replacer plugins which I use in this order, which is the correct order because the logic should be an individual replacer is of more importance than a multiple pack replacer. These mods are installed in MO2 in the left column and the plugins are all sorted properly in the same order:

Modapocalypse NPC's (almost all of them)
BB's Lasses of Skyrim by nightmarezone
Bijin AIO on NexusColdsun's Creations Definitive Edition, various packs...
All the rest of my individual NPC cosmetic replacers

DizzyXC

**Comment by bradcrabtree** [comment]
Also, Lydia Private Version is being sorted by LOOT before Bijin AIO and Coldsun's Creations Definitive Edition Packs. Individual replacers always need to be sorted below multiple replacers. 
https://www.nexusmods.com/skyrimspecialedition/mods/20318

**Comment by bradcrabtree** [comment]
Also, TKAA Renewal is being sorted by LOOT above the Dark Brotherhood Reborn SR - USSEP Patch. I looked at them in xEdit and TKAA can safely be loaded after where it should be loaded.
https://www.nexusmods.com/skyrimspecialedition/mods/34909

DizzyXC

**Comment by sibir-ine** [comment]
@bradcrabtree, you didn't link to _Bijin AIO_, _ColdSun's Creations - Definitive Edition_, or _TKAA Renewal_. I'm assuming _Bijin AIO_ is found [here](https://www.nexusmods.com/skyrimspecialedition/mods/1825), _TKAA Renewal_ is [here](https://www.nexusmods.com/skyrimspecialedition/mods/48297), & _ColdSun's Creations - Definitive Edition_ was [here](https://www.nexusmods.com/skyrimspecialedition/mods/61148), though your confirmation would be appreciated. Since the Nexus page for _ColdSun's Creations - Definitive Edition_ was deleted, unless the mod author moved it to another page that you're aware of, there's nothing we can do about it. We don't add metadata for mods that aren't publicly available as it makes them difficult to deal with for maintainers who can't gain access to them legitimately, so you'll have to add user rules for LOOT to sort it how you want.

**Comment by sibir-ine** [comment]
Re _Better Vampire NPCs_ & _BB's Lasses of Skyrim Redux_, there is no correct load order. Even though you're using the version of BVNPC without appearance changes, the mods both need to make edits to the records for some vampire NPCs, so loading one after the other will override the changes made by the other. You'd need to patch them (or see if someone already made a patch) to resolve those conflicts. A Bashed Patch would resolve most of them automatically if you load _BB's Lasses of Skyrim Redux_ after BVNPC, so you can add a user rule for them. It's the same case with _Modpocalypse NPCs_ & any other NPC appearance mod.

There's also no correct order between different NPC appearance mods as those are personal preference & usually dependent on your install order, something LOOT has no control over & can't reliably determine. As you said, it does make sense to always load one NPC appearance mod after the other when the group of NPCs it edits is a subset of the group the other mod edits. That being said, LOOT's default sorting will usually sort that way unless other load rules or plugins complicate things. Do you have any user-added rules (i.e., groups, load afters, requirements) for _Bijin AIO_, _ColdSun's Creations - Definitive Edition_, or _Lydia Private Version_? I can't find _ColdSun's Creations - Definitive Edition_, but LOOT sorts _Lydia Private Version_ after _Bijin AIO_ as expected on my end.

Re _TKAA Renewal_ & the _Dark Brotherhood Reborn_ USSEP patch, a load after should be fine.

**Comment by MacSplody** [comment]
There's also [EasyNPC](https://www.nexusmods.com/skyrimspecialedition/mods/52313/), which can be used to patch NPC appearance overhauls in your load order.

**Comment by sibir-ine** [comment]
I'll close this. Feel free to let us know if you still have issues or concerns.
