### ISSUE TITLE
Dawnguard - Tweaks and Enhancements

### ISSUE THREAD

**Issue by SkyLover264** [loot/skyrimse#2427]
The esp file for [Dawnguard - Tweaks and Enhancements](https://www.nexusmods.com/skyrimspecialedition/mods/53364) has been renamed from "Dawnguard - Radiant Quest Requirements.esp" to "Dawnguard - Tweaks and Enhancements.esp" as of version 0.2. It has also been relocated to the above-linked page. Also, in case it affects any compatibility notes, the feature where you could request Serana not raise dead enemies has been split off into an optional add-on (Filename: Dawnguard - TnE - Serana Necro Dialogue.esp).

EDIT: I almost forgot. The new version also rerolled the formIDs in order to be esl-ified, so any submods made off of the older version will no longer work.

**Comment by sibir-ine** [comment]
Thanks for the report!
