### ISSUE TITLE
Cyclic Interaction detected between  "Immersive Citizens - ELE patch.esp" and "Better Skill and Quest Books Names SE.esp"

### ISSUE THREAD

**Issue by ghost** [loot/skyrimse#246]
Failed to sort plugins. Details: Cyclic interaction detected between "Immersive Citizens - ELE patch.esp" and "Better Skill and Quest Books Names SE.esp". Back cycle: Better Skill and Quest Books Names SE.esp, ELE_SSE.esp, Immersive Citizens - ELE patch.esp

Found on [/r/skyrimmods](https://old.reddit.com/r/skyrimmods/comments/8z3kpg/problem_with_loot_during_darkladylexys_guide/).

**Comment by MacSplody** [comment]
@bpipher0225 I'd have to see their load order and userlist.txt for the custom rules they're using. The are no rules currently for Better Skill and Quest Books Names SE.esp

**Comment by ghost** [comment]
@CptMcSplody I believe they're following DarkLexy's LOTD metadata guide, which I forgot to post.  I might edit this as I double check this is the only recommendations she has regarding these.
[DarkLexy guide](http://wiki.step-project.com/User:DarkladyLexy/Lexys_LOTD_SE#.5BBetter_Skill_and_Quest_Books_Names_SE.5D)
[Better Skills and Quest book names SE metadata suggestions](https://imgur.com/a/vkmvMMh)
[Enhanced Lighting for ENB metadata suggestions](https://imgur.com/a/mLBRKvC)

**Comment by MacSplody** [comment]
Well I don't think it's a good idea to add any rules for merge plug-ins that use the original file name. But I'll have a look and see why it's happening.

**Comment by ghost** [comment]
I remember seeing this also mentioned on either the Lexy:LOTD or LOTD discord at some point so I'll admit I had assumed the interaction was more generic than it probably is, and might just be an error on the guide steps/user-error.

**Comment by MacSplody** [comment]
Their issue is that `Immersive Citizens - ELE patch.esp` is in a group below `Better Skill and Quest Books Names SE.esp`, and `ELE_SSE.esp` is in a group after `Better Skill and Quest Books Names SE.esp`.

`Immersive Citizens - ELE patch.esp` should load after `ELE_SSE.esp` but can't because of the group conflict. Tell them to move `Immersive Citizens - ELE patch.esp` to the same group as `ELE_SSE.esp`.
