### ISSUE TITLE
"Official/Unofficial" Patches to mods

### ISSUE THREAD

**Issue by ghost** [loot/skyrimse#247]
A couple of examples:

- [x]  [SIC](https://www.nexusmods.com/skyrimspecialedition/mods/18639?tab=description) - Author claims to have permissions from SIC author(s) to run an "official patch", includes the fixed circular leveled list.

~- [ ]  [Campfire and Frostall](https://www.nexusmods.com/skyrimspecialedition/mods/17925) - This is, I believe, the update Chesko posted on his github.  So while not "officially" endorsed, it is Chesko's own update/code.~

- [ ]  [Moonpath to Elsweyr](https://www.nexusmods.com/skyrimspecialedition/mods/15882/) - This one I find questionable posting as it could be debated on it being a true "patch", but it's probably worth a thought.

It might be worth tagging these sort of patches when the present versions are installed until the authors themselves incorporate the changes officially into a new version.

**Comment by MacSplody** [comment]
#363
