### ISSUE TITLE
Wildcat and Ultimate Combat - Compatibility

### ISSUE THREAD

**Issue by cmeeren** [loot/skyrimse#251]
Please remove UltimateCombat.esp from the "Load after" rules for Wildcat (added in 55e23755e2149c12dd76b4408ff0e0c2cb7b07aa). First of all, the Wildcat and Ultimate Combat pages give conflicting advice, and second, if using them both one needs to control their order manually based on patches (e.g. OMEGA MLU says to load Ultimate Combat after Wildcat, which is currently impossible due to the masterlist rule).

**Comment by MacSplody** [comment]
Well I'm not against removing the rule. 
I'd just like some details on what effect loading one after the other has.

> First of all, the Wildcat and Ultimate Combat pages give conflicting advice

A lot of mods do, comparison for reference.

##### Wildcat Compatibility Notes.
> Ultimate Combat: Compatible. Load Wildcat below Ultimate Combat. Timed blocking: Both mods add timed blocking, so you may want to disable one or the other in its MCM or configuration power to eliminate redundancy.

##### Ultimate Combat Description page.
> ASIS, ERSO, Enhanced Enemy AI, ACE, High Level Enemies, Combat Evolved, Wildcat, Requiem
Deadly Combat, Duel - Combat Realism
and almost other mods is compatible with this mod. This Mod is placed after from these mods.
If there is same function, turn off either one. 

Well their aren't any major conflicts records wise, but they both handle combat their own way through scripts. Strictly speaking they should be incompatible by nature, but both have MCM to disable features.
![image](https://user-images.githubusercontent.com/1944639/42783000-820460a4-8942-11e8-978e-d8531aabcee5.png)

> (e.g. OMEGA MLU says to load Ultimate Combat after Wildcat, which is currently impossible due to the masterlist rule).

Well it's not impossible, just inconvenient.

This will require some testing as there doesn't appear to be any direct conflict, and it could just come down to preference.

**Comment by cmeeren** [comment]
How is it possible to override master list rules in LOOT?

**Comment by cmeeren** [comment]
I'm any case, I suggest removing the rule so that user defined rules can be used until a clear answer can be established.

**Comment by MacSplody** [comment]
@cmeeren You either manually move it, or turn off update master list on sort and edit your local copy of the master list.

Edit: I've left a message on both their pages for feedback. I think the best thing would be to remove the load after rule, and place Wildcat in a group after default. That way the user can add a load after rule to Ultimate Combat themselves to override LOOT sorting.

**Comment by cmeeren** [comment]
Great, thanks!
