### ISSUE TITLE
RAID weathers should load after Wet & Cold

### ISSUE THREAD

**Issue by bartmoss** [loot/skyrimse#2510]
Hi there,

According to RAID weathers, that mod should load **after** Wet & Cold. LOOT does not currently sort the mods correctly. (I just tested it, with current LOOT and masterlist.)

Source: https://www.nexusmods.com/skyrimspecialedition/mods/63116 under "Compatibility"

ESP name Raid Weathers: "RAID Weathers.esp"
ESP name Wet & Cold: "WetandCold.esp"

(Without quotes, obviously.)

**Comment by sibir-ine** [comment]
Thanks for the report!
