### ISSUE TITLE
Faster Vanilla Start

### ISSUE THREAD

**Issue by Pickysaurus** [loot/skyrimse#2512]
Please add [my mod](https://www.nexusmods.com/skyrimspecialedition/mods/72890) as incompatible with [Alternate Start: Live Another Life](https://www.nexusmods.com/skyrimspecialedition/mods/272).

Technically they don't conflict but it's a case of whichever loads last will be the one the game uses. 

(My mod changes a global to 3 or 4, AS:LAL change it to 5).

**Comment by sibir-ine** [comment]
Thanks for the report!
