### ISSUE TITLE
Even Better Quest Objectives v1.9.x

### ISSUE THREAD

**Issue by ChristopherC71** [loot/skyrimse#2528]
Hello, I have the latest LOOT v0.18.4 and Loot is not seeing a patch for 'BetterQuestObjectives - Thieves Guild For Good Guys Patch.esp'.

It is active in my load order and is getting flagged.

[Even Better Quest Objectives SE - EBQO SE](https://www.nexusmods.com/skyrimspecialedition/mods/159/)

**Comment by MacSplody** [comment]
Patch name was changed from
`EvenBetterQuestObjectives - Thieves Guild For Good Guys Patch.esp`
to
`BetterQuestObjectives - Thieves Guild For Good Guys Patch.esp`

Just ignore the message for now until the msterlist is updated.

**Comment by sibir-ine** [comment]
Thanks for the report!
