### ISSUE TITLE
Incompatibility ? Cyclic interaction error

### ISSUE THREAD

**Issue by suamor** [loot/skyrimse#2529]
Neither me nor mod author does understand the following cyclic interaction reported from Loot:

There is a cyclic interaction between
RealisticWaterTwo.esp and the SDA NFF Patch. I use latest version (5.4.1 / 1.5) of both mods.

RealisticWaterTwo.esp (https://www.nexusmods.com/skyrimspecialedition/mods/2182)
[Master]
JKs Skyrim_RWT_Patch.esp (https://www.nexusmods.com/skyrimspecialedition/mods/6289)
[Group]
nwsFollowerFramework. (https://www.nexusmods.com/skyrimspecialedition/mods/55653)
[Master]
SDA NFF Patch.esp (https://www.nexusmods.com/skyrimspecialedition/mods/70782)
[Group]
RealisticWaterTwo.esp

In the group editor I see two non-empty groups: DLC (obvious) and default (all mods but DLC).
Is there a really a conflict to Realistic Water Two from SDA ?

I have reinstalled all patched and now I have a different mod instead of JKs_Skyrim_RWT_Patch:
Lux - RWT Patch.esp (https://www.nexusmods.com/skyrimspecialedition/mods/43158 - installed yesterday as well, before the installation of other mentioned mods).

Fix: Edit Metadata, "Load After" and add a new column with the RealisticWaterTwo.esp.

**Comment by MacSplody** [comment]
> Neither me nor mod author does understand the following cyclic interaction reported from Loot:
> 
> There is a cyclic interaction between RealisticWaterTwo.esp and the SDA NFF Patch. I use latest version (5.4.1 / 1.5) of both mods.
> 
> RealisticWaterTwo.esp (https://www.nexusmods.com/skyrimspecialedition/mods/2182) [Master] JKs Skyrim_RWT_Patch.esp (https://www.nexusmods.com/skyrimspecialedition/mods/6289) [Group] nwsFollowerFramework. (https://www.nexusmods.com/skyrimspecialedition/mods/55653) [Master] SDA NFF Patch.esp (https://www.nexusmods.com/skyrimspecialedition/mods/70782) [Group] RealisticWaterTwo.esp
> 
> In the group editor I see two non-empty groups: DLC (obvious) and default (all mods but DLC). Is there a really a conflict to Realistic Water Two from SDA ?
> 
> I have reinstalled all patched and now I have a different mod instead of JKs_Skyrim_RWT_Patch: Lux - RWT Patch.esp (https://www.nexusmods.com/skyrimspecialedition/mods/43158 - installed yesterday as well, before the installation of other mentioned mods).

You've put nwsFollowerFramework into the late loaders group.
If `RealisticWaterTwo.esp` and `nwsFollowerFramework.esp` share the same group, then you will need to set one to load after the other.

**Comment by MacSplody** [comment]
> Fix: Edit Metadata, "Load After" and add a new column with the RealisticWaterTwo.esp.
