### ISSUE TITLE
Holds The City Overhaul

### ISSUE THREAD

**Issue by Ember2528** [loot/skyrimse#2543]
Holds is meant to be placed near the end of the load order, mostly to avoid issues from landscape conflicts, right above mods like A Clear Map of Skyrim or lighting mods like Lux or Enhanced Lighting and FX. LOOT always places it near the top of the load order.

https://www.nexusmods.com/skyrimspecialedition/mods/10609

**Comment by sibir-ine** [comment]
I'm not particularly familiar with landscape conflicts, but it seems like loading it late would at best just overwrite landscape changes made by other mods. I think a better solution may be to add load rules for specific plugins that Holds should load after without needing a patch. Plugins where conflicts are more severe can be noted as incompatible. If you're aware of any such cases, please feel free to report them to us.

**Comment by Ember2528** [comment]
Galandil made the mod with it being late in the load order in mind in order to reduce the amount of mods that would need patches so things like grass mods that make landscape edits would just be covered up by buildings added by Holds while if Holds was loaded earlier some buildings might be half covered by landscape.

That said, Landscape Fixes for Grass Mods is the only one I'm aware of that causes huge issues unless it is above Holds. It has a patch, though the main Holds esp still needs to be bellow it.

**Comment by MacSplody** [comment]
If you wanted to test loading the AIO version after most files then you can add a group after default.
![image](https://user-images.githubusercontent.com/1944639/188441190-c4c5d4e5-aa86-4e10-8d1e-d53f6be9ab07.png)

You could do the same for the modular version, but you'd have to use multiple groups or one group with a set order.

> That said, Landscape Fixes for Grass Mods is the only one I'm aware of that causes huge issues unless it is above Holds. It has a patch, though the main Holds esp still needs to be bellow it.

Is it not sorting Holds after Landscape fixes by default?

Edit:
Default sorting.

![image](https://user-images.githubusercontent.com/1944639/188463736-bda92962-6fe4-4419-86b0-e4dc28aa37f5.png)

**Comment by MacSplody** [comment]
There's an updated version available on [Holds Special Edition Compatibility Patches](https://www.nexusmods.com/skyrimspecialedition/mods/20685/).

**Comment by MacSplody** [comment]
From Landscape Fixes - Holds patch installer.

> Any issues caused by these patches should be directed to the Landscape Fixes For Grass Mods Nexus Mods page https://www.nexusmods.com/skyrimspecialedition/mods/9005/  do NOT ask for support about these patches from Galandil or on their mod (Holds The City Overhaul) pages.
> 					
> If you use Holds optional road plugin (HoldsRoads.esp) that file will override a large number of edits in Landscape Fixes For Grass Mods and is not recommended to use alongside it as no patch will be provided for it by me. Also all of these patches much load after that plugin to work. 
>
> If you really want to use the road plugin alongside LFFGM I recommend removing all landscape records from that file with xEdit since LFFGM cannot load after Holds.esp, you will just have texture seams along roads but most should be hidden by grass depending your set-up.

**Comment by MacSplody** [comment]
Even with the patch, Landscape fixes still needs to be placed before Holds.

![image](https://user-images.githubusercontent.com/1944639/188468301-15589002-c61d-4f31-b7f4-7f14a68c0f77.png)

**Comment by MacSplody** [comment]
Both the original and updates have the same version info in their file header.
And the update has one ITM, so its checksum isn't reliable.
The update does include the `HoldsComplete_DISTR.ini` file for [Spell Perk Item Distributor (SPID)](https://www.nexusmods.com/skyrimspecialedition/mods/36869/).
That could be used for an update patch message and requirement checks.

**Comment by MacSplody** [comment]
Could be intentional, but would cause issues with any other mods that alter the size of these worldspaces.

![image](https://user-images.githubusercontent.com/1944639/188473935-b8028e6c-5794-4972-9942-929bee82bed5.png)

Possibly placed there by mistake, the extra empty cells shouldn't be required.
![image](https://user-images.githubusercontent.com/1944639/188474001-870709ae-2534-4b91-8e83-1c92b291dda1.png)

![image](https://user-images.githubusercontent.com/1944639/188474674-63308979-6047-41a3-ac77-6a77a831f73f.png)

**Comment by Ember2528** [comment]
Alright. The new order seams to not have buried buildings anymore, at least running around the areas I knew had problems before. I'll close this and if I find any other problems report it to the authors or here if I find another mod.

**Comment by MacSplody** [comment]
> Alright. The new order seams to not have buried buildings anymore, at least running around the areas I knew had problems before. I'll close this and if I find any other problems report it to the authors or here if I find another mod.

It can be left open for now, there are still some updates that I want to make in relation to this issue.

**Comment by pStyl3** [comment]
@MacSplody Can you define a list of things that should be worked on for this? Otherwise I'd like to close the issue, because I'm not sure what is left to do here.

**Comment by MacSplody** [comment]
> @MacSplody Can you define a list of things that should be worked on for this? Otherwise I'd like to close the issue, because I'm not sure what is left to do here.

Not at the moment, as I don't have a whole lot installed to test it against.
We can close it for now, I can revisit it if needed.
