### ISSUE TITLE
Vokrus incorrect master sorting

### ISSUE THREAD

**Issue by Ember2528** [loot/skyrimse#2546]
Vokrus is an addon for Vokrii that adds a handful of Ordinator perks to the trees and ships with an esp replacer for Ordinator. It needs Ordinator loaded before Vokrii otherwise it will have a variety of issues and currently LOOT places Ordinator before Vokrii

https://www.nexusmods.com/skyrimspecialedition/mods/63384

**Comment by MacSplody** [comment]
We have logic for some similar mods already, so we just need to update the load after rules.

Also need to add:
Incompatible with
[Vokriinator - Choice Cuts](https://www.nexusmods.com/skyrimspecialedition/mods/26702/)
[Path to Ordinance](https://www.nexusmods.com/skyrimspecialedition/mods/37296/)
