### ISSUE TITLE
Update, DLC & USSEP bash tags

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#255]
For reference [Wrye Bash Advanced Readme Latest Version](http://wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html#patch-tags)
#254 
##### Update.esm
```
Actors.CombatStyle
Actors.Stats
C.Encounter
C.Location
C.RecordFlags
C.Regions
C.Water
Deflst
Delev
Factions
Graphics
Invent
Names
NPC.Class
NpcFaces
Scripts
SpellStats
Stats
```
##### Dawnguard.esm
```
Actors.DeathItem
Actors.Spells
C.Location
C.RecordFlags
C.Regions
C.Water
Delev
Graphics
Invent
Names
NPC.Class
NPC.Race
NpcFaces
Relations
Relev
Scripts
Sound
SpellStats
```
##### Hearthfires.esm
```
Actors.AIPackages
C.Location
C.Water
Factions
Graphics
Invent
NpcFaces
Scripts
Sound
```
##### Dragonborn.esm
```
Actors.AIData
Actors.Stats
C.Location
C.Water
Factions
Graphics
Invent
Names
NpcFaces
Relev
Scripts
SpellStats
Stats
```
##### Unofficial Skyrim Special Edition Patch.esp
```
Actors.AIData
Actors.AIPackages
Actors.CombatStyle
Actors.DeathItem
Actors.Spells
Actors.Stats
Body-Size-F
Body-Size-M
C.Acoustic
C.Climate
C.Encounter
C.ImageSpace
C.Light
C.Location
C.Music
C.Name
C.Owner
C.RecordFlags
C.Regions
C.Water
Deflst
Delev
Factions
Graphics
Invent
Names
NPC.Class
NPC.Race
NpcFaces
R.ChangeSpells
Relations
Relev
Scripts
Sound
SpellStats
Stats
```

**Comment by Ortham** [comment]
I think I recall reading that the readme is a little outdated in terms of Bash Tags, and besides that, remember that Mator Smash (I think that's the name) supports a much larger set of tags, so don't go removing any that it can use.

**Comment by MacSplody** [comment]
@WrinklyNinja Yeah it probably is, I won't be removing bash tags from the masterlist, just wanted to get an idea of which tags would be of use for SSE.

**Comment by MacSplody** [comment]
https://github.com/wrye-bash/wrye-bash/commit/4dc69da89346cb48bc0da1c2f20d60af097bd51f#diff-ee6b65e7d33f57047cdeaa2df3d00d1cL60

Latest changes for SSE tags in upcoming 307 beta.

**Comment by MacSplody** [comment]
Working on updating these at the moment. 
I updated the wrye bash doc myself as it was outdated.
https://github.com/CptMcSplody/wrye-bash/tree/advanced-readme-bashtags/Mopy/Docs

**Comment by MacSplody** [comment]
#277
