### ISSUE TITLE
B&B126 and Radiant Prostitution are not sorted properly 

### ISSUE THREAD

**Issue by zyf2008Neptune** [loot/skyrimse#2559]
b&b126 https://arca.live/b/tullius/4930700
Radiant Prostitution https://www.loverslab.com/files/file/17325-radiant-prostitution-gigolo-se/

B&B 126 changes Hulda in whiterun ,  but loot sorts it before Radiant Prostitution and causes black face.

**Comment by sibir-ine** [comment]
If they're both making changes to Hulda, you'll probably need to manually patch them with, e.g., xEdit. You can add a load rule on your end to sort them the way you want to if you'd rather not patch them, but that wouldn't really be appropriate to add to the masterlist.

**Comment by sibir-ine** [comment]
I'll close this as there hasn't been a response. Feel free to let us know if I've incorrectly assessed the situation & a masterlist load rule is actually appropriate.
