### ISSUE TITLE
Repositioning for AS-LAL and OCS

### ISSUE THREAD

**Issue by Arthmoor** [loot/skyrimse#259]
I need to ask for a repositioning on Alternate Start - Live Another Life and Open Cities Skyrim.

I've issued updates to each one to move OCS below LAL in the load order in order to preserve region and location data in OCS that LAL was blocking and has been blocking for a long time. This was done to resolve the only incompatibility between the 2 mods and involved having to change scripting on a single marker which was in the way for each one.

I'm not entirely sure what the current list structure looks like but LAL should be moved directly underneath any section that contains village mods, but before any city overhauls. That may be a bit of a special space, but it's probably what will work best for LAL.

OCS should remain as far down the list as it can go.

**Comment by MacSplody** [comment]
@Arthmoor Current order is  

City & village Overhauls (Default Group) -> OCS -> Alt Start.

So if I'm following correctly the new order would be as follows.

City Overhauls ->  Alt Start LAL -> Village Overhauls ( JK Riverwood, Dawnstar etc.? ) -> OCS

**Comment by Arthmoor** [comment]
It should become:

Village Overhauls (Mine, JKs, ETaC, etc) -> Alt Start -> City Overhauls (The 5 walled capitals) -> OCS

**Comment by MacSplody** [comment]
@Arthmoor Change has been submitted in #262. Just waiting on some feedback from @WrinklyNinja
