### ISSUE TITLE
CRAFT

### ISSUE THREAD

**Issue by fuchsberger** [loot/skyrimse#2591]
Would it be possible to add CRAFT.esp into High Priority Overwrites?
It changes only crafting recipes but that would ensure that it overwrites all mod's recipes as intended. All patches (and there are many) will then also autosort right below making this section of a modlist very organized and not spread out.

Thanks for considering!

**Comment by sibir-ine** [comment]
Can you please link to the mod? Can you also please explain why **High Priority Overrides** instead of, e.g., **Crafting**?

**Comment by fuchsberger** [comment]
sorry forgot, here you go
https://www.nexusmods.com/skyrimspecialedition/mods/54900

- it allows to make crafting changes after mods such as WACCF which is intented. 
- it also ensures changes after any 3d party patches which are in abundance. since CRAFT only chances crafting recipies and they are not referenced anywhere else they should always have highest priority

**Comment by fuchsberger** [comment]
my apologies. now that i look at the groups again, Crafting would probably work just as fine and be more appropriate in title

**Comment by fuchsberger** [comment]
thanks!

**Comment by sibir-ine** [comment]
You're welcome, thanks for reaching out!
