### ISSUE TITLE
Book Covers Skyrim Updated

### ISSUE THREAD

**Issue by sibir-ine** [loot/skyrimse#2594]
[Link 1](https://www.nexusmods.com/skyrimspecialedition/mods/58376/), [Link 2](https://www.nexusmods.com/skyrimspecialedition/mods/69568/)

- [x] Add a message that they can't be used together
- [x] Add incompatibility with LotD as original is integrated into it, but don't display for dummy plugin from second link
- [x] Some of its patches are also missing masters, so add requirements as necessary

**Comment by Sabre142** [comment]
Another location for this plugin: [Book Covers Skyrim Updated REDUX 4K-2K](https://www.nexusmods.com/skyrimspecialedition/mods/69568/)

**Comment by XilaMonstrr** [comment]
Error still occurring for the empty plugin (LotD patch) on the Redux version

**Comment by sibir-ine** [comment]
This is the metadata for the error message:

```yaml
    inc:
      - name: 'LegacyoftheDragonborn.esm'
        condition: 'not checksum("Book Covers Skyrim Updated.esp", 6D8408E1)'
```

The checksum is for the plugin from the *Patch - Legacy of the Dragonborn* package from your page (I just double-checked to confirm), so the message will only display if the plugin doesn't have that checksum. LOOT displays the plugin's checksum in its card in brown after initiating a sort, so you can verify there that the plugin as downloaded matches. Have you made any changes to the plugin on your end? If you plan on uploading it, we can add that checksum to the condition once you're ready to do so (or after you do). However, if it's just for personal use, then that's not something we can realistically address on our end as we need the plugins that we add metadata for to be publicly & freely available.

**Comment by XilaMonstrr** [comment]
Ah, I think this was happening due to using an older version of the plugin. Thanks.

**Comment by sibir-ine** [comment]
You're welcome!
