### ISSUE TITLE
UCOW Smash Fix should load before UCOW

### ISSUE THREAD

**Issue by Gh0sTG0** [loot/skyrimse#2638]
Hi.
UCOW Smash Fix.esp from https://www.nexusmods.com/skyrimspecialedition/mods/39378
UltimateCollege.esp and info from https://www.nexusmods.com/skyrimspecialedition/mods/44797
There should be this way of loading:
CollegeOfWinterholdImmersive.esp->OCW_Obscure's_CollegeofWinterhold.esp->UCOW Smash Fix.esp->UltimateCollege.esp
Smash fix should be loaded exactly on 3rd position.
For me loot changed last 2 things and tried to load smash fix after college.

**Comment by MacSplody** [comment]
Add a custom rule to load `UltimateCollege.esp` after `UCOW Smash Fix.esp`, that will fix the issue on your end until the masterlist is updated.

**Comment by Gh0sTG0** [comment]
TY, already did that. Just wanted that thing to get fixed globally, for other 29,276 of that, who downloaded ucow xD
If someone of them are using smash and loot xD

**Comment by sibir-ine** [comment]
Thanks for the report!
