### ISSUE TITLE
Eli's Breezehome & ELFX Shadows

### ISSUE THREAD

**Issue by Gh0sTG0** [loot/skyrimse#2639]
Eli's Breezehome should load after ELFX Shadows to preserve cell settings in a single record. However, the apparently optional ELFX add-on from the Optimization replacer (i.e., `Eli_Breezehome [ADDON - ELFX-FX].esp`) resolves the conflict as well, so loading that after if present would be sufficient.

**Original**:
Hi.
Info from [here](https://www.nexusmods.com/skyrimspecialedition/mods/48931) - "Using "Enhanced Lights and FX (ELFX)" with or without "ELFX Shadows"" spoiler.
There should be:

> EnhancedLightsandFX.esp
> ### ﻿ELFX - NoPlayerHomes.esp
> ﻿﻿ELFX Shadows.esp﻿
> Eli_Breezehome.esp

LOOT sorted for me smth like:

> EnhancedLightsandFX.esp
> ﻿﻿ELFX Shadows.esp﻿
> Eli_Breezehome.esp
> ### ELFX - NoPlayerHomes.esp

PS I already added some custom rules for me. But hope that can be added to main masterlist =)

**Comment by sibir-ine** [comment]
The masterlist already has load rules to follow this order:

```yaml
  - name: 'Eli_Breezehome.esp'
    ...
    after:
      - 'ELFX - NoBreezehome.esp'
      - 'ELFX - NoPlayerHomes.esp'
```

Is your masterlist up-to-date? Make sure by pressing the **Update Masterlist** button. Do the filenames of your copies of these plugins differ from what's in the masterlist in any way?

**Comment by Gh0sTG0** [comment]
I'm not sure how that happens. I installed LOOT maybe a week ago or smth like that.
I updated masterlist that date.
I didn't rename anything, mods installed by mo2 (downloaded and installed that date too).
PS I did some thinking...
I can't remember correct: was "ELFX - NoPlayerHomes.esp" after breezehome or it was after shadows... Maybe it was after shadows (when manual recommends to put it before the shadows, hmmm...

**Comment by sibir-ine** [comment]
They sorted before Shadows for me automatically with a minimal setup, but rules could be added if that wasn't the case for you.

**Comment by Gh0sTG0** [comment]
> They sorted before Shadows for me automatically with a minimal setup, but rules could be added if that wasn't the case for you.

TY for your answers. I'm really... not even making a request, but rather sharing my observations

**Comment by sibir-ine** [comment]
Thanks for the report!
