### ISSUE TITLE
Some mods with incompatibilities between them

### ISSUE THREAD

**Issue by Freso** [loot/skyrimse#264]
On Discord, @eFrysTon mentioned some plugins that have conflicts between them that LOOT doesn't know about:

- [x] "Joy of Perspective" and "UNP Vanilla Outfits"
- [x] "Joy of Perspective" and "Cutting Room Floor"
- [x] "Bijin AIO" and "Cutting Room Floor"
- [x] "Cosmetic Vampire Overhaul SSE" and "Cutting Room Floor"

**Comment by MacSplody** [comment]
https://github.com/loot/skyrimse/pull/348 "Bijin AIO" and "Cutting Room Floor"

**Comment by MacSplody** [comment]
#364 Joy of Perspective Compatibility Messages

**Comment by MacSplody** [comment]
#366 Cosmetic Vampire Overhaul
