### ISSUE TITLE
Immersive Armors plugins sorted incorrectly.

### ISSUE THREAD

**Issue by Chef0000** [loot/skyrimse#268]
The two plugins for Immersive Armors are sorted incorrectly in relation to each other.  

Hothtrooper44_ArmorCompilation.esp needs to load after
Hothtrooper44_Armor_Ecksstra.esp

This is stated on the mod page, in the 3rd post for both the SSE and SLE versions.

The load order after activating the two .esp files is :
Hothtrooper44_Armor_Ecksstra.esp
Hothtrooper44_ArmorCompilation.esp

Also, this is from the Posts section for the SLE version:

Eckss 191 kudos 1724 posts 
It's not a replacer. It's necessary because IA has more assets than will fit into 1 .bsa file.
Hothtrooper44 Armor Ecksstra .esp activates more than half of the textures in IA and should be loaded before Hothtrooper44 ArmorCompilation.esp. 
posted @ 7:18, 28 Nov 2015 

Eckss is co-developer of Immersive Armors (hence the ECTSStra)

**Comment by MacSplody** [comment]
@93sc It shouldn't matter as long as both plug-ins & bsa are loaded.

**Comment by Chef0000** [comment]
Alright, thanks for your time.

**Comment by MacSplody** [comment]
@93sc No worries, thanks for the effort.
