### ISSUE TITLE
LOOT sorting for AIO & CRF

### ISSUE THREAD

**Issue by z929669** [loot/skyrimse#2689]
The author of AI Overhaul states explicitly on the [AI Overhaul - Official Patch Hub file](https://www.nexusmods.com/skyrimspecialedition/mods/35823?tab=files) that Cutting Room Floor should be loaded at lower priority than AIO. LOOT currently gives CRF higher priority. I have reported this to the author, but I'm also reporting here, since I can.

As an afterthought, I also mentioned to the AIO author, that the current LOOT sorting is probably just fine and that the AIO-CRF patch can simply remove the redundant records when CRF sorts at higher priority.

**Comment by sibir-ine** [comment]
Thanks for the report!
