### ISSUE TITLE
An outdated report about Immersive Patrols SE AE and Requiem

### ISSUE THREAD

**Issue by ghost** [loot/skyrimse#2748]
```
Immersive Patrols II.esp
You seem to be using Requiem - The Roleplaying Overhaul, but you have not enabled a compatibility patch for this mod. 
A third party patch is available here: Requiem Patch Central
```
This is outdated because Requiem Patch Central has removed this patch which is no needed anymore. 

Changelog in Requiem Patch Central version 5.01:

```
Removed patch for Immersive Patrols. Immersive Patrols v3.0 is compatible without a patch.
```

**Comment by sibir-ine** [comment]
What game do you have selected in the games drop-down menu? Skyrim or Skyrim SE? What version of LOOT are you using? The message was removed a while ago in the SE masterlist & is still present in the LE masterlist, so you're either somehow using the LE masterlist, or your masterlist is outdated which is probably more likely. Versions before v0.18.0 cannot download the latest version of the masterlist which contains this change, so you'll need to update if you haven't already. If you have, just update your masterlist by either pressing the **Update Masterlist** button or by sorting (unless you disabled it in the settings).

**Comment by sibir-ine** [comment]
No response in a month, & the message can't possibly display with an up-to-date SE masterlist, so I'm closing this.
