### ISSUE TITLE
KS Dragon Overhaul 2 - Update required

### ISSUE THREAD

**Issue by YTEx13** [loot/skyrimse#2765]
[Link](https://www.nexusmods.com/skyrimspecialedition/mods/19051)

The mod is totally reworked (new plugin .esp) start from 2.6, has new requirement (hard+optional), compatility patch is totally new.

Compatible - No patch needed -
[Ultimate Dragons SE](https://www.nexusmods.com/skyrimspecialedition/mods/26374) - Optional Master.
[Diverse Dragons Collection SE](https://www.nexusmods.com/skyrimspecialedition/mods/695) 
[Splendor - Dragon Variants SE](https://www.nexusmods.com/skyrimspecialedition/mods/9670) 
[Durnehviir Resurrected SE](https://www.nexusmods.com/skyrimspecialedition/mods/14272) 
[Bellyaches New Dragon Species SSE](https://www.nexusmods.com/skyrimspecialedition/mods/5133) ﻿
[Skyrim Immersive Creatures Special Edition](https://www.nexusmods.com/skyrimspecialedition/mods/12680) 
[Chaos Dragons SSE](https://www.nexusmods.com/skyrimspecialedition/mods/24788) 
[Durnehviir God of Death](https://www.nexusmods.com/skyrimspecialedition/mods/12086/) 
[Serio's Enhanced Dragons](https://www.nexusmods.com/skyrimspecialedition/mods/5745) 
[Elemental Dragons Special Edition](https://www.nexusmods.com/skyrimspecialedition/mods/8394/) 
[Zim's Dragon Improvements](https://www.nexusmods.com/skyrimspecialedition/mods/38693) (LIGHT)
[Talkative Dragons](https://www.nexusmods.com/skyrimspecialedition/mods/26955) - Make sure to disable "Combat Dialogue" option at MCM of KSDO2 if you prefer this mod for dragon talking during combat.
[SkyTEST - Harder Creatures](https://www.nexusmods.com/skyrim/mods/12481) - Make sure load this mod before KSDO2.
[Mortal Enemies SE](https://www.nexusmods.com/skyrimspecialedition/mods/4881/) - Make sure load this mod before KSDO2.
[Serio's Enhanced Dragons](https://www.nexusmods.com/skyrimspecialedition/mods/5745) - Make sure load this mod before KSDO2.

Compatible - patch needed -
[Skyrim Unbound Reborn (Alternate Start)](https://www.nexusmods.com/skyrimspecialedition/mods/27962) - Patch ready.
[Thunderchild - Epic Shouts and Immersion](https://www.nexusmods.com/skyrimspecialedition/mods/1460) - Patch ready.
[Timing is Everything SE](https://www.nexusmods.com/skyrimspecialedition/mods/25464) - Patch ready.
[GoT Dragons (A Game of Thrones)](https://www.nexusmods.com/skyrimspecialedition/mods/79252) - Patch ready (See Sticky post at "Post" for patch).
[Zim's Dragon Improvements](https://www.nexusmods.com/skyrimspecialedition/mods/38693) (FULL & HEAVY) - No patch for now.
[Deadly Dragons](https://www.nexusmods.com/skyrimspecialedition/mods/23723) - No patch for now.
[Serio's Enhanced Dragons Redone](https://www.nexusmods.com/skyrimspecialedition/mods/27061) - No patch for now.
[Advanced Adversary Encounters - Ultimate SSE](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjgurOLxNjaAhUJ6KQKHahwB-QQFggpMAA&url=https%3A%2F%2Fwww.nexusmods.com%2Fskyrimspecialedition%2Fmods%2F6843&usg=AOvVaw1B_LmmKbbUJ1Nj4A7K0_2o) ﻿- No patch for now.
[Enhanced Slightly Mighty Dragons V4](https://www.nexusmods.com/skyrimspecialedition/mods/9274) - No patch for now.
[Enhanced Mighty Dragons V4](https://www.nexusmods.com/skyrimspecialedition/mods/5982/) - No patch for now.

Not Compatible or Not Recommended
[Fores New Idles in Skyrim SE – FNIS SE](https://www.nexusmods.com/skyrimspecialedition/mods/3038?tab=files) - FNIS is good to go but not the Creature Pack, please do not install Creature Pack.
[Simply Stronger Dragons (SSD) SE](https://www.nexusmods.com/skyrimspecialedition/mods/9917)
[KS Dragon Overhaul](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwiZhfOmwaThAhWMvY8KHTELDVcQFjABegQIAxAB&url=https%3A%2F%2Fwww.nexusmods.com%2Fskyrimspecialedition%2Fmods%2F12641&usg=AOvVaw1KBuDGLExJWDd4--XCMQ4X) - mod obsolete.
[Dragon Combat Overhaul SSE](https://www.nexusmods.com/skyrimspecialedition/mods/38022/) 
[Dragon Combat Overhaul UPGRADED BABY YEAH](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwj5-7K19_37AhX0V3wKHemWCycQFnoECA4QAQ&url=https%3A%2F%2Fwww.nexusmods.com%2Fskyrimspecialedition%2Fmods%2F56082&usg=AOvVaw0Lp1D8efa3QeQYG0ZDwRXU) 
[Infinite Dragon Variants](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwi4ybXV8v37AhVI6nMBHTEpABIQFnoECBEQAw&url=https%3A%2F%2Fwww.nexusmods.com%2Fskyrimspecialedition%2Fmods%2F74983%23%3A~%3Atext%3DInfinite%2520Dragon%2520Variants%2520is%2520a%2CRaceMenu%252C%2520without%2520touching%2520vanilla%2520records.&usg=AOvVaw11CGLBtE9hTcZo9mZsjgu7) - Not needed/already included in KSDO2.
[Dragon Stalking Fix](https://www.nexusmods.com/skyrimspecialedition/mods/14060) - Not needed/already included in KSDO2.
[Fixed Dragon Stalking Fix](https://www.nexusmods.com/skyrimspecialedition/mods/37230) - Not needed/already included in KSDO2
[Not Another Dragon Stalking Fix](https://www.nexusmods.com/skyrimspecialedition/mods/88238) - Not needed/already included in KSDO2
[Dragonactorscript infinite loop fix](https://www.nexusmods.com/skyrimspecialedition/mods/87940) - Not needed/already included in KSDO2

**Comment by sibir-ine** [comment]
Thanks for the report!
