### ISSUE TITLE
LOOT sorts Paradigm - A Quick Start Overhaul before Aetherius - A Race Overhaul, which doesn't work

### ISSUE THREAD

**Issue by ketsuban** [loot/skyrimse#2776]
`Paradigm - Simonrim Edition.esp` from the mod [Paradigm - A Quick Start Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/85939) needs to be loaded after `AetheriusSpells.esp` from the mod [Aetherius - A Race Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/26686), or creating a new game hangs on the title screen.

**Comment by sibir-ine** [comment]
Thanks for the report! I've moved the mod to the **Alternate Start** group, so it'll load after by default.
