### ISSUE TITLE
4thUnknown - Ancient Shrouded Armor Replacer - SE suggested bash tags

### ISSUE THREAD

**Issue by rafaelkai** [loot/skyrimse#2838]
Mod name: 4thUnknown - Ancient Shrouded Armor Replacer

Mod link: https://www.nexusmods.com/skyrimspecialedition/mods/57552

Mod version: 1.0

Suggested bash tags:

```
 - name: '4thUnknownAncientShroudedReplacer.esp'
    tag:
      - Graphics
```

```
  - name: 'Patch - (4thUnknown - Ancient Shrouded Armor Replacer) - (LOTD).esp'
    tag:
      - Graphics
```

**Comment by Sabre142** [comment]
Only `4thUnknownAncientShroudedReplacer.esp` needed the Graphics bash tag.
