### ISSUE TITLE
ELFX and Lux Compatibility/Order Question

### ISSUE THREAD

**Issue by nosnowowie93347** [loot/skyrimse#2860]
Elfx and Lux

These two mods edit a lot of the same things. Which one should override the other? Is it okay to use the default sorting?

**Comment by MacSplody** [comment]
Both are lighting overhauls, so I wouldn't use both together.
Load order isn't going to resolve anything for these two mods.
I suggest testing both separately, and then pick one.

**Comment by nosnowowie93347** [comment]
Alrighty! Thank you!
