### ISSUE TITLE
Mods not working and game crashing

### ISSUE THREAD

**Issue by ClaperZX23** [loot/skyrimse#2892]
I was running my mods just fine until I installed loot. I ran everything and installed everything right and it all works right. But, when I start Skyrim and continue or load a save, half my mods are deactivated, and the game crashes/ closes every time I press the esc key to pause the game. I do not know if loot did this or not, but it only started happening once I installed loot.

**Comment by pStyl3** [comment]
Closing this issue since the discussion is better suited for our `general-chat` channel on Discord: [Link](https://discord.com/channels/473542112974077963/473721823071043585/1203421101951291452)
