### ISSUE TITLE
RDO / Song of the Green / GDO

### ISSUE THREAD

**Issue by RK3266** [loot/skyrimse#2934]
I noticed that RDO & Song of the Green fall below GDO now after this was implemented: https://github.com/loot/skyrimse/issues/717

From what I've seen it's suggested to put GDO after RDO 

I set up my own edit on the metadata to place GDO after RDO for now.

**Comment by sibir-ine** [comment]
From @MacSplody in the Discord:

> It doesn't work for every load order.
> ICAIO -> RDO -> GDO -> WACCF.
> Immersive citizens, recommended to place it after most other mods. And RDO after ICAIO.
> GDO is supposed to be before WACCF. But then it's recommended to place WACCF before most mods.
> Better to not force rules involving RDO tbh, and let the user add them manually if they want.

**Comment by RK3266** [comment]
Thanks, that makes sense. I created my own rule for now.
