### ISSUE TITLE
Missing Master.

### ISSUE THREAD

**Issue by LindavK1972** [loot/skyrimse#2942]
Hey,

I'm trying to get Legacy of the Dragonborn / Palaces and Castles Enhanced and JK's Skyrim to play nice.
But one of the ESP's is missing : DBM_JKSkyrim_Patch.esp.

Could you check that?

With kindest regards,

Linda

**Comment by sibir-ine** [comment]
Missing master messages are automatically generated based on the masters list of a given plugin, which is a list in the plugin that enumerates its hard plugin requirements. LOOT reads the list & checks to see if each plugin in it is active, displaying a message for any that aren't. If you're seeing the message, that means you need to install & activate that plugin to use whatever plugin requires it. An automatic message like that can't possibly find the missing master & tell you where to find it, so you'll have to read the page of the plugin with the missing master to find it. Mod authors almost always list the requirements of their mods. In this case, the naming convention follows that of the official LotD patches, so check their [patch hub](https://www.nexusmods.com/skyrimspecialedition/mods/30980).

**Comment by sibir-ine** [comment]
I've instructed you on how to resolve your issue, so I'll close this. Feel free to ask for clarification if you still need help.
