### ISSUE TITLE
LOOT lists Base Object Swapper as a requirement for TMD Winery

### ISSUE THREAD

**Issue by modball** [loot/skyrimse#2990]
LOOT seems to be indicating that Base Object Swapper is a requirement for [TMD Winery](https://www.nexusmods.com/skyrimspecialedition/mods/115363) but it is only required if using [Diverse Winery TMD](https://www.nexusmods.com/skyrimspecialedition/mods/115716).

![WB TMDWinery1](https://github.com/user-attachments/assets/62fabe21-5c72-41d4-9cca-e5f80506f107)
![WB TDMWinery2](https://github.com/user-attachments/assets/4f92e768-d291-45ee-b7aa-d2f205fdd4bb)

For some reason this is causing Wrye Bash 3.10 to complain about an illegal file path, with or without DiverseTMDWinery_SWAP.ini present: 
[TDM Wrye bash.txt](https://github.com/user-attachments/files/17787798/TDM.Wrye.bash.txt)

If I rename TMDWinery.esp the error does not occur.

**Comment by Sabre142** [comment]
Base Object Swapper is only listed as a requirement for this mod in LOOT on the condition that you have `DiverseTMDWinery_SWAP.ini` present. `DiverseTMDWinery_SWAP.ini` is from Diverse Winery - TMD, which does require Base Object Swapper. Simply delete ` DiverseTMDWinery_SWAP.ini` if you have stopped using the Diverse Winery - TMD mod, if the `DiverseTMDWinery_SWAP.ini` is still there in your Data folder.

You can see the requirement here in the masterlist is conditional:

```yaml
    req:
      - <<: *BaseObjSwap
        condition: 'file("DiverseTMDWinery_SWAP.ini")'
```

You should also update your Wrye Bash version to the latest version [here](https://www.nexusmods.com/site/mods/591), which is currently version 313.
