### ISSUE TITLE
Sweet as Honeyside

### ISSUE THREAD

**Issue by Spu00Key** [loot/skyrimse#30]
Load Order's need adjustment for [Sweet as Honeyside](http://www.nexusmods.com/skyrimspecialedition/mods/918/?).
- ELFX has a patch for this to remove the lighting changes.
- @Arthmoor Alternative Start reverts to master lighting changes by Honeyside.

If no objection in 7 days I'll update the master as follows per Author's Description:
ELFX - NoHoneyside.esp
Alternate Start - Live Another Life.esp
Honeyside.esp

**Comment by Freso** [comment]
Go for it! 👍 It can be changed later if users report problems with that order.

**Comment by Spu00Key** [comment]
Closed with PR #35.
