### ISSUE TITLE
LOOT having an issue running

### ISSUE THREAD

**Issue by DragonHearted99** [loot/skyrimse#322]
All, 
I have tried multiple time to run LOOT 0.13 and keep having the "oops" problem. Please find the attached LootDebugLog.txt.  Any light you can shed for me would be much appreciated.

[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/2344180/LOOTDebugLog.txt)

Thank You, 
DH

**Comment by DragonHearted99** [comment]
Here is some additional information after I deleted the LOOT folder from user/morphy/appdata/local/Loot folder

[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/2344201/LOOTDebugLog.txt)
![loot 0 13 first screen](https://user-images.githubusercontent.com/42924343/44967521-7774a380-af74-11e8-870f-93b1a8627206.jpg)
![loot 0 13 error after hitting sort](https://user-images.githubusercontent.com/42924343/44967525-80fe0b80-af74-11e8-82f2-f656afb5ec11.jpg)

**Comment by pStyl3** [comment]
What Antivirus program do you use? It may be the case, that you need to include LOOT to it's exception list.

**Comment by DragonHearted99** [comment]
Bit Defender Total Security 2018, I added both LOOT and MO2 to the exceptions list previously but still have the latest log which I posted.  I have even turned Bit Defender off with the same results.  I do not have a git folder under user/morphy/appdata/local/Loot folder but do have a SkyrimSpecialEdition folder.  Please let me know if there is more information I should gather.

![bit defender exclusions](https://user-images.githubusercontent.com/42924343/44988816-8ed87e80-afbe-11e8-8326-ae1f921954e9.jpg)
![bit defender sheild off](https://user-images.githubusercontent.com/42924343/44988835-9730b980-afbe-11e8-9154-a70cf0a1836e.jpg)

**Comment by pStyl3** [comment]
If you open the following url within your internet browser (which do you use?), what happens?
https://github.com/loot/

Can you access that site normally or does it get blocked within your browser aswell?

**Comment by MacSplody** [comment]
> [12:23:12.681495] [error]: Exception while executing query: Git operation failed. Details: -1; failed to send request: A connection with the server could not be established
: libgit2 error

@DragonHearted99 you might have a firewall blocking LOOT's access to the internet.

**Comment by DragonHearted99** [comment]
ok was able to open https://github.com/loot/  with no problem (Chrome)
![github check](https://user-images.githubusercontent.com/42924343/45002843-f4a02700-b00d-11e8-9dc0-17ea0468ce9a.jpg)

Firewall in BitDefender was the winning ticket in this case for some reason the rule was turned off
![firewall rule was disabled](https://user-images.githubusercontent.com/42924343/45002861-27e2b600-b00e-11e8-8989-2dfd92099573.jpg)

Loot now running as per the image below
![loot working yay](https://user-images.githubusercontent.com/42924343/45002868-34ffa500-b00e-11e8-926d-756967a22a95.jpg)

Many thanks for your suggestions and help
