### ISSUE TITLE
WACCF + ICH Sorting Rule

### ISSUE THREAD

**Issue by Velgus** [loot/skyrimse#323]
The masterlist entry for sorting WACCF after ICH is not objectively correct. There are issues with sorting it either way, and the only way to resolve compatibility is via a patch (none have been released for SSE yet, one existed for Classic's WAFR).

The sorting rule creates an issue for users like myself who simply integrate WACCF's changes into ICH (the easier way to do it, since ICH is a smaller mod), as there is no way to get LOOT to ignore the masterlist entry, causing a cyclic error when setting ICH to load after WACCF with user data. This is also how the patch for Classic's WAFR with ICH worked - it was a replacement plugin for ICH, meant to be loaded afterwards.

At the very least, perhaps add a condition that checks for the non-modified checksum to apply the Load After. If the imp_helm_legend.esp file has been modified, do not apply the rule.

**Comment by MacSplody** [comment]
@Velgus Updated https://github.com/loot/skyrimse/commit/43af7a753a2d8d086ce66cb165e4330336501249
