### ISSUE TITLE
WACCF-ICH Patch Available - Suggest to add warning based on file checksum

### ISSUE THREAD

**Issue by Velgus** [loot/skyrimse#327]
The official patch for Improved Closefaced Helmets with WACCF is available here: https://www.nexusmods.com/skyrimspecialedition/mods/19518

It's a replacement plugin. 

What I'd recommend is to get the file checksum for the default "imp_helm_legend.esp"(https://www.nexusmods.com/skyrimspecialedition/mods/824), and if it has that checksum with WACCF also in the load order, add a warning message to get the WACCF-patched plugin from the aforementioned page.

**Comment by MacSplody** [comment]
As the original file will still work & the .bsa is required by the patch, I think it would be better for the patch notes to be read in this case. I've updated several mods to include a link to their compatibility notes.

@Velgus Thanks for the feedback.
