### ISSUE TITLE
Incorrect text in warning for "KS Dragon Overhaul 2.esp"

### ISSUE THREAD

**Issue by Velgus** [loot/skyrimse#328]
I'm receiving the following warning for "KS Dragon Overhaul 2.esp":

"You seem to be using Thunderchild - Epic Shouts and Immersion, but you haven't enabled the patch for this plugin: KS Dragon Overhaul - AAE Ultimate Edition Patch"

This should say:

"You seem to be using Thunderchild - Epic Shouts and Immersion, but you haven't enabled the patch for this plugin:  KS Dragon Overhaul 2 - Thunderchild Patch"

The link is fine - both patches are on the same page.

**Comment by MacSplody** [comment]
@Velgus Thanks for the feedback. Fixed in the above commit.
