### ISSUE TITLE
JKs Skyrim_No Snow Under the Roof_Patch.esp

### ISSUE THREAD

**Issue by Teabag86** [loot/skyrimse#336]
Requested LOAD order
NSUTR_groundsnow_mesh_fixes.esp

JKs Skyrim_No Snow Under the Roof_Patch.esp OR
JKs Skyrim_Dawnstar_NSUTR_Patch.esp OR
JKs Skyrim_Dawnstar_BOYD_NSUTR_Patch.esp

The JKS patches need to load after the NSUTR mesh fixes.
There are only 3 records in conflict.
I should also note that only 1 of the last 3 files should be used, but I think you already have this covered. 

NSUTR mesh fixes https://www.nexusmods.com/skyrimspecialedition/mods/15064
JKS Patches https://www.nexusmods.com/skyrimspecialedition/mods/17026

Thanks

**Comment by MacSplody** [comment]
@Teabag86 All done.
