### ISSUE TITLE
Change license to Creative Commons Zero

### ISSUE THREAD

**Issue by Freso** [loot/skyrimse#34]
I would like to relicense the LOOT masterlists/repositories to be under the [Creative Commons Zero license](https://creativecommons.org/publicdomain/zero/1.0/) (effectively submit them to the public domain). See https://github.com/loot/loot.github.io/issues/61 for more thoughts on this.

@MaddBomber83, @Sharlikran, @WrinklyNinja, @flatwhatson, @ExE-Boss, @Kinaga, @Arthmoor if you agree with moving to this much more free license, please write a comment confirming this.

- [x] @MaddBomber83
- [x] @Sharlikran
- [x] @WrinklyNinja
- [x] @flatwhatson
- [x] @ExE-Boss
- [x] @Kinaga
- [x] @Arthmoor

**Comment by Ortham** [comment]
I'm okay with this.

**Comment by ExE-Boss** [comment]
I’m also OK with this.

**Comment by flatwhatson** [comment]
👍

**Comment by Sharlikran** [comment]
Fine with me

**Comment by Arthmoor** [comment]
I have no problem with this.

**Comment by Spu00Key** [comment]
I'll just have to echo @WrinklyNinja and question changing something on semantics.  Does this change let us do something we can't do now, that we want to do now?

It's cool if it allows us to do more in the future, just question why now when we have nothing to balance against it.

Not important enough to me to be a thorn though.  I'm ok with the change and appreciate the opportunity to provide input.

**Comment by Freso** [comment]
@MaddBomber83 I'll reply to you on the loot/loot issue.

**Comment by ExE-Boss** [comment]
It might be easier to contact @Kinaga on Nexus at [Carriage and Ferry Travel Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/8379) by [Kinaga](https://www.nexusmods.com/skyrimspecialedition/users/22750984), which was added to the masterlist in PR #26.

**Comment by Kinaga** [comment]
I'm ok with this. Thank you for pming me on Nexus. Sorry if I held you up.

**Comment by Freso** [comment]
Thanks @Kinaga, and I assume @ExE-Boss for reaching out to them. :) (It was on me to-do list, but my to-do list is very long. >_<)

I have made a pull request now which I will merge in ~2 days if no objections are made by then: https://github.com/loot/skyrimse/pull/38
