### ISSUE TITLE
SkyUI Late Load Incorrect

### ISSUE THREAD

**Issue by Velgus** [loot/skyrimse#346]
SkyUI shouldn't be a late load. All resources used in SkyUI (both in the plugin and BSA) are custom/new, not overwriting anything in vanilla/other mods. 

In the off-chance there are other mods that overwrite these resources, they will almost definitely be doing so intentionally, and therefore 'should' be loading afterwards.

I get that it's to fix an existing issue with a specific mod, but it seems like a poor way to handle it. This issue should be fixed on that mod's end, not via a global sorting rule. Said mod was originally 'supposed' to be overwriting those scripts, but just unfortunately hasn't been updated.

**Comment by CptMcSplody** [comment]
> In the off-chance there are other mods that overwrite these resources, they will almost definitely be doing so intentionally, and therefore 'should' be loading afterwards.

If you can find a mod which currently needs to overwrite SkyUI scripts then bring it to my attention.
Speculation is no use.

**Comment by MacSplody** [comment]
Below quote is taken from [MCM Quickstart](https://github.com/schlangster/skyui/wiki/MCM-Quickstart)
> Should I include the resources from the SkyUI SDK with my mod?
> No, you should not include any SKI_* scripts with your mod. Also remember this for SKI_PlayerLoadGameAlias.pex/psc, which the Creation Kit will automatically add when creating a mod archive (BSA). Remove them from the file list before proceeding.
> 
> Including SKI_* scripts might lead to conflicts with future MCM updates.
> 
> If you accidently added SKI_PlayerLoadGameAlias, it's not the end of the world though, as this script is very simple and unlikely to change (ever). Still, you should avoid packaging it in later versions.

**Comment by Velgus** [comment]
That is for the SkyUI SDK, that's not all that's in the BSA, it also contains interface files, which some mods do indeed update. Any mod that updates the cursormenu.swf or map.swf (eg. Paper World Maps) would have issues if they were BSA-ified.

Another example is Frostfall once the official update comes out (or anyone who manually does the fixes themselves, and re-archives them in a BSA). The current 'unofficial' fixes patch for Frostfall uses loose files, but Frostfall itself uses a BSA and overwrites SkyUI's translation files. Once those have been officially been updated, Frostfall's translation changes will not be used.

Even without specific examples, surely you can see how ugly of a design decision it is to support a single broken mod at the expense of any other mods that make similar decisions as said broken mod once made. It shouldn't be LOOT's job to accommodate a broken feature of a mod.

**Comment by MacSplody** [comment]
@Velgus Updated https://github.com/loot/skyrimse/commit/8cd11ecd917935fb8e2c8c443664e9adf44a7366
