### ISSUE TITLE
No Masterlist after letting LOOT through firewall and re-installing

### ISSUE THREAD

**Issue by ChilliBoi** [loot/skyrimse#36]
I have let the application update masterlist in the settings
[LOOTAPIDebugLog.txt](https://github.com/loot/skyrimse/files/1139098/LOOTAPIDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/1139096/LOOTDebugLog.txt)
[CEFDebugLog.txt](https://github.com/loot/skyrimse/files/1139097/CEFDebugLog.txt)

**Comment by Freso** [comment]
Please post these in https://github.com/loot/loot/issues/801 instead. No need to create a new (duplicate) issue, esp. under the wrong project.
