### ISSUE TITLE
Loot detects Old original skyrim and the new Special edition skyrim but i only have the special edition skyrim installed 

### ISSUE THREAD

**Issue by jamesa82** [loot/skyrimse#37]
Title says it all really. I have no idea why but loot detects the old skyrim even though i don't have it installed, I only have the special edition installed. When i click the original old skyrim it has all the mods i have for special edition listed as well as the skyrim and dlc esms but without any tags of anything because i don't have the master list ( or even the game installed).

Loot seems to work fine for my SE Skyrim but i don't really get why it's doing this. 
Since i plan on installing oldrim in order to play enderal i really don't want to put my modded special edition in jeopardy by loot getting the two mixed up and since loot is pretty invaluable to get things working properly i'd really appreciate some insight on this oddity.
Thanks for any help you can give

**Comment by Ortham** [comment]
Where is LOOT installed, is it next to your Skyrim SE install? Also check if there's a Registry entry at `HKLM\Software\Bethesda Softworks\Skyrim\Installed Path`.

**Comment by jamesa82** [comment]
I have loot installed into my Skyrim special edition folder inside my steamapps/common folder.
There's no registry entry for skyrim (orginal) in my HKLM\Software\Bethesda Softworks. There's bethesda.net, fallout 3, morrowind, oblivion, oblivion - construction set and skyrim Special edition but no skyrim (original) one.

**Comment by jamesa82** [comment]
MANAGED TO FIX IT!!
I uninstalled it from my SSE folder and into the default location.
just wondering if uninstalling and reinstalling loot mid play through will cause any issues with my games or mods??

**Comment by Ortham** [comment]
Yeah, it'll be because it looks for a `Skyrim.esm` for both Skyrim and Skyrim SE local installs. It would be good if there was some secondary measure to differentiate them...

> just wondering if uninstalling and reinstalling loot mid play through will cause any issues with my games or mods??

No, it won't.

**Comment by jamesa82** [comment]
Thanks for the help, really appreciate it.
resolved #37
