### ISSUE TITLE
Patch Required - Vivid Weathers and Wet & Cold

### ISSUE THREAD

**Issue by Graybark** [loot/skyrimse#381]
The VW author recommends to load VW after W&C in the description. It's loading the opposite by default. A custom rule may be needed.

**Comment by MacSplody** [comment]
Hi @ArtaiosGreybark 

Already checked it in https://github.com/loot/skyrimse/issues/195#issue-334708428
Needs a patch, if there is one available it can be linked.

**Comment by Graybark** [comment]
You're always 10 steps ahead of me.

**Comment by MacSplody** [comment]
Moved to issue [Testing Mods - Notes](https://github.com/loot/skyrimse/issues/309)
