### ISSUE TITLE
Palaces and Castles Enhanced SSE LOOT

### ISSUE THREAD

**Issue by Spu00Key** [loot/skyrimse#39]
[Palaces and Castles Enhanced SSE](https://www.nexusmods.com/skyrimspecialedition/mods/1819/)

From the Author (SetteLisette):
> Hi! No worries for the delay as I completely understand that you have priorities. as we all do!
> 
> Thank you so much for your continuous support. Yes, as you pointed out, the lighting mods that I list bellow should be loaded before my mod.
>  
> Realistic Lighting Overhaul (http://www.nexusmods...yrim/mods/30450)
> Enhanced Lights and FX (http://www.nexusmods...yrim/mods/27043)
> Relighting Skyrim (http://www.nexusmods...yrim/mods/17609)
> Shadows (http://www.nexusmods...yrim/mods/50855)
> Enhanced Lighting for ENB (ELE) - LITE (http://www.nexusmods...yrim/mods/59733)
> Volrath Enhanced Lights and Fixes - VELF (http://www.nexusmods...yrim/mods/19933)
> In addition to that, any mods that add objects to the changed interiors should be loaded before my mod. If it's just a sweetroll then not a big deal, but if bigger objects like paintings and tables are added by other mods, I'd say they cause conflicts. So the following mods should also be loaded before my mod.
> Faction Crossbows (http://www.nexusmods...yrim/mods/58704)
> Legendary Skyrim Crossbows (http://www.nexusmods...yrim/mods/82171)
> Snazzy Furniture and Clutter Overhaul (http://www.nexusmods...yrim/mods/76307)
> Any editions of Morrowloot
> Requiem (http://www.nexusmods...yrim/mods/19281)
> Skyrim Unique Treasures (http://www.nexusmods...yrim/mods/12766)
> BadGremlins Something Fishy (http://www.nexusmods...yrim/mods/63537)
> Legacy of the Dragonborn (http://www.nexusmods...yrim/mods/52248)
> T3nd0's Perkus Maximus "The Mage Module" (http://www.nexusmods...yrim/mods/59849)
> Populated Skyrim HELL EDITION (http://www.nexusmods...yrim/mods/73315)
> Populated Skyrim Prisons Cells Reborn (http://www.nexusmods...yrim/mods/73194)
> Populated Prisons (http://www.nexusmods...yrim/mods/33141)
> Solitude Dome Paintings (http://www.nexusmods...yrim/mods/64549)
> Cutting Room Floor (http://www.nexusmods...yrim/mods/47327)
> Interesting NPCs (http://www.nexusmods...kyrim/mods/8429)
> Inconsequential NPCs (http://www.nexusmods...rim/mods/36334/)
> Ovens and Churns of Skyrim (http://www.nexusmods...yrim/mods/41809)
> Skyrim Ovens for Hearthfire (http://www.nexusmods...yrim/mods/26814)
> The following mods contain Navmesh edits so NEED to be loaded before my mod, or the NPCS in palaces and keeps will have hard time getting to destinations and in worst cases CTDs might occur.
> Riften - Thief Edition (http://www.nexusmods...yrim/mods/31669)
> Solitude - Capital Edition (http://www.nexusmods...yrim/mods/52117)
> Skyrim Sewers 4 (http://www.nexusmods...yrim/mods/14351)
> Solitude Reborn (http://www.nexusmods...yrim/mods/63685)
> Thane rooms in each Jarlhouse (http://www.nexusmods...yrim/mods/80136)
> The Vaults Of Skyrim (http://www.nexusmods...yrim/mods/53977)
> Skyrim Underground (http://www.nexusmods...yrim/mods/75004)
> Holds The City Overhaul (http://www.nexusmods...yrim/mods/74638)
> Historical Revival - The Roman Era (http://www.nexusmods...yrim/mods/32988)
>  
>  
> ...This is all I could come up with. =D

**Comment by Ariphaos** [comment]
Both WARZONES mods also have conflicts that PCE needs to override.

**Comment by MacSplody** [comment]
Given the nature of the mod and the large amount of changes it makes, any incompatibility will have to be patched by the mod author. Simple giving it priority over other mods will not fully resolve conflicts.

better quest objectives & vigilant also have conflicts.
Edit: also SkyrimImprovedPuddles-DG-HF-DB.esp

Currently looking at this one, Compatibility patches are available for:

Optional patches
- Unofficial SSE Patch
- Unofficial SSE Patch & Cutting Room Floor (highly recommended)
- Alternate start (Issues with storm-cloak or imperial soldier start)
- Holidays
- Enhanced Lights & FX Enhancer (highly recommended)
- Relationship Dialogue Overhaul (Required if RDO loads after Palaces and Castles Enhanced)
- Art of Magika

Necessary Patches (Must be installed)
- Interesting NPCs
- Immersive citizens
- Enhanced Lights & FX
- Open Cities
- Realistic Lighting Overhaul (Interiors Module)
- Relighting Skyrim
- Skyrim sewers 4
- Skyrim Project Optimization (ESM & ESP Versions)

**Comment by Graybark** [comment]
That mod is a compatibility nightmare.

**Comment by MacSplody** [comment]
Main module appears to be corrupt 

```
[00:12] 
<Error reading float in " \ 
[04] Palaces Castles Enhanced.esp \
[30] GRUP Top "CELL" \
[6] GRUP Interior Cell Block 6 \
[2] GRUP Interior Cell Sub-Block 7 \ 
[3] GRUP Cell Children of SolitudeBluePalace "Blue Palace" [CELL:00016A04] \ 
[0] GRUP Cell Persistent Children of SolitudeBluePalace "Blue Palace" [CELL:00016A04] \ 
[86] [REFR:000EB5AE] (places RoomMarker [STAT:0000001F] in GRUP Cell Persistent Children of SolitudeBluePalace "Blue Palace" [CELL:00016A04]) \ 
[3] XMBO - Bound Half Extents \ 
[2] Z">

<Error reading float in " \ 
[04] Palaces Castles Enhanced.esp \
[30] GRUP Top "CELL" \ 
[6] GRUP Interior Cell Block 6 \
[2] GRUP Interior Cell Sub-Block 7 \ 
[3] GRUP Cell Children of SolitudeBluePalace "Blue Palace" [CELL:00016A04] \
[0] GRUP Cell Persistent Children of SolitudeBluePalace "Blue Palace" [CELL:00016A04] \ 
[86] [REFR:000EB5AE] (places RoomMarker [STAT:0000001F] in GRUP Cell Persistent Children of SolitudeBluePalace "Blue Palace" [CELL:00016A04]) \
[4] XPRM - Primitive \
[0] Bounds \ 
[2] Z">
```

**Comment by MacSplody** [comment]
Closing for now, will revisit if fixed. I have  left a report on nexus for the author.
