### ISSUE TITLE
SkyTEST, skyBirds and Birds of Skyrim load order

### ISSUE THREAD

**Issue by deepfriedmind** [loot/skyrimse#40]
The load order should be:
1. [SkyTEST](http://www.nexusmods.com/skyrimspecialedition/mods/1104)
2. [skyBirds](http://www.nexusmods.com/skyrimspecialedition/mods/2315)
3. [Birds of Skyrim](http://www.nexusmods.com/skyrimspecialedition/mods/3097)

LOOT currently has it backwards, i.e.:

1. [Birds of Skyrim](http://www.nexusmods.com/skyrimspecialedition/mods/3097)
2. [skyBirds](http://www.nexusmods.com/skyrimspecialedition/mods/2315)
3. [SkyTEST](http://www.nexusmods.com/skyrimspecialedition/mods/1104)

Thanks for a great tool!

**Comment by Freso** [comment]
Do you have any source for this? skyBirds mentions a compatibility patch between it and SkyTEST (which would mean that as long as that patch is loaded after those two, it doesn't matter which of the two others go first).

Bird of Skyrim doesn't seem to mention anything about incompatibilities or relative load order to other mods.

**Comment by Spu00Key** [comment]
> **Birds of Skyrim**
> Compatible with skyBirds SSE Edition by steve40, which is also highly recommended. Load Birds of Skyrim AFTER skyBirds.
> Compatible with Birds and Flocks SSE Edition, which is also highly recommended.
> Compatible with USSEP. No patch needed.
> Compatible with SkyTEST. Load Birds of Skyrim AFTER SkyTEST.

> **Sky Birds**
> Patches for USSEP, skyTEST and Better Harvesting. ONLY USE THIS PATCH WITH v0.94. THE NEW v1.01 **DOES NOT NEED ANY PATCH FOR USSEP OR SKYTEST COMPATIBILITY**, AND THE OLD PATCH MIGHT CAUSE CTD. LOAD SKYBIRDS v1.01 BEFORE BETTER HARVESTING.

1. SkyTEST-RealisticAnimals&Predators.esp
2. skyBirds_SSE.esp
3. BirdsOfSkyrim_SSE.esp

The primary compatability check deals with the Chicken on hit script / shader.

**EDIT:**

> **Current Sorting**
>   - name: 'BirdsOfSkyrim_SSE.esp'
>     after:
>       - 'Skytest.esp'
>   - name: 'BirdsAndFlocks_SSE.esp'
>     after:
>       - 'BirdsOfSkyrim_SSE.esp'
>       - 'skyBirds_SSE.esp'

The ESP names for the SkyTest series have been changed.
The load order for the Sky Birds, Birds and Flocks, Birds of Skyrim series has also changed.

**Comment by Spu00Key** [comment]
I'll wait a few days for comment before merging and closing.

**Comment by Freso** [comment]
Just curious, where did you get the above quotes from?

**Comment by Spu00Key** [comment]
[Birds of Skyrim SSE Edition](http://www.nexusmods.com/skyrimspecialedition/mods/3097/?)
[skyBirds SSE Edition](http://www.nexusmods.com/skyrimspecialedition/mods/2315/?)

The conflict information is pulled from SSE Edit.
