### ISSUE TITLE
Cleaning Info updates using xEdit Quick Auto Clean

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#409]
https://github.com/loot/skyrimse/commits/cleaning-info-updates

- [x] USSEP
- [x] CRF
- [x] Thunderchild
- [x] LOTD
---

**Comment by Infernio** [comment]
Mods updated on this branch: https://github.com/Infernio/skyrimse/tree/crc-updates
- [x] Alternate Start
- [x] Enhanced Blood Textures (+ Wound Size Plugin)
- [x] SkyUI
- [x] RaceMenu
- [x] Particle Patch for ENB
- [x] Obsidian Weathers (+ TS Patch & Vigilant Plugin)
- [x] Andromeda
- [x] Keld-Nar

**Comment by Infernio** [comment]
See #410

**Comment by MacSplody** [comment]
#411
