### ISSUE TITLE
Used LOOT to sort mods, now merchants in game are bugged

### ISSUE THREAD

**Issue by Dracosnayke** [loot/skyrimse#43]
I heard of LOOT from one of the mods that I'd downloaded for Skyrim SE, so since I'd been having a hassle sorting and organizing my game's mods on my own, I decided to give it a try since it seemed like it could figure out what was best. So I downloaded LOOT, ran it for Skyrim SE, and let it sort my mods out for me.

It worked very well, I couldn't find any real issues with my game after using it, except one major one. Whenever I go to talk to a merchant, I will ask what they're selling so that they'll open the trading window. Only when I press that dialogue option, they'll say their phrase "A bit of this and a bit of that" or what have you, but then the dialogue window will reset without actually opening the trade window. I can back out and move on with my life easily enough, but the inability to trade with merchants when I'm so early on in my game is a major issue.

This is my first time writing in about something like this, I'm not fully sure what the process would be, whether I need to put up my whole list of mods, load order, or whatever. All I know is that I haven't downloaded many mods recently that should affect NPC behavior. It was only after using LOOT to sort did I have this issue. So I'm hoping that I'll be able to find a solution for it.

**Comment by Ortham** [comment]
I haven't done any load order debugging in a long time, but if you post your load order, maybe I can help.

**Comment by Dracosnayke** [comment]
0  0 Skyrim.esm
  1  1 Update.esm
  2  2 Dawnguard.esm
  3  3 HearthFires.esm
  4  4 Dragonborn.esm
  5  5 Unofficial Skyrim Special Edition Patch.esp
  6  6 ApachiiHair.esm
  7  7 climatesoftamriel.esm
  8  8 campfire.esm
  9  9 RSkyrimChildren.esm
 10  a Cutting Room Floor.esp
 11  b SMIM-SE-Merged-All.esp
 12  c Bring Out Your Dead.esp
 13  d planetary alignment.esp
 14  e dd-no spinning death animation merged.esp
 15  f dD - Realistic Ragdoll Force - Realistic.esp
 16 10 Hothtrooper44_Armor_Ecksstra.esp
 17 11 Modern Brawl Bug Fix.esp
 18 12 Unique Uniques.esp
 19 13 weightless dragon bones and scales.esp
 20 14 Lethal Traps - Smilodon Patch.esp
 21 15 Visible Favorited Gear.esp
 22 16 FasterSkillLeveling2017.esp
 23 17 PerkPointPotion.esp
 24 18 Ish's Respec Mod.esp
 25 19 Perk Points and More Gold for Bounty Quests.esp
 26 1a NoBSAIProjectileDodge.esp
 27 1b ShieldWard.esp
 28 1c UnreadBooksGlow.esp
 29 1d BarenziahQuestMarkers.esp
 30 1e Footprints.esp
 31 1f RSChildren - Complete.esp
 32 20 RSChildren_PatchUSSEP.esp
 33 21 ogSplendorDragons.esp
 34 22 DiverseDragonsCollectionSE.esp
 35 23 DiverseWerewolvesCollection.esp
 36 24 TheCleaner.esp
 37 25 Whistle.esp
 38 26 Horse Storage.esp
 39 27 AmazingFollowerTweaks.esp
 40 28 Realistic-Voice.esp
 41 29 transmutetweak.esp
 42 2a instantmining.esp
 43 2b PerkPointsPerLevel.esp
 44 2c Summermyst - Enchantments of Skyrim.esp
 45 2d Aurora - Standing Stones of Skyrim.esp
 46 2e EnhancedLightsandFX.esp
 47 2f Elemental Destruction.esp
 48 30 weightless potions.esp
 49 31 IcePenguinWorldMap.esp
 50 32 ELFX - Exteriors.esp
 51 33 lamposts of skyrim.esp
 52 34 Ordinator - Perks of Skyrim.esp
 53 35 Thunderchild - Epic Shout Package.esp
 54 36 practice dummies.esp
 55 37 skyBirds_SSE.esp
 56 38 SkyTEST-RealisticAnimals&Predators.esp
 57 39 Hothtrooper44_ArmorCompilation.esp
 58 3a Betterfoodeffects.esp
 59 3b Point The Way.esp
 60 3c Run For Your Lives.esp
 61 3d Cloaks.esp
 62 3e Inigo.esp
 63 3f Blowing in the Wind SSE.esp
 64 40 Immersive Patrols II.esp
 65 41 Hunterborn.esp
 66 42 Skyshards.esp
 67 43 Frostfall.esp
 68 44 MoreWerewolves.esp
 69 45 Hotsprings of Skyrim.esp
 70 46 deadly daedra of skyrim.esp
 71 47 wetandcold.esp
 72 48 iNeed.esp
 73 49 the paarthurnax dilemma.esp
 74 4a gildergreen regrown.esp
 75 4b MBW Dragon Souls to Perk Points.esp
 76 4c Apocalypse - Magic of Skyrim.esp
 77 4d WeaponsOf3E_SSE.esp
 78 4e Hunterborn - Campfire Patch.esp
 79 4f Chesko_WearableLantern.esp
 80 50 TTR_Master_Trader_1x.esp
 81 51 Hunterborn - Leather Tanning.esp
 82 52 Hunterborn - Soups and Stews.esp
 83 53 Hunterborn - iNeed Patch.esp
 84 54 ScrimshawExpanded.esp
 85 55 LightngDuringStorm.esp
 86 56 Simply Stronger Dragons.esp
 87 57 Cloaks - Dawnguard.esp
 88 58 Cloaks - USSEP Patch.esp
 89 59 Combat Evolved.esp
 90 5a Dual Blocking for Idiots v1.35a.esp
 91 5b Animal Tweaks.esp
 92 5c VisualAnimatedEnchants.esp
 93 5d Wildcat - Combat of Skyrim.esp
 94 5e dD - Enhanced Blood Main.esp
 95 5f dD-Medium Script Range.esp
 96 60 Mortal Enemies.esp
 97 61 Realistic Melee Range.esp
 98 62 heart breaker se.esp
 99 63 360WalkandRunPlus-RunBackwardSpeedAdjust.esp
100 64 Slow and Freeze Time Spells -TwinCrows.esp
101 65 violens se.esp
102 66 AcquisitiveSoulGemMultithreaded.esp
103 67 HideUI.esp
104 68 Joy of Perspective.esp
105 69 SkyHUD.esp
106 6a Real Bows SE.esp
107 6b Imperious - Races of Skyrim.esp
108 6c Open Cities Skyrim.esp
109 6d immersive citizens - ai overhaul.esp
110 6e ELFX - Hardcore.esp
111 6f RealisticWaterTwo.esp
112 70 Alternate Start - Live Another Life.esp
113 71 Relationship Dialogue Overhaul.esp
114 72 Blowing in the Wind - Open Cities Skyrim Patch SSE.esp
115 73 RealisticWaterTwo - iNeed.esp
116 74 RealisticWaterTwo - Watercolor.esp

Here you go. Just used the "Copy Load Order" function from the LOOT window. But this is the order that my mods were put in after using it.

**Comment by Ortham** [comment]
Hmm, nothing in there jumps out at me. All I can suggest is to try the binary method: deactivate half your plugins, load the game and see if it still occurs. If not, reactivate them and deactivate the other half, so you can tell which half is causing the problem, then repeat on the half that had the problem, until you're left with only a few plugins that could be causing the issue.

Obviously, don't save your game while doing this debugging, just save in a shop before starting and reload that save each time.

**Comment by MacSplody** [comment]
Could be Relationship Dialogue Overhaul as that requires a patch for USSEP & Cutting room floor. And I don't see that patch listed.

What mod is TTR_Master_Trader_1x? If that affects merchants it could also conflict with RDO.

mod link https://www.nexusmods.com/skyrimspecialedition/mods/1826
Master Trader SE - Merchants Never Run Out Of Gold

Edit: checked and Master trader conflicts with RDO
![image](https://user-images.githubusercontent.com/1944639/39144650-4c120236-4729-11e8-801c-ddf5dc3de767.png)

Two solutions:
- load master trader after RDO, won't break anything, but users will lose some dialogue features.
- A compatibility patch, have contacted Master trader mod author about making a patch for them.

**Comment by MacSplody** [comment]
Issue should be resolved with the above change to load `TTR_Master_Trader` after `Relationship Dialogue Overhaul.esp`

`Relationship Dialogue Overhaul.esp` was removing required changes made by 'TTR_Master_Trader.esp'
