### ISSUE TITLE
Reduce the number of groups

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#458]
### Intention
Look at the possibility of reducing the number of groups:
- [x] Merging mod specific Groups to a neighbouring generic group.
#### Current mod specific Groups:
- [x] iCitizens - Immersive Citizens
- [x] Alternate Start
- [x] Open Cities
- [x] Enhanced Lighting
- [x] Realistic Water.

![image](https://user-images.githubusercontent.com/1944639/48658428-6c8cc380-ea39-11e8-9e32-e7ca6c5c26f4.png)

**Comment by MacSplody** [comment]
##### iCitizens Group
---

[Immersive Citizens - AI Overhaul SE](https://www.nexusmods.com/skyrimspecialedition/mods/173) `Immersive Citizens - AI Overhaul.esp`
###### after:
`3DNPC.esp`
`Bells of Skyrim.esp`
`Bridges of Skyrim.esp`
`Civil War Repairs.esp`
`EnhancedLightsandFX.esp`
`Eli_Breezehome.esp`
`Eli_Routa.esp`
`Eli_Routa - Non-Stormcloak.esp`
`Landscape Fixes For Grass Mods.esp`
`Requiem.esp`
`SkyfallEstate.esp`
`Skyrim Project Optimization - Full Version`
`Skyrim Sewers.esp`
`TouringCarriages.esp`
`Verdant - A Skyrim Grass Plugin SSE Version.esp`
`ASLAO - Front Porch (Breezehome).esp`
`BHTNFBP.esp`
`breezehome enhanced SSE.esp`
`Simpler Breezehome.esp`
`Wind District Breezehome - Replacer.esp`
`breezehome_basement.esp`
`BreezehomeSB.esp`
`breeze2.esp`
###### before:
[`Convenient Horses.esp`](https://www.nexusmods.com/skyrimspecialedition/mods/9519)
[`ELE_SSE.esp`](https://www.nexusmods.com/skyrimspecialedition/mods/1377)
[`TheChoiceIsYours.esp`](https://www.nexusmods.com/skyrimspecialedition/mods/3850)


---
[Relationship Dialogue Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/1187) `Relationship Dialogue Overhaul.esp`
###### after:
`AmazingFollowerTweaks.esp`
`FCO - Follower Commentary Overhaul.esp`
`Immersive Citizens - AI Overhaul.esp`
###### before:
[`Convenient Horses.esp`](https://www.nexusmods.com/skyrimspecialedition/mods/9519)
[`EFFDialogue.esp`](https://www.nexusmods.com/skyrimspecialedition/mods/8379)
[`ELE_SSE.esp`](https://www.nexusmods.com/skyrimspecialedition/mods/1377)
[`FlowerGirls SE.esp`](https://www.nexusmods.com/skyrimspecialedition/mods/5941/)
[`Hunters Not Bandits.esp`](https://www.nexusmods.com/skyrimspecialedition/mods/1547)
[`TheChoiceIsYours.esp`](https://www.nexusmods.com/skyrimspecialedition/mods/3850)
[`TTR_Master_Trader.*\.esp`](https://www.nexusmods.com/skyrimspecialedition/mods/1826)
[`Serana Dialogue Edit.esp`](https://www.nexusmods.com/skyrimspecialedition/mods/16222)

---
[Extensible Follower Framework](https://www.nexusmods.com/skyrimspecialedition/mods/8379) `EFFDialogue.esp`
###### after:
`Relationship Dialogue Overhaul.esp`


---

**Comment by MacSplody** [comment]
Closest generic group

#### low Priority Group
[`Wildcat - Combat of Skyrim.esp`](https://www.nexusmods.com/skyrimspecialedition/mods/1368)
###### after
`Animal Tweaks.esp`
`Immersive NPC in the dark.esp`
`Imperious - Races of Skyrim.esp` (Only for group conflicts)
`New Weapon Parry.esp`
`SkyRe_Main.esp`
`SkyRe_Combat.esp`
`SkyRe_EnemyAI.esp`
`SkyTEST-RealisticAnimals&Predators.esp`

---
[`Imperious - Races of Skyrim.esp`](https://www.nexusmods.com/skyrimspecialedition/mods/1315)
###### after
`Joy of Perspective.esp`
Anything that alters races.

**Comment by CptMcSplody** [comment]
Testing on this branch https://github.com/loot/skyrimse/tree/group-testing

**Comment by MacSplody** [comment]
Okay after a lot of experimentation, I've settled on this approach to groups.
#479 
#480 
### Group Hierarchy
Every group set to load after `default` should have:
#### A clear order of priority for each module within it.
So if we have 3 mods `A.esp`, `B.esp` & `C.esp` in one group.
Whichever should sort last in that group needs to have `after` rules for all previous module in that group.
If `B.esp` needs to be last it requires an after rule for `A.esp` & `C.esp`.
Only having `A.esp` after `C.esp` & `B.esp` after `A.esp` will lead to cyclic errors between `B.esp` and `C.esp`.
By having a clear order for each group.
It allows modules from a lower group to load after any mod in any higher group.
It removes the need to add patches & dependant modules to a masters group.
Patches\modules  will load directly after their highest master\after.
Which keeps things simpler by reducing the number of modules in each group(After `default`).
As the number of `after` rules is dependant on the size of the group.
So Larger groups will require more for each module.
This why it's simpler to only add the masters to a group & not patches.

**Comment by MacSplody** [comment]
Updated Group Structure
![image](https://user-images.githubusercontent.com/1944639/49115191-02261f80-f292-11e8-97ff-0e39671137ba.png)

Compared to old structure
![image](https://user-images.githubusercontent.com/1944639/49115346-7234a580-f292-11e8-85aa-3acc1ac59e0f.png)
