### ISSUE TITLE
Add entries for SKSE64 and SkyUI

### ISSUE THREAD

**Issue by pStyl3** [loot/skyrimse#48]
LOOT's [masterlist for Skyrim](https://raw.githubusercontent.com/loot/skyrim/v0.10/masterlist.yaml) contains some data for SKSE and SkyUI (at the very top of it).

Should we do the same for SSE's masterlist? [SKSE64](http://skse.silverlock.org/) is in alpha now, as is [SkyUI](https://www.nexusmods.com/skyrimspecialedition/mods/12604).

Or maybe wait until they reach a stable release?

CC: @schlangster @Mardoxx

**Comment by Mardoxx** [comment]
Absolutely no idea. Ask maintainers of loot

**Comment by Ortham** [comment]
I think it makes sense to add it when it's needed. At the moment, I don't think there is any need.

**Comment by Arthmoor** [comment]
Does it make sense now that 1.5.3 isn't in beta anymore?

**Comment by Ortham** [comment]
> Does it make sense now that 1.5.3 isn't in beta anymore?

That doesn't really change that SKSE64 and SkyUI are still alpha, though it does mean I should probably get on with ESL support for LOOT...

**Comment by Arthmoor** [comment]
I don't think it would hurt to put the support in for testing if nothing else.

**Comment by Ortham** [comment]
If it's needed for testing, then sure.

**Comment by Arthmoor** [comment]
This probably needs to be looked at again to provide for exe versions and SKSE64 loader versions in the same way the Fallout 4 list currently is since both are likely to change again in the future.

**Comment by MacSplody** [comment]
#65 Needs some verification, one issue with version check for SkyrimSE.exe, version listed in exe details is 1.0.0.0 not 1.5.23

**Comment by Arthmoor** [comment]
The version number needs to be set to 1.5.39 now anyway since SSE just updated this morning.

**Comment by MacSplody** [comment]
@Arthmoor  Unable to get the true version of the SKyrimSE.exe at the moment. Quoting @WrinklyNinja 

> Given that the executable version doesn't reflect the game version, I think it's pointless checking it. You could check the CRC instead, but I don't know if different regions get different executables (which would all have different CRCs)...

**Comment by Arthmoor** [comment]
Not sure what to tell you then cause only Bethesda can control what shows up in the exe data.

**Comment by pStyl3** [comment]
SKSE64 has left its alpha status and is now considered being in beta (v2.0.7).

**Comment by MacSplody** [comment]
I'll close this issue as SkyUI & SKSE entries have been added. 
A separate entry will be added for the below request.

> This probably needs to be looked at again to provide for exe versions and SKSE64 loader versions in the same way the Fallout 4 list currently is since both are likely to change again in the future.
