### ISSUE TITLE
Requiem - The Roleplaying Overhaul (Notes)

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#496]
`Requiem.esp`
- [x] Add plugin to Perks & Skills group.

Because it needs to be before Sacrosanct.
Order with Alternate Start can be either way,
placing them in the same group woud require an after to be set for the other.
A patch is required if it's before, none if Requiem is after ASLAL.
Having Requiem in the group before ASLAL will allow users to add an
after to Requiem for ASLAL without causing a sorting error.
If you put Requiem in the Low Priority Overrides group,
then you'll need to add an after for ASLAL to Sacrosanct to avoid a sorting error.

`Requiem Records Fix.esp`
> Make sure this file, the 'Requiem Records Fix.esp' is at the top in your load order, but below any DLCs. Load `USSEP` and anything else after it.
- [x] Add plugin to Pre Very Early group.

`Requiem for the Indifferent.esp`
- [x] Add plugin to Late fixes & Changes group.

---

- [x] Bash Tag Suggestions

`NPC.Class`

![image](https://user-images.githubusercontent.com/1944639/74286309-67432500-4d1f-11ea-890d-7a093d6a37a1.png)

`Keywords`

![image](https://user-images.githubusercontent.com/1944639/74290895-1fc29600-4d2b-11ea-9221-d6d4c316a271.png)

![image](https://user-images.githubusercontent.com/1944639/74290927-3832b080-4d2b-11ea-8422-fb5cd95ef470.png)

`Text`

![image](https://user-images.githubusercontent.com/1944639/74290967-5698ac00-4d2b-11ea-9491-f210fc541313.png)

![image](https://user-images.githubusercontent.com/1944639/74290989-67492200-4d2b-11ea-94cc-c4fa8c90422e.png)

`Actors.ACBS`

![image](https://user-images.githubusercontent.com/1944639/74291094-b2633500-4d2b-11ea-8a3c-0a45559ec596.png)

![image](https://user-images.githubusercontent.com/1944639/74291159-dc1c5c00-4d2b-11ea-8fdb-2010c0fc44eb.png)

`Actors.AIPackages`

![image](https://user-images.githubusercontent.com/1944639/74291234-1be34380-4d2c-11ea-82b9-fdd501dfb14e.png)

`Actors.Stats`

![image](https://user-images.githubusercontent.com/1944639/74291038-8f388580-4d2b-11ea-9e4e-391b46e7e928.png)

---

**Incompatible Plugins**
```yaml
- `Requiem plus PCEA 3-5.esp`
- `Ordinator - Perks of Skyrim.esp`
- `PerkusMaximus_Mage.esp`
- `PerkusMaximus_Master.esp`
- `PerkusMaximus_Thief.esp`
- `PerkusMaximus_Warrior.esp`
- `SkyRe_Main.esp`
- `Requiem - Hard Times.esp`
```

- [x] Add inc to Requiem.

**Load after Requiem**
```yaml
`Better Vampires.esp`
`Bounty Gold.esp`
`Clairvoyance.esp`
`dD - Realistic Ragdoll Force - (Realistic|Reduced|Medium|High)\.esp`
`EnchantingAwakened.esp`
`Immersive Ingestibles.esp`
`mslVampiricThirst.esp`
`Realistic AI Detection 2.*\.esp`
`Religion.esp`
`Requiem - Realistic Darkness.esp`
`Unlimited Training.esp`
`WerewolfPerksExpanded.esp`
`XPMSE.esp`
```

- [x] Add afters to other mods for Requiem.

**Require Patch**
```yaml
`1nivWICCloaks.esp`
`3DNPC.esp`
`(83Willows_101BUGS_V4_).+\.esp`
`Alternate Start - Live Another Life.esp`
`aMidianBorn_ContentAddon.esp`
`Animallica.esp`
`Audio Overhaul Skyrim.esp`
`Better Vampires.esp`
`Black Mage Armor.esp`
`Book Covers Skyrim.esp`
`Campfire.esm`
`Civil War Overhaul.esp`
`Cloaks.esp`
`CollegeOfWinterholdImmersive.esp`
`CompanionArissa.esm`
`Complete Crafting Overhaul_Remade.esp`
`Craftable Horse Barding.esp`
`Cutting Room Floor.esp`
`DawnguardArsenal.esp`
`DeadlyDragons.esp`
`Dragon Combat Overhaul.esp`
`EMCompViljaSkyrim.esp`
`EnchantingAwakened.esp`
`ESFCompanions.esp`
`ExplosiveBoltsVisualized.esp`
`Faction Crossbows.esp`
`Falskaar.esm`
`FireAndIceOverhaul.esp`
`Flora Fixes.esp`
`Frostfall.esp`
`Height Adjusted Races( .+)?\.esp`
`HothFollower.esp`
`hothtrooper44_ArmorCompilation.esp`
`Hunterborn.esp`
`Hypothermia.esp`
`Immersive Horses.esp`
`Immersive Jewelry.esp`
`Immersive Patrols II.esp`
`Immersive Sounds - Compendium.esp`
`ImmersiveSpells.esp`
`Immersive Weapons.esp`
`imp_helm_legend.esp`
`Inconsequential NPCs.esp`
`Inconsequential NPCs - Enhancement.esp`
`Inigo.esp`
`mslVampiricThirst.esp`
`One With Nature.*\.esp`
`Open Cities Skyrim.esp`
`PrvtI_HeavyArmory.esp`
`RealisticNeedsandDiseases.esp`
`Rebirth Monster.esp`
`Relationship Dialogue Overhaul.esp`
`RSkyrimChildren.esm`
`RSChildren - Complete.esp`
`RUSTIC SOULGEMS - (Uns|S)orted\.esp`
`ScopedBows.esp`
`Skyrim Immersive Creatures.esp`
`Skyrim Unlocked.esp`
`SkyTEST-RealisticAnimals&Predators.esp`
`TimingIsEverything.esp`
`TradeBarter.esp`
`Undeath.esp`
`Unique Uniques.esp`
`VioLens.esp`
`Weapons Armor Clothing & Clutter Fixes.esp`
`Wild World.esp`
`WM Flora Fixes.esp` Now Included in CACO SSE
`Wyrmstooth.esp`
```

**Comment by CptMcSplody** [comment]
**Incompatible Plugins**
```yaml
- `Requiem plus PCEA 3-5.esp`
- `Ordinator - Perks of Skyrim.esp`
- `PerkusMaximus_Mage.esp`
- `PerkusMaximus_Master.esp`
- `PerkusMaximus_Thief.esp`
- `PerkusMaximus_Warrior.esp`
- `SkyRe_Main.esp`
- `Requiem - Hard Times.esp`
```
**Load after Requiem**
```yaml
`Better Vampires.esp`
`Bounty Gold.esp`
`Clairvoyance.esp`
`dD - Realistic Ragdoll Force - (Realistic|Reduced|Medium|High)\.esp`
`EnchantingAwakened.esp`
`Immersive Ingestibles.esp`
`mslVampiricThirst.esp`
`Realistic AI Detection 2.*\.esp`
`RealisticRoomRental(-Basic)?.esp`
`Religion.esp`
`Requiem - Realistic Darkness.esp`
`Unlimited Training.esp`
`WerewolfPerksExpanded.esp`
`XPMSE.esp`
```
**Require Patch**
```yaml
`1nivWICCloaks.esp`
`3DNPC.esp`
`(83Willows_101BUGS_V4_).+\.esp`
`Alternate Start - Live Another Life.esp`
`aMidianBorn_ContentAddon.esp`
`Animallica.esp`
`Audio Overhaul Skyrim.esp`
`Better Vampires.esp`
`Black Mage Armor.esp`
`Book Covers Skyrim.esp`
`Campfire.esm`
`Civil War Overhaul.esp`
`Cloaks.esp`
`CollegeOfWinterholdImmersive.esp`
`CompanionArissa.esm`
`Complete Crafting Overhaul_Remade.esp`
`Craftable Horse Barding.esp`
`Cutting Room Floor.esp`
`DawnguardArsenal.esp`
`DeadlyDragons.esp`
`Dragon Combat Overhaul.esp`
`EMCompViljaSkyrim.esp`
`EnchantingAwakened.esp`
`ESFCompanions.esp`
`ExplosiveBoltsVisualized.esp`
`Faction Crossbows.esp`
`Falskaar.esm`
`FireAndIceOverhaul.esp`
`Flora Fixes.esp`
`Frostfall.esp`
`Height Adjusted Races( .+)?\.esp`
`HothFollower.esp`
`hothtrooper44_ArmorCompilation.esp`
`Hunterborn.esp`
`Hypothermia.esp`
`Immersive Horses.esp`
`Immersive Jewelry.esp`
`Immersive Patrols II.esp`
`Immersive Sounds - Compendium.esp`
`ImmersiveSpells.esp`
`Immersive Weapons.esp`
`imp_helm_legend.esp`
`Inconsequential NPCs.esp`
`Inconsequential NPCs - Enhancement.esp`
`Inigo.esp`
`mslVampiricThirst.esp`
`One With Nature.*\.esp`
`Open Cities Skyrim.esp`
`PrvtI_HeavyArmory.esp`
`RealisticNeedsandDiseases.esp`
`Rebirth Monster.esp`
`Relationship Dialogue Overhaul.esp`
`RSkyrimChildren.esm`
`RSChildren - Complete.esp`
`RUSTIC SOULGEMS - (Uns|S)orted\.esp`
`ScopedBows.esp`
`Skyrim Immersive Creatures.esp`
`Skyrim Unlocked.esp`
`SkyTEST-RealisticAnimals&Predators.esp`
`TimingIsEverything.esp`
`TradeBarter.esp`
`Undeath.esp`
`Unique Uniques.esp`
`VioLens.esp`
`Weapons Armor Clothing & Clutter Fixes.esp`
`Wild World.esp`
`WM Flora Fixes.esp` Now Included in CACO SSE
`Wyrmstooth.esp`
```

**Comment by MacSplody** [comment]
[Testing Branch](https://github.com/loot/skyrimse/tree/Requiem-Testing)
**Bugsmasher**
Placing `Requiem - Legendary Bugsmasher Edition.esp` in a group before (not `default`, too many sorting errors) `Requiem.esp` does yield the correct sorting result. 
A separate group ( Anchor (GroupName)) directly before `Requiem.esp` group also works.
![image](https://user-images.githubusercontent.com/1944639/49382026-39228800-f70d-11e8-9961-887391234b5b.png)

**Compatibility**
It's recommended to load the main plugin `Requiem.esp` after other mods.
But there are exceptions to this, and it's not always clear which mods should sort after `Requiem.esp`

**Comment by CptMcSplody** [comment]
[Testing Branch](https://github.com/loot/skyrimse/tree/Requiem-Testing)

Just change the SSE repo in LOOT settings from `v0.13` to `Requiem-Testing`
![image](https://user-images.githubusercontent.com/1944639/49384852-d7195100-f713-11e8-9479-cb51a7f13d13.png)

**Comment by CptMcSplody** [comment]
No feedback, so I'm closing this until there is some actual interest in `Requiem` being added.

**Comment by MacSplody** [comment]
Done in https://github.com/loot/skyrimse/commit/a7b3d7fbc6548b7e408a3d63879229d1df7723a0.
