### ISSUE TITLE
Sorting/Compatibility between Overhauls/Tweaks for Creatures & Combat.

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#497]
Opened this issue as the sorting/compatibility between several Combat & Creature mods has been brought up on the Nexus a few times. 

At the moment this is mainly a place holder for keeping track of any testing & notes.

Plugins so far, with rough load order.

`Mortal Enemies.esp`
`Animal Tweaks.esp`
`Wildcat - Combat of Skyrim.esp`
`Vigor - Combat and Injuries.esp`
`Combat Evolved.esp`
`UltimateCombat.esp`
`Skyrim Revamped - Complete Enemy Overhaul.esp`
`SkyTEST-RealisticAnimals&Predators.esp`
`NoBSAIProjectileDodge.esp`
`Stealth Skills Rebalanced_COMPLETE.esp`
`Ordinator - Perks of Skyrim.esp`
`Thief skills rebalance for Ordinator.esp`
`Requiem.esp`
`Immersive Citizens - AI Overhaul.esp`
`Realistic AI Detection 2 SE.esp`
`J42_ArmorRatingRedux.esp`

**Comment by MacSplody** [comment]
## [Wildcat - Combat of Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/1368)
#### [Compatibility Notes](https://www.nexusmods.com/skyrimspecialedition/articles/21/?)

## [Smilodon - Combat of Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/2824)
#### [Compatibility Notes](https://www.nexusmods.com/skyrimspecialedition/articles/119/?)

**Comment by MacSplody** [comment]
## [Mortal Enemies SE](https://www.nexusmods.com/skyrimspecialedition/mods/4881)

> If you have a preferred attack commit setting you can load it after M.E.
Load this mod after any mods that modify creature/npc stats.

This mods has several different versions with different names for each plugin.
`Mortal Enemies.esp`
`Mortal Enemies - No RunWalk Changes.esp`
`Mortal Enemies - Rival Remix.esp`
`Mortal Enemies - Rival Remix - NoRunWalkChanges.esp`
`Mortal Enemies Patch - Realistic Animals Predators.esp`
`Mortal Enemies - Smilodon Patch.esp`
`Mortal Enemies - 2.0 Test Version.esp`

However most patches use `Mortal Enemies.esp`.
Possible solution would be to add a message to rename the plugins to `Mortal Enemies.esp` to ensure compatibility with patches that depend on it.

It seems the Mod is no longer being supported.

**Comment by Infernio** [comment]
I might make a PR for this one later, but I'll throw it in here for now:

## [Armor Rating Redux SE](https://www.nexusmods.com/skyrimspecialedition/mods/17932)
```
------------
Compability:
------------
    - Should be loaded after other mods that change Game Settings related to
        Armor.
    - Not compatible with any mod that attempts to do the same thing (duh).
    
    Compatible with everything else.
    ...probably.
```

In practice, this seems to mean:
- Do **not** clean ITMs, they're meant to revert changes made to the armor globals by Wildcat and other combat mods.
- Load it after such global-altering mods (Wildcat is the only one I've used that does that).
- Incompatible with other armor rating overhauls (haven't stumbled on any others yet).

**Comment by MacSplody** [comment]
## [Vigor - Combat and Injuries](https://www.nexusmods.com/skyrimspecialedition/mods/1876)

**Compatibility**
###### [Wildcat - Combat of Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/1368)
Taken from Sticky Post on Vigor mod page

> - Is this compatible with Wildcat?
>Both mods are nicely customizable, thus if you really wish to use certain parts of each mod, you can but you HAVE TO read both mods description to know what you are enabling/ disabling to make sure there are no redundant features.

Taken from Wildcat notes

> Vigor - Combat and Injuries: Compatible, but with some overlap. Load Vigor below Wildcat, and make sure you have at least version 5.1 of Vigor. Injuries and stagger: Both mods add injuries and stagger mechanics, so you may want to disable one or the other in its MCM or configuration power to eliminate redundancy.

¯\\\_(ツ)_/¯ User Preference I guess

MCM Update available
[Vigor - Combat and Injuries MCM](https://www.nexusmods.com/skyrimspecialedition/mods/18137)

**Comment by Infernio** [comment]
I've been looking at some of these and hit a roadblock when adding load order info for Wildcat + Enhanced Blood Textures.

[Wildcat's compatibility notes](https://www.nexusmods.com/skyrimspecialedition/articles/21):
> Load Wildcat below Enhanced Blood Textures.

The problem with just adding a 'load EBT after Wildcat' rule is that Wildcat is a low priority override and EBT is an early loader, which obviously causes a cylic interaction. I could move them to a different group, but they're probably in those groups for a reason, so I'm hesitant to do that without discussing it first.

**Comment by MacSplody** [comment]
> > Load Wildcat below Enhanced Blood Textures.
> 
> The problem with just adding a 'load EBT after Wildcat' rule is that Wildcat is a low priority override and EBT is an early loader, which obviously causes a cylic interaction. I could move them to a different group, but they're probably in those groups for a reason, so I'm hesitant to do that without discussing it first.

He means `after` so current sorting is correct.

>Compatible. Enhanced Blood Textures comes with an outdated fix for the "Brawl Bug", while Wildcat comes with the more effective Modern Brawl Bug Fix. Load Wildcat below Enhanced Blood Textures.

**Comment by MacSplody** [comment]
[No BS AI Projectile Dodge](https://www.nexusmods.com/skyrimspecialedition/mods/1763/)

> Wildcat / Smilodon - I haven't checked the plugin yet if they edit the same game setting variable. Put my mod AFTER the this in your load order and it should hypothetically work.   
> 
> Mortal Enemies - Compatible, load order doesn't matter

Sort After:
[Ultimate Combat SE](https://www.nexusmods.com/skyrimspecialedition/mods/17196)

**Comment by MacSplody** [comment]
#### [Armor Rating Redux SE](https://www.nexusmods.com/skyrimspecialedition/mods/17932)

No Conflicts with the following mods.

![image](https://user-images.githubusercontent.com/1944639/57416337-d2dbed00-71f7-11e9-8bea-cad109977a61.png)

**Comment by MacSplody** [comment]
[Wild World SE](https://www.nexusmods.com/skyrimspecialedition/mods/14616)

Compatible Mods
- Animallica (Patch available)
- Birds of Skyrim (Load after Wild World)
- Combat Evolved (Load before Wild World)
- Convenient Horses
- Hunterborn
- Immersive Horses (Patch available)
- More Village Animals (load before Wild World)
- Morrowloot Ultimate (Patch available here)
- OBIS
- Revenge of the Enemies (Patch available)
- Skyrim Immersive Creatures (Patch available)
- SkyTEST Realistic Animals and Predators (Patch available)
- Wild Cat

Incompatible Mods
- Animal Tweaks (Needs patch)
- Less Aggressive Animals
- NARC (Does the same thing)
- One with Nature
- Realistic Wildlife Behavior (Does the same thing)
