### ISSUE TITLE
No Snow Under The Roof: Wild Edits

### ISSUE THREAD

**Issue by Infernio** [loot/skyrimse#531]
1. Load only `Prometheus_No_snow_Under_the_roof.esp`
2. Open record `00104217`
3. Note the `Object Bounds/NAM0` and `Object Bounds/NAM9` changes

I don't see how these could be intentional.

Some info on object bound edits can be found [here](https://forum.step-project.com/topic/11024-worldspace-edits-nam9-and-nam0-object-bounds/), but the TL;DR on them is that they can't be corrected by patching and have to be manually cleaned. The fix is to simply drag and drop the values from `Skyrim.esm`.

**Comment by Infernio** [comment]
CRC after automatic and manual cleaning is `C813F07D`.

**Comment by MacSplody** [comment]
> 
> 
>     1. Load only `Prometheus_No_snow_Under_the_roof.esp`
> 
>     2. Open record `00104217`
> 
>     3. Note the `Object Bounds/NAM0` and `Object Bounds/NAM9` changes
> 
> 
> I don't see how these could be intentional.
> 
> Some info on object bound edits can be found [here](https://forum.step-project.com/topic/11024-worldspace-edits-nam9-and-nam0-object-bounds/), but the TL;DR on them is that they can't be corrected by patching and have to be manually cleaned. The fix is to simply drag and drop the values from `Skyrim.esm`.
