### ISSUE TITLE
Plugins now asking for Skyrim Script Extender

### ISSUE THREAD

**Issue by captice** [loot/skyrimse#550]
Have the latest version of SKSE64 2.0.12 (1.5.62)
I have SkyUI_SE.esp and RaceMenu.esp for SSE coming up with an error 'This plugin requires 'Skyrim Script Extender" to be installed, but missing." these errors were not flagged 9 hours ago when i last loaded up LOOT. was there a hiccup/mixup with the masterlist?

**Comment by MacSplody** [comment]
Corrected in #551

**Comment by captice** [comment]
Thank You
