### ISSUE TITLE
Imperious loadAfter Inconsistencies

### ISSUE THREAD

**Issue by marcopennekamp** [loot/skyrimse#577]
Hey! I've noticed two inconsistencies with the Imperious mod:

1. Ordinator is set to load after Imperious in the master list "to avoid cyclic errors." Imperious and Ordinator are compatible in either order, however, as they don't conflict in any record (I've checked in SSEEdit). This loadAfter entry in the master list actually introduces an error in my case. I'm following the [Nordic Guide](https://www.nexusmods.com/skyrimspecialedition/mods/12562) and have created LOOT groups for each sensible category appearing in Nordic. Imperious is thus far down in the load order for me, while Ordinator is relatively high up. I realize that this is an extreme edge case, but sadly there is no ability to deactivate loadAfter metadata with user metadata (afaik). Is this loadAfter in the master list necessary or could it be changed? Alternatively, is there a way to remove the loadAfter entry from my local LOOT?
2. Imperious conflicts with Apachii Divine Elegance Store. Apachii edits the races for a cosmetic change, so [Apachii herself recommends](https://forums.nexusmods.com/index.php?/topic/5500882-apachii-divine-elegance-store/?p=49129687) that Imperious should be loaded after Apachii (Apachii_DivineEleganceStore_Patch.esp). This could be a possible addition to the masterlist.

Thanks for creating and maintaining LOOT, it's an invaluable tool in my modding toolchain. If I can help in any way, please don't hesitate to ask! 😄

**Comment by MacSplody** [comment]
Hi @marcopennekamp 

> Is this loadAfter in the master list necessary or could it be changed?

It's necessary to prevent sorting errors within the core group if separate mods outside that group are set to load after both `Imperious` and `Ordinator` 
`Imperious` -> `Ordinator`
`Ordinator` -> `CACO - Ordinator Patch`
`Imperious` -> `YOT - Imperious Patch`

`Imperious` -> `YOT - Imperious Patch` -> `Ordinator` -> `CACO - Ordinator Patch`
If `Imperious` -> `Ordinator` after rule is removed and both are still in the same group. 
Then you'll get a sorting error when both `CACO - Ordinator Patch` and `YOT - Imperious Patch` are in a group before `Imperious` and  `Ordinator`.

> is there a way to remove the loadAfter entry from my local LOOT?

There are two ways, you can:
- **(A)** not use the `masterlist.yaml`(i.e. delete your local copy of the `masterlist.yaml`). 
But then you would only have the default group and sorting. 
And none of the other information such as cleaning, compatibility, patch messages.
- **(B)** edit the `masterlist.yaml` locally to remove the rule.
`Users\%yourusername%\AppData\Local\LOOT\Skyrim Special Edition`

Both require that you turn off _update master list before sort_.
![image](https://user-images.githubusercontent.com/1944639/50825481-0897c480-1331-11e9-8d7f-c166332bb82b.png)

> Imperious conflicts with Apachii Divine Elegance Store. Apachii edits the races for a cosmetic change, so [Apachii herself recommends](https://forums.nexusmods.com/index.php?/topic/5500882-apachii-divine-elegance-store/?p=49129687) that Imperious should be loaded after Apachii (Apachii_DivineEleganceStore_Patch.esp). This could be a possible addition to the masterlist.

Imperious will sort after `Apachii Divine Elegance Store` by default. If you place `Apachii Divine Elegance Store` in a group after `Imperious` then it would need the load after rule.
I can add that rule just to be sure though.

**Comment by marcopennekamp** [comment]
Thanks for the quick reply and the in-depth explanations! Really appreciate it. 😄 

> Then you'll get a sorting error when both CACO - Ordinator Patch and YOT - Imperious Patch are in a group before Imperious and Ordinator.

You mean in a group _after_ Imperious and Ordinator?

At first glance, this sounds like a flaw with the solver. Let's say we have Imperious, Ordinator, and the two patches you mention. Imperious and Ordinator are in group `A`, the patches are in group `B`. We thus have the following rules:

```
AEnd -> BStart
AStart -> Ordinator -> AEnd
AStart -> Imperious -> AEnd
BStart -> CACO - Ordinator Patch -> BEnd
BStart -> YOT - Imperious Patch -> BEnd
```

Surely, this rule set has the simple solution `AStart -> Ordinator -> Imperious -> AEnd -> BStart -> CACO - Ordinator Patch -> YOT - Imperious Patch -> BEnd`, among other, equally valid solutions. Are groups more complicated than I imagine or is there something I overlooked?

From another angle, I'd expect a metadata setting such as `after` to yield _less_ errors with _less_ rules, not _less_ errors with _more_ rules. This, too, hints at a flaw with the solver.

I realise I may be overstepping my welcome here, but now I've grown interested in the problem. 😅 (I'd also be interested in investigating this if you think it could indeed be improved.)

> Both require that you turn off update master list before sort.

Thanks for the in-depth explanation, but I want to avoid that. Intuitively, I'd say merging the masterlist with a user-defined optional local file at the top level (i.e. whole mod entries get replaced) would be a well-balanced solution and relatively easy to implement. I could maybe fork that in.

> Imperious will sort after Apachii Divine Elegance Store by default. If you place Apachii Divine Elegance Store in a group after Imperious then it would need the load after rule. I can add that rule just to be sure though.

I didn't realise it sorted that way by default, but yes, my grouping changed that.

**Comment by MacSplody** [comment]
> I realise I may be overstepping my welcome here, but now I've grown interested in the problem.

Not at all, as long as you're polite, then you're welcome to provide feedback, 

> > Then you'll get a sorting error when both CACO - Ordinator Patch and YOT - Imperious Patch are in a group before Imperious and Ordinator.
> 
> You mean in a group _after_ Imperious and Ordinator?

No I mean, `CACO - Ordinator Patch` and `YOT - Imperious Patch` are in the `default` group.
This is where most patches are placed by default.
`Ordinator` & `Imperious` are in the `core` group, which is after `default`.

`Core` group mods must sort after default group mods, except when: 
- The `default` plug-in has a load after rule for the mod in the `Core` group.
- The `Core` group mod is a master for the `default` plug-in.
- The `Core` group mod is set as required by the `default` plug-in.

Okay imagine that Ordinator `after` Imperious rule is not included.

`Ordinator.esp` -> `CACO - Ordinator Patch.esp`
`Imperious.esp` -> `YOT - Imperious Patch.esp`

Which should sort after the other?

`Ordinator.esp`(core) after `YOT - Imperious Patch.esp`(default)
or
`Imperious.esp`(core) after `CACO - Ordinator Patch.esp`(default)

> From another angle, I'd expect a metadata setting such as after to yield less errors with less rules, not less errors with more rules. This, too, hints at a flaw with the solver.

Setting an after in the group does `yield fewer errors with fewer rules`.
To achieve no errors with Ordinator & Imperious in the same group without that after rule:
- Every possible patch for both would need to be added to the `core` group.
- Every mod which is set to load after any mod in the `Core` group would need to be added.
- And you could keep repeating those two statements to deal with possible errors.

**Comment by marcopennekamp** [comment]
Thanks for the explanations about the `default` group, I wasn't aware of that!

> Which should sort after the other?

Each patch should sort after its respective master file. The order of Ordinator and Imperious should be arbitrary. What's happening instead is that the rules for the `default` group create an interaction that shouldn't be present in the first place. You see my point here, right? You place a mod in a group which logically comes before another group, even though the mod shouldn't be placed before, but after.

I realize that this is a design tradeoff: (a) Have a default group and support mods that aren't grouped or (b) require every mod to be grouped, but simplify interactions. I would prefer the latter, but I can see why the former choice is better for less experienced users who want to add ungrouped mods to LOOT.

> Every possible patch for both would need to be added to the core group.

Or to _another_ group which doesn't impose an order (like `default`), but requires files to have a load after/requirement/master rule. Basically a `patches` group.

> Every mod which is set to load after any mod in the Core group would need to be added.

This, too. The problem is not that mods would need to be grouped, but that mods which should come after mods in the core group are not added to the core (or a later) group. 

The behavior of the `default` group directly contradicts assumptions made about group ordering, which is what creates all these complexities. As it stands, LOOT sits somewhere in the middle between two extremes: (a) Have a single group, but perfectly model loadAfter relationships, or (b) assign each mod to a group, modeling loadAfter relationships only for mods inside the group and patches outside the group, but without a `default` group or other complex interactions.

It works, though, and thank you for that! I am aware that there is no telling if a better design would actually improve things in practice, because it's so hard to gauge the quality of a load order. It's also hard to justify changing the core architecture just so a few quirky interactions get improved. But I believe it's fun to think about alternative systems and I hope you don't feel like it's a waste of your time, haha. 😅

**Comment by CptMcSplody** [comment]
@MaddBomber83 No worries, https://loot.readthedocs.io/en/latest/app/sorting.html details how sorting is handled if you're interested to know more.

**Comment by MacSplody** [comment]
@marcopennekamp No worries, https://loot.readthedocs.io/en/latest/app/sorting.html details how sorting is handled if you're interested to know more.
