### ISSUE TITLE
Failed to sort plugins

### ISSUE THREAD

**Issue by horker42** [loot/skyrimse#584]
Hi - thank you for taking a look at this (and for creating LOOT, of course).  

I'm having an issue where I can't sort my plugins b/c LOOT is saying there's a cyclic interaction detected between plugins "ELFXEnhancer.esp" and "Immersive Citizens - AI Overhaul.esp". Back cycle: Immersive Citizens - AI Overhaul.esp, ELFXEnhancer.esp.  

I tried to manually reorder these two files in LOOT, but I am unable to edit the metadata (it appears to be greyed out for ELFXEnhancer.esp).  My understanding is that all Immersive Citizens files must come after ELFX files, but when I try to edit ELFXEnhancer metadata, it says that it must come after Immersive Citizens - AI Overhaul, and as I noted, LOOT will not let me reorder the files.  

Is there any way that I can override LOOT to resolve this issue?  My apologies if this is an easy fix - I'm very much a n00b to modding Skyrim.  

Thank you very much for any assistance you can provide.
[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/2770899/LOOTDebugLog.txt)

**Comment by MacSplody** [comment]
Hi @horker42 

> I'm having an issue where I can't sort my plugins b/c LOOT is saying there's a cyclic interaction detected between plugins "ELFXEnhancer.esp" and "Immersive Citizens - AI Overhaul.esp". Back cycle: Immersive Citizens - AI Overhaul.esp, ELFXEnhancer.esp.

> I tried to manually reorder these two files in LOOT, but I am unable to edit the metadata (it appears to be greyed out for ELFXEnhancer.esp).

You're getting the error because you adding a rule that conflicts with a masterlist rule.

> My understanding is that all Immersive Citizens files must come after ELFX files,

If you're using the patch included with the Immersive Citizens for ELFX Enhancer.
Then there is no reason to load ICAIO after ELFX Enhancer.

So just remove the after rule you have set in ICAIO for ELFX Enhancer and the error will stop happening.

**Comment by horker42** [comment]
Thank you very much for the quick response.  I reset all the user metadata I added for my ELFX files and Immersive Citizens files (removing my attempts to reorder them through rules).  But now I
[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/2770994/LOOTDebugLog.txt)
'm getting the message:  "Cyclic interaction detected between "Immersive Citizens - ELFXEnhancer patch.esp" and "ELFX - Hardcore.esp". Back cycle: ELFX - Hardcore.esp, Immersive Citizens - ELFXHardcore patch.esp, ELFXEnhancer.esp, Immersive Citizens - ELFXEnhancer patch.esp"

I may have misinterpreted your response, but the files listed above now include no changes made by me.

**Comment by MacSplody** [comment]
You can't use both  `ELFXEnhancer.esp` and `ELFX - Hardcore.esp` at the same time.
Both are doing the same thing in regards to lighting. 

**Try with only:**

`Immersive Citizens - AI Overhaul.esp`
`ELFXEnhancer.esp`
`Immersive Citizens - ELFXEnhancer patch.esp`

**Or**

`Immersive Citizens - AI Overhaul.esp`
`ELFX - Hardcore.esp`
`Immersive Citizens - ELFXHardcore patch.esp`

**Comment by horker42** [comment]
Thanks again for your help with this.  Your response resolved my issue.  I really appreciate your assistance.

**Comment by MacSplody** [comment]
@horker42 You're welcome. 
If you're just starting out modding it can be tough as there is a lot to take in.
