### ISSUE TITLE
LOOT v0.14.1 (less dragons meta error)

### ISSUE THREAD

**Issue by easelgames** [loot/skyrimse#588]
Previous version didn't mention this. LOOT displays a "delete" error for "less dragons10.esp. It states that it's already included with "timing is everything - quest delay and timing control" However, I'm using "Dynamic Timescale" NOT the one loot mentions. It's not even been downloaded before... (also it's an LE mod only...) 
![loot_21vcnfs79a](https://user-images.githubusercontent.com/46850157/51431268-80e56c00-1bf4-11e9-80d7-d2c0b583d63d.png)

**Comment by MacSplody** [comment]
@easelgames Can you link the file you're using? Also a list the names of each plugin that cause this mesage to show.

**Comment by MacSplody** [comment]
@easelgames Should be fixed now, update your masterlist.

**Comment by easelgames** [comment]
Thanks! Sorry was at work.
