### ISSUE TITLE
Convenient Horses mod is loading before Open Cities mod, should load after

### ISSUE THREAD

**Issue by phillipjohnmc** [loot/skyrimse#59]
Just reporting this issue, subject line says the problem (if CH loads before OC, causes CTDs, so it should load after OC). I changed the metadata for myself but I think it should be changed on your end as well, yes? Let me know if you need more info

**Comment by Ortham** [comment]
The specific plugin names would be good, or your copied plugin metadata.

**Comment by phillipjohnmc** [comment]
Open Cities Skyrim.esp
[spoiler][code]{
 "name": "Open Cities Skyrim.esp",
 "enabled": true,
 "priority": 0,
 "globalPriority": 70,
 "after": [
  {
   "name": "Atlas Map Markers.esp",
   "display": "Atlas Map Markers.esp",
   "condition": ""
  },
  {
   "name": "The Horkerpocalypse.esp",
   "display": "The Horkerpocalypse.esp",
   "condition": ""
  },
  {
   "name": "Unique Region Names.esp",
   "display": "Unique Region Names.esp",
   "condition": ""
  },
  {
   "name": "URN+CoT Patch.esp",
   "display": "URN+CoT Patch.esp",
   "condition": ""
  }
 ],
 "req": [],
 "inc": [],
 "msg": [],
 "tag": [
  {
   "name": "C.Location",
   "condition": "",
   "isAddition": true
  }
 ],
 "dirty": [],
 "clean": [],
 "url": []
}
[/code][/spoiler]

Convenient Horses.esp
[spoiler][code]{
 "name": "Convenient Horses.esp",
 "enabled": true,
 "priority": 0,
 "globalPriority": 0,
 "after": [
  {
   "name": "Open Cities Skyrim.esp",
   "display": "Open Cities Skyrim.esp",
   "condition": ""
  }
 ],
 "req": [],
 "inc": [],
 "msg": [],
 "tag": [],
 "dirty": [],
 "clean": [],
 "url": []
}
[/code][/spoiler]

**Comment by phillipjohnmc** [comment]
The Convenient Horses metadata has my change in it

**Comment by Arthmoor** [comment]
Likely not the best of placed to ask about this, but in what way is it supposed to be causing CTDs and for which game? There should be no reason either of these mods needs to care about the other.

**Comment by phillipjohnmc** [comment]
I don't know why it does, and I'm not the mod author. I know that if I run the game with CH loaded above OC, I'll have a CTD from time to time, whereas if it's after, the CTDs stop. Of course, a CTD might be caused by something else. But, the CH mod author says on the mod's description page that CTDs might happen if CH is above OC. So, I've been manually placing it after OC. I asked in the CH posts page if there were a way to make LOOT sort and place CH after OC without having to manually move it every time, and someone mentioned to edit the metadata. Someone else mentioned to sent a report about this issue to LOOT, which is why I've done this.

**Comment by Ortham** [comment]
Cause of the crashing aside, I've added the metadata in 28db7d1b7f8abcc023f0e61c012c68c472967080.

**Comment by phillipjohnmc** [comment]
ok thanks!

**Comment by Arthmoor** [comment]
Gave the mod a once over, I don't see this rule update being an issue since there are no conflicts at all between it an OCS (which btw means it isn't likely to crash either, but hey).

**Comment by phillipjohnmc** [comment]
yeah i don't think OC is crashing in and of itself, but with CH loaded over it, i had CTDs that stopped when i started loading it after. perhaps mention it to the mod developer? he says on his own description page: "Open Cities: I haven't tested, but it has been reported that CTD may happen if CH is loaded before OC."

btw i love OC! thanks for the good work :)
