### ISSUE TITLE
SSE - 3D Trees & Plants + Cutting Room Floor (CRF) Patch Error in Loot (yet .esp is there?)

### ISSUE THREAD

**Issue by easelgames** [loot/skyrimse#595]
Loot (latest version) is saying that I haven't enabled a patch for CRF + 3D Trees/Plants, even though I can see it in loot's plugin list? Both MO2/Loot run as administrator.
![3d trees crf patch warning](https://user-images.githubusercontent.com/46850157/51755236-292f8080-208c-11e9-818f-8eeab47e918a.png)

**Comment by MacSplody** [comment]
@easelgames Thanks for letting us know. It should be corrected now, can you update your masterlist and try again?

**Comment by easelgames** [comment]
Issue is fixed. However I think it got fixed before you updated stuff. I was using the (2nd) latest version of 3D T+P and this may have caused the weird error. It went away after updating this. I'm assuming QW's update patched the newer version I hadn't had. Causing version numbers to mismatch or something? I'm not familiar with these things.

**Comment by MacSplody** [comment]
No it's based on module names, we do use checksum if required and version if available for some other checks though. Anyhow thanks I'll mark this as closed.
