### ISSUE TITLE
"Ordinator" and "Scoped Bows"

### ISSUE THREAD

**Issue by pStyl3** [loot/skyrimse#6]
Enai Siaion [wrote](http://forums.bethsoft.com/topic/1611336-rel-loot-thread-26/?p=25267498):

> This mod seems to sort Scoped Bows after Ordinator so it breaks the archery tree and I get a million complaints that Ordinator has a bug.

Mods in question are:
[Ordinator - Perks of Skyrim](http://www.nexusmods.com/skyrimspecialedition/mods/1137)
[Scoped Bows SE](http://www.nexusmods.com/skyrimspecialedition/mods/912)

Both mod authors further discussed this [here](https://forums.nexusmods.com/index.php?/topic/4991505-scoped-bows-se/?p=44956065), and the mod description of Scoped Bows now reads:

> Ordinator - Perks of Skyrim ...is perfectly compatible with Scoped Bows! Just don't use the optional "Eagle Eye Tweak" that comes with Scoped Bows!

Therefore, could we warn users to not use "ScopedBows_EagleEyeTweak.esp" if "Ordinator - Perks of Skyrim.esp" is used?

**Comment by Ortham** [comment]
So just add an `inc` entry for `ScopedBows_EagleEyeTweak.esp` to `Ordinator - Perks of Skyrim.esp`?

**Comment by pStyl3** [comment]
I think that would be sufficient, and in compliance with what OutLaw666 (Scoped Bows) writes in his/her mod description.
