### ISSUE TITLE
LOOT error message

### ISSUE THREAD

**Issue by ramrabza** [loot/skyrimse#61]
Hi
there is an error message during the plugin sorting
[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/1755429/LOOTDebugLog.txt)

cheers

**Comment by SuperSandro2000** [comment]
Dupe https://github.com/loot/loot/issues/882

**Comment by pStyl3** [comment]
Update LOOT to version 0.12.4, install all recommended Windows updates and make sure that you [enable TLS 1.2 support](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in) to support updating the masterlists from LOOT's official repositories on GitHub.
