### ISSUE TITLE
loot not loading after reinstall

### ISSUE THREAD

**Issue by Sandstormwolf** [loot/skyrimse#62]
[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/1773591/LOOTDebugLog.txt)

I have skyrim se, and it was working fine till I had to reinstall Nexus mod manager.  now it will not run.  I have Windows 10 operating system.

**Comment by Ortham** [comment]
Try running the Skyrim SE launcher, LOOT can't find the game.

**Comment by Sandstormwolf** [comment]
got loot up thank you1
