### ISSUE TITLE
masterlist cyclic interaction between "1nivWICCloaks.esp" and "WACCF_Armor and Clothing Extension.esp"

### ISSUE THREAD

**Issue by snizkabiz** [loot/skyrimse#626]
Good afternoon,

I just sorted my load order today I guess after a masterlist revision that changed some stuff and found a cyclic interaction.  I had this load order for around a month with no problems in LOOT and I haven't changed anything, but for some reason today LOOT found this cyclic interaction.

The interaction goes as follows:
Cyclic interaction detected between "Immersive Citizens - AI Overhaul.esp" and "EnhancedLightsandFX.esp":

Immersive Citizens - AI Overhaul.esp
 [Masterlist Load After]
Dawnstar.esp
 [Master]
**Prometheus_No_snow_Under_the_roof.esp
 [Masterlist Load After]
EnhancedLightsandFX.esp**
 [Masterlist Load After]
Immersive Citizens - AI Overhaul.esp

The part in bold is what I believe is the new revision that is causing the problem.  I did some digging and found that in my previous load order all of these rules applied other than EnhancedLightsandFX.esp loading after Prometheus_No_snow_Under_the_roof.esp.  My game works fine with the load order that way and I'm not entirely sure why Prometheus now needs to be loaded before ELFX.  I can also confirm that this is a masterlist related problem because I don't have any load after user metadata on these plugins and the only thing that has changed in between load order sorts was the addition of that one rule to the masterlist.  Either way LOOT doesn't work for me with the current masterlist due to this cyclic interaction so hopefully something can be done.

Thanks!

Edit: Sorry if anything I've said is wrong or uninformed I'm not an expert in coding or modding just a hobbyist so really I'm just trying to help fix what might be an issue, thanks again.

**Comment by MacSplody** [comment]
@snizkabiz Why is `Dawnstar.esp` a master for `Prometheus_No_snow_Under_the_roof.esp`?

**Comment by snizkabiz** [comment]
@CptMcSplody Oh, because I'm dumb sorry, my Prometheus_No_snow_Under_the_roof.esp is a merged file of no snow under the roof and it's patches for arthmoor's villages.  I totally forgot about that so would the fix for this then be to just remove the dawnstar patch from the merge and load it as a separate plugin?  Sorry again like I said before not an expert.

**Comment by MacSplody** [comment]
@snizkabiz You're better off just merging the patches together, and leave the main plugin separate.
Otherwise, you'll run into more issues with the main module.
Bugfixes should be fine to merge into the main plugin.

**Comment by snizkabiz** [comment]
@CptMcSplody ok so make two merges one of the bugfixes and the main mod and one of the patches.  Will do thanks for the help!

**Comment by snizkabiz** [comment]
@CptMcSplody whew so I fixed that issue rebuilding merges can be a real pain, but now LOOT is detecting a second cyclic interaction:


Cyclic interaction detected between "1nivWICCloaks.esp" and "WACCF_Armor and Clothing Extension.esp":

1nivWICCloaks.esp
 [Masterlist Load After]
aMidianBorn_ContentAddon.esp
 [Group]
Guard Dialogue Overhaul.esp
 [Masterlist Load After]
Weapons Armor Clothing & Clutter Fixes.esp
 [Master]
WACCF_Armor and Clothing Extension.esp
 [Group]
1nivWICCloaks.esp


This time I made absolutely sure that none of these plugins originate from any merges and none of them have any user metadata on them.  I would assume that means that this problem is not of my doing this time but I could still be wrong about that.

Thanks again and sorry for all these problems.  I've been using LOOT for years and never had this many issues hopefully I can get all this sorted out though.

**Comment by MacSplody** [comment]
@snizkabiz Okay, that's probably because of the WACCF after GDO I added. I'll see if there is a work around for it.

**Comment by MacSplody** [comment]
@snizkabiz If you change `1nivWICCloaks.esp` group to underrides is the error resolved?

**Comment by snizkabiz** [comment]
@CptMcSplody Yes it does!... but there is still another cyclic interaction involving GDO:


Failed to sort plugins. Details: Cyclic interaction detected between "aMidianBorn_ContentAddon.esp" and "Lore Weapon Expansion.esp":

aMidianBorn_ContentAddon.esp
 [Group]
Guard Dialogue Overhaul.esp
 [Masterlist Load After]
Weapons Armor Clothing & Clutter Fixes.esp
 [Master]
WACCF_Armor and Clothing Extension.esp
 [Group]
Lore Weapon Expansion.esp
 [User Load After]
aMidianBorn_ContentAddon.esp

EDIt: oops just read that fully let me check my rules first one minute

**Comment by MacSplody** [comment]
Okay now do the same for Lore Weapon Expansion.

**Comment by snizkabiz** [comment]
@CptMcSplody YES! that's done it! All issues have been resolved and the load order has been properly sorted.  Thank you so much for baring with me while we sorted this problem out and hopefully it worked out another rule or something in the process.
