### ISSUE TITLE
LOOT is sorting GDO and WACCF sorting incorrectly

### ISSUE THREAD

**Issue by pikachu01** [loot/skyrimse#639]
Loaded up xEdit after sorting with LOOT with GDO and WACCF and I got this error:

[00:11]  - Error: "Weapons Armor Clothing & Clutter Fixes.esp" has a lower load order than "Guard Dialogue Overhaul.esp"

Looking at GDO's description:
Guard Dialogue Overhaul.esp. Should be placed after any mod that alters Guard Dialogue, after Immersive Armors (if IA is installed) **and before RDO and any Mod that edits Skyrim vanilla Weapons** or Armor (such as aMidianborn_Skyforge_Weapons.esp from the Book of Silence or Weapons and Armor Fixes - Remade), otherwise anywhere on the .esp list. Typically, people load GDO shortly after CRF.

**Comment by MacSplody** [comment]
@pikachu01 I've removed the WACCF after GDO rule for now as it was causing sorting errors and conflicts between other mods.

You can still add a load after GDO to WACCF or change the group of GDO to sort it before WACCF.

Other options are
- Remove conflicting weapon/armour records from GDO.
- Forward WACCF weapon/armour records changes to GDO.

> [00:11] - Error: "Weapons Armor Clothing & Clutter Fixes.esp" has a lower load order than "Guard Dialogue Overhaul.esp"

FYI that's a xEdit modgroups error and nothing critical to your actual load order.
