### ISSUE TITLE
New patches for JK's Skyrim + ETaC

### ISSUE THREAD

**Issue by Teabag86** [loot/skyrimse#652]
https://www.nexusmods.com/skyrimspecialedition/mods/24416
Replacer .esp file for JK's Skyrim. Includes specific patches created for this mod combo. Individual patches for these mods from JKS and ETaC are not required. No specific load order. Master files load order is based off LOOT.

- [x] ETaC - Complete_JKs Skyrim_Blowing in the Wind_Patch.esp
- [x] ETaC - Complete_JKs Skyrim_CFTO Patch.esp
- [x] ETaC - Complete_JKs Skyrim_Holidays_Patch.esp
- [x] ETaC - Complete_JKs Skyrim_NSUTR_Patch.esp

- [x] JKS_DoS_ETaC_Holidays_Patch.esp
- [x] JKS_DoS_ETaC_Blowing in the Wind_Patch.esp

Blowing in the Wind https://www.nexusmods.com/skyrimspecialedition/mods/5124
CFTO https://www.nexusmods.com/skyrimspecialedition/mods/8379
Holidays https://www.nexusmods.com/skyrimspecialedition/mods/1533
NSUTR https://www.nexusmods.com/skyrimspecialedition/mods/518

**Comment by Teabag86** [comment]
Additional patches have been added to the above mod page to be used with the JK's Skyrim, Dawn of Skyrim and ETaC mod combination. Individual patches for these mods from JKS, DoS and ETaC are not required.

JKS_DoS_ETaC_Holidays_Patch.esp
JKS_DoS_ETaC_Blowing in the Wind_Patch.esp

Recommended load order (LOOT sorted)
https://imgur.com/a/jMZl2sH

**Comment by MacSplody** [comment]
@Teabag86 A bit trickier, I could use a checksum to confirm it's the replacer.
But if it's ever updated or modified that check will fail.
Would you consider adding a version to the replacers file header?
`1.0etac` would work.

**Comment by Teabag86** [comment]
As in the HEDR- Header / Version record?
Currently it is 1.700000 like my other files.
Happy to change it if this is what you mean.

**Comment by MacSplody** [comment]
SNAM - Description

![image](https://user-images.githubusercontent.com/1944639/55232431-76130d00-521d-11e9-87c3-85741320ac5a.png)
