### ISSUE TITLE
CACO - Beyond Skyrim Bruma Patch

### ISSUE THREAD

**Issue by Teabag86** [loot/skyrimse#654]
https://www.nexusmods.com/skyrimspecialedition/mods/24830

A comprehensive overhaul for both mods to work together seamlessly. Highly recommended.
Beyond Skyrim - Bruma SE
https://www.nexusmods.com/skyrimspecialedition/mods/10917

Complete Alchemy and Cooking Overhaul https://www.nexusmods.com/skyrimspecialedition/mods/19924

Load Order (LOOT sorted)
BSAssets.esm
BSHeartland.esm
BS_DLC_patch.esp
Complete Alchemy & Cooking Overhaul.esp
CACO_Beyond Skyrim Bruma_Patch.esp

**Comment by CptMcSplody** [comment]
Already added 6615bc9
