### ISSUE TITLE
New CACO - Bruma - Rare Curios Patch

### ISSUE THREAD

**Issue by Teabag86** [loot/skyrimse#655]
Available from CACO - Bruma Patch Page
https://www.nexusmods.com/skyrimspecialedition/mods/24830

The changes from CACO - Rare Curios Patch are already included in this patch. So don't use both.

Recommended load order (LOOT sorted)
ccbgssse037-curios.esl
BSAssets.esm
BSHeartland.esm
BS_DLC_patch.esp
Complete Alchemy & Cooking Overhaul.esp
CACO_Beyond Skyrim Bruma_Patch.esp
CACO_Bruma_Rare Curios_Patch.esp

**Comment by MacSplody** [comment]
@Teabag86 Thanks, it's added now.

BTW I was testing with bash and Is this the expected result?

![image](https://user-images.githubusercontent.com/1944639/56078863-a85b6780-5de4-11e9-97c7-5cb914fa85ec.png)

**Comment by Teabag86** [comment]
Ah Damn! Thank you. I didn't think the Delev tag would remove those items. I guess because it is a patch to the master. I'll get that fixed tonight.
