### ISSUE TITLE
v0.3 Cyclic interaction when sorting with Default settings & masterlist

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#66]
Failed to sort plugins. Details: Cyclic interaction detected between "MLU.esp" and "Alternate Start - Live Another Life.esp". Back cycle: Alternate Start - Live Another Life.esp, RealisticWaterTwo.esp, MLU.esp

When I change either Realistic water to morrowloots group or MLU to default it completes the sort.

I'm assuming this is because Alt start has priority over MLU, while MLU has priorty over RWT. But RWT is set to load after alt start.

**Comment by Ortham** [comment]
Please post your debug log, see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by MacSplody** [comment]
[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/1874702/LOOTDebugLog.txt)
- Single failure Full Debug Log.

[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/1874744/LOOTDebugLog.txt)
- Larger, Did some testing. Seems to always fail with MLU group set to followers & trying to sort any mod above MLU.esp and after Alt start.
- Last pass is with MLU.esp group changed from followers to default which completed successfully.

[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/1875936/LOOTDebugLog.txt)
- Fails on run Outside MO2 as well with just 3 mods. MLU, Alt start & realistic water.

[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/1875953/LOOTDebugLog.txt)
- Sort completes when MLU is set to alt start group

**Comment by Ortham** [comment]
Yeah, what's happening is that

- RW has LAL as `after` metadata,
- MLU belongs to the `Followers` group
- LAL belongs to the `Alternate Start` group
- RW belongs to the `default` group
- The `Alternate Start` group loads after the `Followers` group
- The `Followers` and `Alternate Start` groups both load after the `default` group.

This derives:

- LAL -> RW
- MLU -> LAL
- RW -> MLU

Which is impossible to resolve. Going by MLU's Nexus page, I don't think it belongs in the followers group. Probably another group that just loads after `default` should be fine.

**Comment by MacSplody** [comment]
Could a group for realistic water be added after alt start, and before dynamic patches such as "Late loaders" ? This would also avoid the issue and RWT should generally have priority anyway to avoid LOD & water seams.

**Comment by Ortham** [comment]
Yes, that would also work. I erred on the side of making minimal changes though.
