### ISSUE TITLE
Zim's Immersive Artifacts has to load after Audio Overhaul Skyrim - Legacy of the Dragonborn Patch

### ISSUE THREAD

**Issue by DFelten** [loot/skyrimse#679]
The `zia_complete pack.esp` from [Zim's Immersive Artifacts](https://www.nexusmods.com/skyrimspecialedition/mods/9138) has to load after the [Consistency Patch for Legacy of the Dragonborn](https://www.nexusmods.com/skyrimspecialedition/mods/12466?tab=files) `Audio Overhaul Skyrim - Legacy of the Dragonborn Patch.esp`.

The patch overwrites the changes of `T03Nettlebane` and removes the new object effect. The changes are there again when loading the ESP of Zim's Immersive Artifacts after the patch.

**Comment by MacSplody** [comment]
@DFelten Thanks, that change has been pushed.
