### ISSUE TITLE
Nether's Follower Framework has to load after Qw_BeyondReach_USSEP Patch

### ISSUE THREAD

**Issue by DFelten** [loot/skyrimse#682]
The `nwsFollowerFramework.esp` from [Nether's Follower Framework](https://www.nexusmods.com/skyrimspecialedition/mods/18076) has to load after the [QUASIPC](https://www.nexusmods.com/skyrimspecialedition/mods/18369) `Qw_BeyondReach_USSEP Patch.esp`.

The patch overwrites the quest `DialogueFollower` and removes the follower slots of the framework. It's working when loading Nether's Framework after the patch.

![FrameWork-Warning](https://user-images.githubusercontent.com/1169185/58116365-6223d000-7bfc-11e9-9c95-eafdb7b62319.jpg)

**Comment by MacSplody** [comment]
`Qw_BeyondReach_USSEP Patch.esp` is likely to conflict with other follower mods.
I'll add an after to `nwsFollowerFramework.esp` for `Qw_BeyondReach_USSEP Patch.esp`.
The patch can be moved to an earlier group.

**Comment by MacSplody** [comment]
@DFelten Thanks, the changes have been pushed.
