### ISSUE TITLE
Unofficial Skyrim Special Edition Patch 4.1.8a and package of Aventus Aretino 

### ISSUE THREAD

**Issue by DFelten** [loot/skyrimse#691]
Currently there is a problem with the Unofficial Skyrim Patch and some children mods:

https://forums.nexusmods.com/index.php?showtopic=4978860/#entry70583578

If one of these mods is active together with Unofficial Skyrim Special Edition Patch 4.1.8a, the game does not load anymore:

* TK Children
* RS Children
* Simple Children
* Killable Children
* Axe's RS Children Mod
* Improved Adoptions
* Immersive Weapon Integration

**Comment by MacSplody** [comment]
@DFelten Thanks, just have to decide on the best way to handle that issue.

> ALERT FROM UNOFFICIAL PATCH PROJECT TEAM: It has been determined that the AI package USKPAventusAretinoSleepOrphanage [PACK:05000808] on Actor AventusAretino "Aventus Aretino" [NPC_:00014132] is redundant and has been removed from Aventus and deleted. However USSEP compatibility solutions with various mods altering Aventus still refer to the now nonexistent AI pack. This results on a infinite-loading screen on the main menu when starting the game.
> 
> Users, if you are familiar with xEdit, remove the unresolved reference error that now exists in this mod's compatibility solution with USSEP. Mod author, it is recommended you do the same and re-release for those not fluent in xEdit. 

AventusAretino 00014132
PKID - Package
[05000808] < Error: Could not be resolved >

Modules affected:
[Axe's RS Children](https://www.nexusmods.com/skyrimspecialedition/mods/16044)
`aAxeRSCtweaks.esp` (26F29854)

[Killable Children](https://www.nexusmods.com/skyrimspecialedition/mods/1108)
`Killable Children.esp` (C38F2891)

[RS Children Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/2650)
`RSChildren.esp` (6407E29C) Non Playable - USSEP
`RSChildren.esp` (2CC8F8D2) Playable - USSEP

[Simple Children](https://www.nexusmods.com/skyrimspecialedition/mods/22789)
`FacegenForKids.esp` (DB8F0931)

[TKChildren SE](https://www.nexusmods.com/skyrimspecialedition/mods/5916)
`TKChildren.esp` (8B45CAFD) English Version
`TKChildren.esp` (B5A9AA32) Japanese Version

Fixed Mods
Improved Adoptions USSEP fix.esp (EE0A02C2)
ImmersiveIntegrationSE15.esp (85B039B1)

**Comment by DFelten** [comment]
I think currently there has to be a warning that they are not compatible with a link to a tutorial to remove the specific reference. With xEdit it's really easy. Unfortunately I have not found any patches for the mods on Nexus yet.

**Comment by Arthmoor** [comment]
It would be better still to prod the folks who made those additional patches to update them and thus eliminate the problem entirely.

**Comment by MacSplody** [comment]
Done as of https://github.com/loot/skyrimse/commit/056a413a36bbecd2aaced7e8d6e6c8c35494cb4b
