### ISSUE TITLE
Misc. College of Winterhold Tweaks - Compatibility and Conflicts.

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#703]
#517 
#### Source
**[Compatibility and Conflicts Article](https://www.nexusmods.com/skyrimspecialedition/articles/906)**

---

[Alternate Start - Live Another Life](https://www.nexusmods.com/skyrimspecialedition/mods/272)
- [x] Sort Mage-light Maintenance after ASLAL.

[Apepi's Better College of Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/4221)
- [x] Incompatible with Erratum Etc.
- [x] Use Erratum Etc. Lite instead.

[College of Winterhold Light Pillar Fix](https://www.nexusmods.com/skyrimspecialedition/mods/8591/?)
- [x] Mage-light Maintenance is incompatible.
  _Redundant:  Fixes the light pillars by another method._

[College of Winterhold Upgraded](https://www.nexusmods.com/skyrimspecialedition/mods/4984)
- [x] Incompatible with Erratum Etc.
- [x] Use Erratum Etc. Lite instead.

[Enlightened College of Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/8710)
- [x] Mage-light Maintenance is incompatible.
  _Redundant:  Fixes the light pillars by another method._

[Immersive College of Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/17004)
- [x] Mage-light Maintenance is incompatible.
 _Redundant:  Fixes the light pillars by another method._

- [x] Sort Governable Gatekeeper after ICoW
 _Minor Conflict:  ICoW disables the trigger GG uses._

- [x] Sort after Scheduled Savos
 _Minor Conflict:  Both mods edit Savos' courtyard AI Package._

- [x] Incompatible with Erratum Etc.
- [x] Use Erratum Etc. Lite instead.

Edit: https://github.com/loot/skyrimse/issues/703#issuecomment-513530076
[Improved College Entry](https://www.nexusmods.com/skyrimspecialedition/mods/22184)
- [x] Already includes Friendly Faralda.
- [x] Mage-light Maintenance is incompatible.
 _Redundant:  Fixes the light pillars by another method._
- [x] Already includes An alternate version of The Augur's Admonishment
_Doesn't need a patch to work with Not So Fast_

[Juniper's College of Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/11915)
- [x] Load after Erratum Etc.

[Magical College of Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/1539)
- [x] Incompatible with Erratum Etc.
- [x] Use Erratum Etc. Lite instead.

[Not So Fast - Mages Guild](https://www.nexusmods.com/skyrimspecialedition/mods/5686)
- [x] Incompatible with The Augur’s Admonishment.
- [x] Use NSF-MG version instead.
[
Obscure's College of Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/20514)
- [x] Already includes Scheduled Savos
- [x] Already includes Erratum Etc.

---

#### Load Order

![image](https://user-images.githubusercontent.com/1944639/59724495-f6944900-9221-11e9-9331-24d1ee6fd168.png)

> ﻿Q: What is the intended load order?
> A: Load all plugins as high in your load order as possible.  The exception is the Not So Fast - Mages Guild version of The Augur's Admonishment, which should be loaded after Not So Fast.

**Comment by MacSplody** [comment]
@SomethingObscure Which module should win this conflict between `OCW_Obscure's_CollegeofWinterhold.esp` and `MCWT_DeadDunmerDelivery.esp`?

I'm assuming it would be `MCWT_DeadDunmerDelivery.esp`.

![image](https://user-images.githubusercontent.com/1944639/59724841-4aebf880-9223-11e9-8ccf-41745546a930.png)

**Comment by SomethingObscure** [comment]
That record shouldn't be there in OCW.  I'll have a closer look when I have time; probably Friday.

**Comment by SomethingObscure** [comment]
That record (and an edit to Tolfdir's scene marker too) have been removed in OCW 1.4.11.  Thanks for spotting it.  👍 

Edit:  Also removed from DDD as well.  The whole thing was cleaner to do using only new records.

**Comment by MacSplody** [comment]
> That record (and an edit to Tolfdir's scene marker too) have been removed in OCW 1.4.11. Thanks for spotting it. 👍
> 
> Edit: Also removed from DDD as well. The whole thing was cleaner to do using only new records.

@SomethingObscure You're welcome. I use [modgroups](https://tes5edit.github.io/docs/3-modgroups.html#s_3-1) in xEdit, it makes those kind of conflicts easier to spot.

**Comment by SomethingObscure** [comment]
[Improved College Entry](https://www.nexusmods.com/skyrimspecialedition/mods/22184) now contains some of the M.C.W.Tweaks.  

- Friendly Faralda has been copied over verbatim.
- An alternate version of Mage-Light Maintenance is included.
- An alternate version of The Augur's Admonishment, which I am told does not need a patch to work with Not So Fast - Mages Guild, is included.
- Parts of Erratum Etc. are included, but as these are all minor and identical to mine, they can both be in someone's load order and overwrite one another without issue.  

Edit: I noticed that CollegeEntry.esp is missing at least one USSEP edit (Hall of Attainment cell settings).  I'm going to investigate further and then let Parapets know.

**Comment by SomethingObscure** [comment]
I have found that [Faction Skill Requirements](https://www.nexusmods.com/skyrimspecialedition/mods/24191) has a script conflict with Dead Dunmer Delivery.  I'm going to list them as incompatible.

**Comment by SomethingObscure** [comment]
[Immersive College of Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/17004) now contains _MCWT_AWizardsWalk.esp_, so using them together would be redundant!
