### ISSUE TITLE
ELFX fixes after alternate start

### ISSUE THREAD

**Issue by Soukmancer** [loot/skyrimse#713]
https://www.nexusmods.com/skyrimspecialedition/mods/25498

ELFX fixes should load after Alternate Start to preserve it's fixes/changes ... Alternate start appears to only be carrying forward vanilla unchanged values create a false conflict.    ELFX fixes should likely be somewhere near the end of the load order. prolly next to  ELFX enhancer makes the most sense.

**Comment by MacSplody** [comment]
It can load after these without issue, it only edits a few cells so it doesn't conflict with much.

```
      - 'Alternate Start - Live Another Life.esp'
      - 'Immersive Citizens - AI Overhaul.esp'
      - 'MLU.esp'
      - 'Open Cities Skyrim.esp'
```

**Comment by MacSplody** [comment]
Those after have been added. I haven't added it to same group as ELFX enhancer,
because it would then load after all other ELFX patches.
