### ISSUE TITLE
Relationship Dialogue Overhaul after Alternate Start

### ISSUE THREAD

**Issue by Soukmancer** [loot/skyrimse#715]
As mentioned by the RDO author

"A handful of records conflict between RDO and LAL. RDO includes the changes made to these conflicting records by LAL, and therefore should be loaded after LAL so that changes from both mods are applied."

Loot currently sorts RDO before ASLAL

**Comment by MacSplody** [comment]
This has been brought up before and I don't think it's optimal for RDO to have a hard after for ASLAL.
It's only 4 records, which is easily patched or an after can be added by the user.

![image](https://user-images.githubusercontent.com/1944639/59971678-9cc0b580-9578-11e9-84ce-454c4f9fe3bf.png)

It won't break RDO to leave it before ASLAL. 

![image](https://user-images.githubusercontent.com/1944639/59971760-4fddde80-957a-11e9-8ee3-fe3f4f47c576.png)

**Comment by MacSplody** [comment]
There's also [BUVARP SE - Barely Used Vanilla Actors Recycle Project for SE](https://www.nexusmods.com/skyrimspecialedition/mods/13562) which has RDO as a master.
The order with other NPC overhauls would need to be worked out.

**Comment by Soukmancer** [comment]
I can make a patch the easily enough n put it on nexus.

**Comment by MacSplody** [comment]
> I can make a patch the easily enough n put it on nexus.

Okay, a message can be added when it's available.

I'll leave this open, the _after_ can be reviewed once I've had time to look at conflicts for modules sorting after RDO.

**Comment by MacSplody** [comment]
[WARP - World Assets Recycle Project SE](https://www.nexusmods.com/skyrimspecialedition/mods/28228)

Two conflicts with Alternate Start after WARP.

![image](https://user-images.githubusercontent.com/1944639/66273868-0cc92200-e870-11e9-8afb-9c758bae05ec.png)

![image](https://user-images.githubusercontent.com/1944639/66273883-4a2daf80-e870-11e9-8c7f-2f6b1076be0b.png)

Two cell settings are reverted if WARP is after ASLAL.
As well as removing the trigger reference & Navm changes shown above.

![image](https://user-images.githubusercontent.com/1944639/66273928-ce803280-e870-11e9-8a61-8adb8c423915.png)

![image](https://user-images.githubusercontent.com/1944639/66273934-db9d2180-e870-11e9-9fec-64901bcf8520.png)
