### ISSUE TITLE
Conflicts between RDO and Song of the Green

### ISSUE THREAD

**Issue by Xahtax** [loot/skyrimse#717]
RDO and Song of the Green have conflicts i think they could be solved if RDO is loaded after Song of the Green. 
An example of a conflict is shown in the screenshot.
![Screenshot](https://user-images.githubusercontent.com/52102338/59983182-bddae200-961c-11e9-9778-315dc15cdb95.JPG)

**Comment by MacSplody** [comment]
No conflicts if `Relationship Dialogue Overhaul.esp` is after `018Auri.esp`.
Yup looks like RDO needs to be after Song of Green.
Since you found the conflict, Do you want to add the change?

**Comment by Xahtax** [comment]
You can do that :)

**Comment by MacSplody** [comment]
Okay, it basically the same as this https://github.com/loot/skyrimse/commit/98485f1e0ae3d3104e1bf498fe0206ab9e6fcacc

That's only on a testing branch so I can remove it eaily enough.
I'll remove that one, and you can add the change in a pull request to v0.14.

**Comment by Xahtax** [comment]
Ok, i'll try it :)
