### ISSUE TITLE
Guard Armor Replacer should be sorted higher

### ISSUE THREAD

**Issue by Soukmancer** [loot/skyrimse#721]
[Guard Armor Replacer](https://www.nexusmods.com/skyrimspecialedition/mods/22671)

I tried the minimalist patch as well for compatibility sake but there were still issues.  Where LOOT sorts it it will conflict with specific outfits Immersive Armors and Cutting Room Floor assigns to some quest NPC's.  So it should be sorted above

It also seems to have cell entries containing vanilla data with no changes.  Because of this it introduces a false conflict and reverts cell changes made back to vanilla made by mods such as Unique Treasures of Skryim, AI overhaul, sounds of skyrim so it should be sorted above.

Also a cell conflict with Palaces and castles enhanced, not sure what should win this one though.

**Comment by MacSplody** [comment]
Downloads lists it as having to be after the bashed patch, that seems a bit extreme.
In any case it requires some testing in bash to see why it would need to be after.

![image](https://user-images.githubusercontent.com/1944639/63055749-83841780-bede-11e9-85f9-447672a36938.png)

**Comment by MacSplody** [comment]
Seems to work fine with bash.
Though it may need these tags.

```yaml
  - name: 'Guards_Armor_Replacer.esp'
    tag:
      - Delev
      - Graphics
      - Invent
      - Relev
```

**Comment by Soukmancer** [comment]
One thing to note is I also use the minimal version, I'll likely just be making a patch to resolve conflicts. this one is very minor.  the minimal and full version have the same esp name and it's possible they would need to be sorted manually depending on what your using in ones load order.

**Comment by MacSplody** [comment]
@Soukmancer I'll close this for now, if it needs any rule changes it can be opened again.
