### ISSUE TITLE
Alchemy Potions and Food Adjustments after SkyTest

### ISSUE THREAD

**Issue by Soukmancer** [loot/skyrimse#725]
[Alchemy Potions and Food Adjustments](https://www.nexusmods.com/skyrimspecialedition/mods/5877)

This should be sorted after SkyTest to avoid the need of a patch. LOOT currently sorts it before.. for some reason SkyTest changes the effect of red Apple, seared slaughterfish and mammoth meat, which causes the conflict..

**Comment by MacSplody** [comment]
Yeah I think you're right, default sorting is placing `SkyTEST-RealisticAnimals&Predators.esp` after `AlchemyAdjustments.esp`. That keyword added below by SkyTest is only referenced by itself, so not sure why they would add that change.

![image](https://user-images.githubusercontent.com/1944639/60459503-49fe9200-9c39-11e9-9748-9730f85cea43.png)

A rule to sort `AlchemyAdjustments.esp` after `SkyTEST-RealisticAnimals&Predators.esp` should be added.
