### ISSUE TITLE
Dwemer Spectres before Immersive Armor and HMB Cathedral

### ISSUE THREAD

**Issue by Soukmancer** [loot/skyrimse#726]
[Dwemer Spectres Special Edition](https://www.nexusmods.com/skyrimspecialedition/mods/8016)

Possibly the same assets... both are in BSA though.
But it does containing conflicting/overwriting assets with [Humans Mer and Beastfolk - The Cathedral Concept](https://www.nexusmods.com/skyrimspecialedition/mods/24174) and [Immersive Armors](https://www.nexusmods.com/skyrimspecialedition/mods/3479) to be on the safe side, I'd opt to have it loaded above both in the load order.

**Comment by MacSplody** [comment]
> Possibly the same assets... both are in BSA though.

The assets would need to be extracted and compared. It would help to know what types of assets are conflicting, Is it just textures and meshes?

**Comment by Soukmancer** [comment]
I believe it is just vanilla assets, according to the author.

"The auto-archiver picked up stuff that was never modified, that's all."

although immersive armor and this mod are likely using the same shared assets.  I set a rule in LOOT though to manage it but here is an example.

http://icecream.me/uploads/262e1c0700bb983c9b8cc19b40211ea2.png

I do know HMB had a similar issue as it also used an auto archive and included some vanilla assets as well.  It's tricky to know with HMB which are vanilla and which are custom assets.

**Comment by MacSplody** [comment]
Assets look the same. So I don't think load order matters.

`1stpersondwarvenarmor_0.nif`

Immersive Armours
![image](https://user-images.githubusercontent.com/1944639/68015951-564c3780-fc8b-11e9-93d8-8ac8550ee18f.png)

Dwemer Spectres
![image](https://user-images.githubusercontent.com/1944639/68016043-901d3e00-fc8b-11e9-94ed-82c710a90f8a.png)

`dwarvenarmor_0.nif`

Immersive Armours
![image](https://user-images.githubusercontent.com/1944639/68016363-56006c00-fc8c-11e9-84da-47ccdfa639d7.png)


Dwemer Spectres
![image](https://user-images.githubusercontent.com/1944639/68016280-27829100-fc8c-11e9-83b7-d835e82ca4c7.png)

---

`malehead.nif`

Dwemer Spectres
![image](https://user-images.githubusercontent.com/1944639/68019594-22294480-fc94-11e9-8f1b-79367e744d79.png)

Humans Mer and Beastfolk - The Cathedral Concept
![image](https://user-images.githubusercontent.com/1944639/68019680-64528600-fc94-11e9-8a83-fa2e2f00dc02.png)

**Comment by MacSplody** [comment]
@Soukmancer Closing as the assets look the same.
