### ISSUE TITLE
Bruma and Other Patches for Convenient Horses 2.0 - New file names

### ISSUE THREAD

**Issue by DFelten** [loot/skyrimse#729]
The patches from "[Bruma and Other Patches for Convenient Horses](https://www.nexusmods.com/skyrimspecialedition/mods/13812)" got new file names.  So currently, LOOT does not recognize them anymore.

> I had to rename half of the files to have them working with the update, so I decided to rename them all, they were a bit on the long side. This means that LOOT could nag about missing patches, but you know they're not missing, just ignore the warnings.

**Comment by MacSplody** [comment]
@DFelten This should be fixed now for the new plugin names.
