### ISSUE TITLE
2 of my patches load order: minor

### ISSUE THREAD

**Issue by Soukmancer** [loot/skyrimse#735]
Hi,

Got an easy one;

I have two patches, LOOT sorts em side by side but they should be in the opposite order.

Skyrim Revamped Releveled should be first https://www.nexusmods.com/skyrimspecialedition/mods/27201/

Mighty Bellyache's Dragons should be after.
https://www.nexusmods.com/skyrimspecialedition/mods/27131

Currently the opposite happens, and it creates 1 minor conflict since both patches make adjustments to the the Undead Dragon in Labrynthian.  But Bellyache's is the preferred winner as it is a dragon mod.

Thanks

**Comment by MacSplody** [comment]
This is the order I get with no rule changes.

![image](https://user-images.githubusercontent.com/1944639/62414845-e3dea380-b618-11e9-9438-d8bd0a84e7a0.png)

Which gives this conflict

![image](https://user-images.githubusercontent.com/1944639/62414851-04a6f900-b619-11e9-9529-370b7f661555.png)

Something else in your load order must be affecting default sorting.
It's pretty minor, but I can add a rule to make sure `MightifiedBellyachesDragons.esp` always loads after `RevampedReleveled.esp` and `Skyrim Revamped - Complete Enemy Overhaul.esp`.

**Comment by MacSplody** [comment]
@Soukmancer Done in https://github.com/loot/skyrimse/commit/ec715bc8618471a1766699c1c6a2e0f15c4019e7
