### ISSUE TITLE
ski_playerloadgamealias.pex exists in thunderchild bsa too is it safe?

### ISSUE THREAD

**Issue by parsafaramarzi** [loot/skyrimse#736]
im just assuming that its not safe because i was warned about sofia mod by loot aswell can someone confirm it for se ? also loot will recognize ski_playerloadgamealias.pex as a part of sofia follower mod even if another mod contains it

**Comment by MacSplody** [comment]
@parsafaramarzi Yeah you're right, Thunderchild does include a copy of the script.

![image](https://user-images.githubusercontent.com/1944639/62414439-1b4a5180-b613-11e9-9f58-8705bad9f0ff.png)

You have two options, make sure SkyUI sorts after `Thunderchild - Epic Shout Package.esp`
or
You'll need to exract the `Thunderchild - Epic Shout Package.bsa`, delete the `.bsa` and then remove the `ski_playerloadgamealias.pex` from the scripts folder.

**Comment by parsafaramarzi** [comment]
yea thats exactly what i did thanks man
