### ISSUE TITLE
Plugin name changes for Immersive College NPCs

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#737]
Here's a summary of the recent updates:

[Immersive College NPCs](https://www.nexusmods.com/skyrimspecialedition/mods/9252): In version 1.1 _CollegeStudents.esp_ has been renamed to **ICNs_ImmersiveCollegeNPCs.esp** following conversion to ESP-FE.

[Obscure's College of Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/20514): The patch for ICNs 1.1 has been renamed from _OCW_ICNs_FEPatch.esp_ to **OCW_ICNs_OE_FEPatch.esp**

[Misc. College of Winterhold Tweaks](https://www.nexusmods.com/skyrimspecialedition/mods/22653): The ICNs 1.1 add-on for A College Coup has been renamed from _MCWT_ACollegeCoup_ICNs.esp_ to **MCWT_ACollegeCoup_ICNs_OE.esp**

_Originally posted by @SomethingObscure in https://github.com/loot/skyrimse/issues/517#issuecomment-517145364_

**Comment by SomethingObscure** [comment]
I've started the ICNs [load order recommendations list](https://www.nexusmods.com/skyrimspecialedition/articles/1295).  The mod is pretty light so as expected there's not much to report.  As per usual I'll keep both this thread and that article up to date with new findings, if any.
