### ISSUE TITLE
Inigo - Conflicts with Caranthir Tower Reborn

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#742]
Reported by [aristotle99](https://www.afkmods.com/index.php?/profile/10250-aristotle99/) on the [forum thread](https://www.afkmods.com/index.php?/topic/5042-relz-loot-load-order-optimisation-tool/&do=findComment&comment=175607)

>  LOOT loads Inigo above Caranthir Tower Reborn, but I think this is wrong.
> 
> cdcooley writes: "I've played through Inigo's mini-quest and done the tower startup quest repeatedly to check for critical problems. Neither mod actually blocks progression of the quests in the other in any way I could detect. Inigo can get to the cabin and NPCs can enter and leave the tower, I could still find all 8 of Langley's eggs and retrieve all of Darkfox128's deviously hidden objects around the tower (after cheating to find where they are hidden).
> 
> The only problems I found are graphical glitches which are minimized if you load Inigo after Caranthir Tower Reborn. When I loaded them in that order the only thing that stood out (literally) was one of Langley's wooden posts embedded in the tower's entrance structure. Other than the odd visual effect of the post (and its flag fluttering in and out of the structure's wall once it is raised) there were no problems I could identify.
> 
> If there's something I've missed I really want to know. General comments about needing a patch without specifying why is not going to help make it happen in a timely fashion."
> 
> Here is the discussion:
> 
> https://forums.nexusmods.com/index.php?/topic/4749095-caranthir-tower-reborn-patches/page-2

**Comment by Xahtax** [comment]
There is an issue with both mods wich would need a patch. It's this conflict, I think.  [Screenshot of the conflict](https://cdn.discordapp.com/attachments/496196499890241546/609853199029108737/unknown.png)
If Inigo is loaded after CT there will be less navmesh issues. And another Location conflict will be solved without needing a patch. When I asked about this issue on the xEdit server a few weeks ago, someone told me that it might be better to complete Inigo's quest, before building the tower.
There is a patch for both mods on the LE patch page of CT, I'm not sure, if it would solve this conflict though.

**Comment by MacSplody** [comment]
> There is an issue with both mods wich would need a patch. It's this conflict, I think. [Screenshot of the conflict](https://cdn.discordapp.com/attachments/496196499890241546/609853199029108737/unknown.png)

Yeah you're right, thanks.

>If Inigo is loaded after CT there will be less navmesh issues. And another Location conflict will be solved without needing a patch.

That depends on what Caranthir Tower Reborn location is used for I guess.

>When I asked about this issue on the xEdit server a few weeks ago, someone told me that it might be better to complete Inigo's quest, before building the tower.

Would it still work with the same order, Inigo after CTR? Or would you need to reverse the order?

> There is a patch for both mods on the LE patch page of CT,

The one listed [here](https://www.nexusmods.com/skyrim/mods/77806) requires Enhanced Landscapes & Inigo, so that won't help.

It's probably best to inform the authors of both mods about the conflict, and hopefully a patch will be released.

**Comment by Xahtax** [comment]
Sorry, just saw that now.
I think that the location is used for fast travel
![CTLocation](https://user-images.githubusercontent.com/52102338/63656664-1eaaa600-c797-11e9-94ac-df4b34224f0a.PNG)
That's the other location. I don't know what it does.
![CTLocation2](https://user-images.githubusercontent.com/52102338/63656668-44d04600-c797-11e9-9f97-2271baa78069.PNG)

> Would it still work with the same order, Inigo after CTR? Or would you need to reverse the order?

I don't know. Inigo has to be loaded after CTR, because of the location conflict, I guess. Inigo uses the location for scenes and other things. I'm not sure if it would break, if CTR overwrites it.

> It's probably best to inform the authors of both mods about the conflict, and hopefully a patch will be released.

Did someone inform the authors already? IIRC Darkfox127 won't provide patches.

Note: I've used Inigo and CTR without a patch on LE and didn't encounter any issues. Maybe it's not that bad. I'm not sure though.

**Comment by MacSplody** [comment]
The CTR location is only used in two locations. Both of these are reverted by Inigo, if you're patching or bashing then it's not much of an issue.

![image](https://user-images.githubusercontent.com/1944639/63657283-cfb14080-c797-11e9-8359-014dc9912389.png)

![image](https://user-images.githubusercontent.com/1944639/63657302-1b63ea00-c798-11e9-859d-4202da2c637f.png)

But that location is linked to the CTR tower ascention magic effect. Which is used by the spell to reveal the tower.

![image](https://user-images.githubusercontent.com/1944639/63657332-6847c080-c798-11e9-80b6-f4626ad3c749.png)

![image](https://user-images.githubusercontent.com/1944639/63657355-c70d3a00-c798-11e9-82c2-92bac59d71d0.png)

![image](https://user-images.githubusercontent.com/1944639/63657369-ec9a4380-c798-11e9-888f-be1a11f37cfe.png)

So based on that, I think it should be left as it is. But a message about there compatibility could be added.
