### ISSUE TITLE
Harvest Overhaul Redone now integrates Flora Respawn Fix compatibility

### ISSUE THREAD

**Issue by SethWilliamson** [loot/skyrimse#750]
LOOT currently (Masterlist dated 2019-08-22) posts a message that a patch is required for [Harvest Overhaul Redone](https://www.nexusmods.com/skyrimspecialedition/mods/2398) and [Flora Respawn Fix](https://www.nexusmods.com/skyrimspecialedition/mods/13186). 

This patch has been removed from the nexus:
https://www.nexusmods.com/skyrimspecialedition/mods/14125

Harvest Overhaul Redone now has the option during installation to install a version that has everything forwarded from Respawn Fix. 

![FOMOD Install Screenshot](https://i.ibb.co/h7zrQHb/Harvest-Overhaul.jpg)

The patch is no longer necessary. Flora Respawn Fix becomes a dependancy.

**Comment by MacSplody** [comment]
@SethWilliamson thanks, that message is removed now.
