### ISSUE TITLE
The People of Skyrim 2 - Open Cities support

### ISSUE THREAD

**Issue by Nesbit098** [loot/skyrimse#758]
TPOS 2
https://www.nexusmods.com/skyrimspecialedition/mods/22392?tab=files

TPOS 2 FOMOD INSTALLER V9.2.8 

FILE FULL OPEN CITIES 
is NOW Compatible with OCS PC ONLY.

The mod Open Cities should be ABOVE TPOS 2 Main File 1 OC Version in the load order. 
Any TPOS 2 version below V9.2.8 is NOT compatible with Open Cities.

I realized after upload the main files carry the same name identification. However the header of the esp does state which version is for OCS in the installer. If I need to adapt the name for the OCS version please advise and I will do so.

Many Thanks & Regards
Nesbit.

**Comment by MacSplody** [comment]
As long as the mods version is listed in the plugin description, then the `.esp` name doesn't need to change.

**Comment by Nesbit098** [comment]
Thanks Cpt...

**Comment by CptMcSplody** [comment]
@Nesbit098 Yeah that version won't work, at least not without an after and the user patching the two plugins. You'll need to add Open cities as a master and carry forward all of its changes to cell settings. Otherwise there will be issues like NPCs falling through the terrain.
![image](https://user-images.githubusercontent.com/1944639/64349522-06385800-cfef-11e9-9e80-81186969bfe0.png)

**Comment by MacSplody** [comment]
@Nesbit098 Yeah that version won't work, at least not without an after and the user patching the two plugins. You'll need to add Open cities as a master and carry forward all of its changes to cell settings. You would be better off changing the name as well. Mainly because there will be no doubt over which version is being used if a user has any issues.

![image](https://user-images.githubusercontent.com/1944639/64349522-06385800-cfef-11e9-9e80-81186969bfe0.png)

**Comment by Nesbit098** [comment]
It works fine and has been tested by me...The are no cities altered mate....I can changed the name of the fine as stated but it works fine and no patches are required for there is not content involved...FULLY TESTED


Sent from Mail for Windows 10

**Comment by MacSplody** [comment]
> It works fine and has been tested by me...The are no cities altered mate....I can changed the name of the fine as stated but it works fine and no patches are required for there is not content involved...FULLY TESTED 

There are edits to city exteriors which OCS also changes.
The CELL and WRLD settings are important for Open Cities.

![image](https://user-images.githubusercontent.com/1944639/64356736-47cf0000-cffb-11e9-8a25-4221582c5642.png)

![image](https://user-images.githubusercontent.com/1944639/64357572-d2fcc580-cffc-11e9-9859-edde70a33e77.png)

> Open Cities
> The mod Open Cities should be ABOVE TPOS 2 Main File 1 in your load order. For V9.2.8 and above only...Any TPOS 2 version below is NOT compatible with Open Cities.

Is that?
`tpos_complete02_RTCWG.esp`
`Open Cities Skyrim.esp`
or 
`Open Cities Skyrim.esp`
`tpos_complete02_RTCWG.esp`

If it's the second one it needs to have a patch or have the Cell and WRLD settings integrated in to TPOS2 OCS.

**Comment by Nesbit098** [comment]
OK sorry back trouble stop me dead for the best part...along with family stuff..All a bit messy...I placed the wrong file in the installer, not the complete edited file for OC. So ignore this request I will re upload corrections soon for the next version and contact you then OK CPT..

**Comment by Nesbit098** [comment]
OK Cpt,
The main TPOS file for OC has been check..and is correct... the one I did not uploaded with V9.2.8...But so there can be no further concerns I have made a small patch for Markarth exterior a small adjustment...
I will contact when the new file is uploaded

Regards Nesbit

**Comment by Nesbit098** [comment]
OK Cpt, I have bought all references forward for OC in the patch and re navmesh a little of Riften as my file is after OC ...all is correct and I will upload tonight.
If you look or investigate any conflicts are resolved with the patch. 

The TPOS FILE is still named the same but in the header it is clear what version it is and for use with OC.
TPOS2 SE Full Version 9.2.9  Open Cities Version.

So the house is in order....I am uploading later tonight and will let you know when I am done..

LOAD ORDER

Open Cities Skyrim
tpos_complete02_RTCWG
tpos_OCpatch

**Comment by MacSplody** [comment]
Okay thanks.
I know it might seem a bit much, but there have been issues with other mods OCS versions in the past. I just want to avoid any similar problems

**Comment by Nesbit098** [comment]
not at all you are right to be correct....

**Comment by Nesbit098** [comment]
OK Capt I have posted the live update file and just rounding off a couple of small issues. Road travelers to cities... the xmarkers have been removed and packages never got all the npc's two left..So once I am 100% I will contact you with the version number for OC and the patch to OK...Thanks for your time.

**Comment by Nesbit098** [comment]
OK Cpt,
Done... No references to the cities in the TPOS 2 FULL V9.3.0 file under UPDATES at present on the Nexus page.....and the patch carries all the references bought forward, and required navmesh changes..Tested and confirmed...All good...

LOAD ORDER
Open Cities Skyrim
tpos_complete02_RTCWG ( Header Info TPOS2 SE Full Version 9.3.0 Open Cities Version. )
tpos_OCpatch
