### ISSUE TITLE
Cyclic Interaction 1nivWICSkyCloaksPatch.esp/ aMidianBorn_ContentAddon.esp/ CCOR

### ISSUE THREAD

**Issue by Vachnic** [loot/skyrimse#766]
Never posted anything here before, but as of today I suddenly get this cyclic interaction message when running LOOT. I have used run LOOT many times before and never has this pop up before. 
I hope this is the correct place to post this.

Cyclic interaction detected between "1nivWICSkyCloaksPatch.esp" and "aMidianBorn_ContentAddon.esp":

1nivWICSkyCloaksPatch.esp
 [Group]
Complete Crafting Overhaul_Remade.esp
 [Master]
aMidianBorn_ContentAddon.esp
 [Group]
1nivWICSkyCloaksPatch.esp

**Comment by MacSplody** [comment]
> I have used run LOOT many times before and never has this pop up before.

The group for `Complete Crafting Overhaul_Remade.esp` was changed to place it after
`mlu.esp` by default.

> Complete Crafting Overhaul_Remade.esp
>  [Master]
> aMidianBorn_ContentAddon.esp

Your copy of `aMidianBorn_ContentAddon.esp` has been modified to have `Complete Crafting Overhaul_Remade.esp` as a master.
That's causing the sorting error due to the groups between `aMidianBorn_ContentAddon.esp`
and `Complete Crafting Overhaul_Remade.esp`.

Did you add CCOR as a master? 
if you haven't modified them yourself, can you provide a source url for your plugins?

**Comment by Vachnic** [comment]
Hi Cpt,
Thanks for the swift reply :) I didn't add CCOR as a master to Contentaddon. I converted it myself then downloaded a patch/ esp replacement from "Lost of T'Skyrim" as was suggested by an install guide I was following. I just checked and the patch adds CCOR and ACE (Armor and Clothing Extension) as masters.
The link to the patch is https://www.nexusmods.com/skyrimspecialedition/mods/9951?tab=files (second file from top)

**Comment by MacSplody** [comment]
> The link to the patch is https://www.nexusmods.com/skyrimspecialedition/mods/9951?tab=files (second file from top)

Okay thanks.

To solve the sorting error change `aMidianBorn_ContentAddon.esp` group to _default_ in LOOT.

**Comment by MacSplody** [comment]
Also @Vachnic Winter is coming is included in CCOR.
You don't need the `1nivWICCloaks.esp`.
https://forums.nexusmods.com/index.php?/topic/2672844-ccor-supported-mods/?p=24503074

**Comment by Vachnic** [comment]
The sorting works now when set to default. Thanks.

As for Winter is Coming, does that also count for the SSE version? 
CCOR itself hasn't been officially ported to SSE (yet). 
How I use it is: 
Original CCOR for LE (converted), 
CCOR SSE updated (also from Lost of T'Skyrim, see link before = esp replacement) and 
CCOR Script fixes (https://mega.nz/#!TMw11SjA!LUFD6zRG8l0MrxbfM-pxQcLCpoHjRslpo0C8EBB1p8w)
When I have a moment I will look into it myself, but maybe you know off hand.

**Comment by MacSplody** [comment]
It should still be the included unless something major changed in the T'Skyrim update.

**Comment by Vachnic** [comment]
OK, then they are still included. the patches are just the esp and some scripts.

Thanks so much for your help!

**Comment by MacSplody** [comment]
You're welcome.
