### ISSUE TITLE
Cyclic Interaction between two mods

### ISSUE THREAD

**Issue by JustinM358** [loot/skyrimse#767]
Hi, I updated to the latest version of LOOT, and when I tried sorting my load order, I got this error message:

> Cyclic interaction detected between "Cutting Room Floor.esp" and "Enhanced Landscapes.esp":
> 
> Cutting Room Floor.esp
>  [Masterlist Load After]
> Guard Dialogue Overhaul.esp
>  [Group]
> fallentreebridgesSSE.esp
>  [Group]
> Enhanced Landscapes.esp
>  [Masterlist Load After]
> Cutting Room Floor.esp

How would I go about fixing this to sort my mods?

**Comment by MacSplody** [comment]
> Hi, I updated to the latest version of LOOT, and when I tried sorting my load order, I got this error message:
> 
> > Cyclic interaction detected between "Cutting Room Floor.esp" and "Enhanced Landscapes.esp":
> > Cutting Room Floor.esp
> >  [Masterlist Load After]
> > Guard Dialogue Overhaul.esp
> >  [Group]
> > fallentreebridgesSSE.esp
> >  [Group]
> > Enhanced Landscapes.esp
> >  [Masterlist Load After]
> > Cutting Room Floor.esp
> 
> How would I go about fixing this to sort my mods?

I just pushed a fix for this.
@JustinM358 Can you update your masterlist?

**Comment by JustinM358** [comment]
Yes, it is fixed now. Thank you!
