### ISSUE TITLE
Paper World Map

### ISSUE THREAD

**Issue by whirledwarotter** [loot/skyrimse#768]
It needs to be loaded last as in last of anything in the load order since it doesn't work at all if you load it anywhere but last. I rarely use loot because of it sorts it in the middle of the load order, which is annoying.

**Comment by MacSplody** [comment]
> It needs to be loaded last as in last of anything in the load order since it doesn't work at all if you load it anywhere but last.
> I rarely use loot because of it sorts it in the middle of the load order, which is annoying.

It doesn't place it in the middle. It's loading late.
The only modules that will load after it are:

`NoGrassINCities.esp`
`WACCF_BashedPatchLvlListFix.esp`
`EconomyOverhaulandScarcityPatch.esp`
`Scarcity SE - Less Loot Mod.esp`
`Sum_WACCF_Patch.esp`
Any dynamic patches like `Bashed Patch, 0.esp`
`Dawnguard Map Markers.esp`
`DynDOLOD.esp`

If your not happy with its placement, then add a user rule to place it in a later group.
