### ISSUE TITLE
Cyclic interaction detected between TFoS Trees of Solitude SSE.esp/ DynDOLOD.esm

### ISSUE THREAD

**Issue by Vachnic** [loot/skyrimse#769]
So, I got me another one... Trying out a new tree/flora overhaul called "Myrkvior - The Flora Of Skyrim - Trees SSE". One of the add-ons to that is giving me this cyclic message:

Cyclic interaction detected between "TFoS Trees of Solitude SSE.esp" and "DynDOLOD.esm":

TFoS Trees of Solitude SSE.esp
 [Master]
DynDOLOD.esm
 [Master Flag]
TFoS Trees of Solitude SSE.esp

The overhaul can be found here: https://www.nexusmods.com/skyrimspecialedition/mods/28406?tab=files.
The add-on in question is at the bottom in the miscellaneous files. it is flagged as an ESL.

**Comment by MacSplody** [comment]
> TFoS Trees of Solitude SSE.esp
>  [Master]
> DynDOLOD.esm
>  [Master Flag]
> TFoS Trees of Solitude SSE.esp

Not sure why an `.esp` would be marked as a master for an `.esm`.
It's not something LOOT will be able to sort.
I'll test it out in DynDOLOD anyhow.

**Comment by MacSplody** [comment]
Okay I've tested with that file and can't replicate that issue.

![image](https://user-images.githubusercontent.com/1944639/64493852-693f1e80-d27d-11e9-91f1-0aa925afd680.png)

**Comment by Vachnic** [comment]
In the meantime I re-ran DynDOLOD thinking that maybe I did something wrong. But when I ran LOOT after again, it still gives me the error. 

So I checked the masters added to DynDOLOD.esm with SSE Edit and it shows:
![Cyclic error](https://user-images.githubusercontent.com/54997222/64493963-313cd900-d287-11e9-8a5f-7647a60ddc64.jpg)

So in short, all the add-ons that add trees to cities gets added as masters to DynDOLOD.esm for me?
It... is kinda baffling.
I am going to try to remove the "masters" with the CK and see if that does anything.

**Comment by Vachnic** [comment]
Yeah... removing them as masters didn't work so well. I was able to remove them, but now the game CTDs as soon as I want to go outside when DynDoLod should kick in.
I also haven't seen any similar messages as my issue on the mod page, so I guess it is me that is doing something wrong.  I will just keep changing things around and see what happens.
Thanks for looking into it :)

**Comment by Vachnic** [comment]
I did some more digging and I found the issue... turns out it was (apparently) an issue with DynDOLOD itself (see forum post: https://forum.step-project.com/topic/14248-dyndolodesm-includes-non-esm-flagged-esp-as-masters/). Sheson uploaded a new version and apparently it is now fixed. 
I am generating new files as we speak (again... 5th time today yay). But I guess we can  say this problem is solved.

**Comment by MacSplody** [comment]
Okay thanks for letting us know.

**Comment by Vachnic** [comment]
And I can now confirm that updating DynDoLod resources and DynDolod to the latest version (now 2.70 and 2.71 respectively) fixes this issue.
