### ISSUE TITLE
Mod sorting change request

### ISSUE THREAD

**Issue by Thijxx** [loot/skyrimse#791]
The mod **[Tinker's Forge - Smithing Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/22595)** ESP file `PathOfMight.esp` should be sorted below **[Ordinator - Perks of Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/1137)** ESP file `Ordinator - Perks of SDkyrim.esp`.

**Comment by MacSplody** [comment]
I'll test these rules and see which can be added as well.

Sort after:
- `Vokrii - Minimalistic Perks of Skyrim.esp` [Vokrii - Minimalistic Perks of Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/26176)

Incompatible with:
- `PerkusMaximus_Warrior.esp` [T3nd0's Perkus Maximus SSE](https://www.nexusmods.com/skyrimspecialedition/mods/11044).
- `Smithing Perks Overhaul SE.esp` [Smithing Perks Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/19246
)
- `Complete Crafting Overhaul_Remade.esp` [Complete Crafting Overhaul Remade](https://www.nexusmods.com/skyrim/mods/49791)

**Comment by MacSplody** [comment]
`Complete Crafting Overhaul_Remade.esp`

![image](https://user-images.githubusercontent.com/1944639/64992779-8783ca80-d8cc-11e9-9ce7-6c11a0cd19d6.png)

![image](https://user-images.githubusercontent.com/1944639/64992971-eba68e80-d8cc-11e9-9c29-c1f255ea5737.png)

Some conflicts, it would need a patch.

**Comment by MacSplody** [comment]
`Weapons Armor Clothing & Clutter Fixes.esp` [Weapons Armor Clothing and Clutter Fixes](https://www.nexusmods.com/skyrimspecialedition/mods/18994
) would need a patch as well.

![image](https://user-images.githubusercontent.com/1944639/64993842-fcf09a80-d8ce-11e9-8853-3c2787913ad8.png)

**Comment by MacSplody** [comment]
Done in https://github.com/loot/skyrimse/commit/1d30b01612831bae6b633d0ccc022b35521b7755
