### ISSUE TITLE
Vokriinator - Choice Cuts sorting issue

### ISSUE THREAD

**Issue by xryanv** [loot/skyrimse#870]
When using the Vokriinator Plus 2.7 version of the mod off the nexus page https://www.nexusmods.com/skyrimspecialedition/mods/26702?tab=files

The author states that the following is the correct load order:

PathofSorcery.esp
Vokrii - Minimalisitic Perks of Skyrim.esp
Ordinator - Perks of Skyrim.esp

However Loot sorts them in the order: 

Vokrii - Minimalisitic Perks of Skyrim.esp
Ordinator - Perks of Skyrim.esp
PathofSorcery.esp

Resulting in a CTD on start for me, within the following load order:

MysticismMagic.esp
Elemental Destruction.esp
Vokrii - Minimalistic Perks of Skyrim.esp
Ordinator - Perks of Skyrim.esp
PathOfSorcery.esp
Vokriinator.esp
Vokriinator Plus - EDM patch.esp
Vokriinator Plus - Mysticism patch.esp
SpellsRequirePerks - Ordinator.esp

Moving PathOfSorcery.esp to before Vokrii - Minimalistic Perks of Skyrim.esp corrects the issue,
this is repeatable.

**Comment by MacSplody** [comment]
> However Loot sorts them in the order:
> Vokrii - Minimalisitic Perks of Skyrim.esp
> Ordinator - Perks of Skyrim.esp
> PathofSorcery.esp

That is the correct order, from [Path of Sorcery - Magic Perk Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/6660) description.

> Ordinator - Compatible! Load Path of Sorcery AFTER Ordinator. (This will replace the Ordinator magic perk trees with the perk trees from Path of Sorcery, along with some magi effects)

![image](https://user-images.githubusercontent.com/1944639/67155913-8e5c8d80-f30f-11e9-8f46-79e8dc49a16a.png)

> 
> The author states that the following is the correct load order:
> 
> PathofSorcery.esp
> Vokrii - Minimalisitic Perks of Skyrim.esp
> Ordinator - Perks of Skyrim.esp

When using Vokriinator, and that's fine, a condition can be added to allow `PathofSorcery.esp`
to sort before `Vokrii - Minimalisitic Perks of Skyrim.esp` and `Ordinator - Perks of Skyrim.esp` if `Vokriinator.esp` is present.

**Comment by MacSplody** [comment]
Done in https://github.com/loot/skyrimse/commit/df8514c3268400d6de73e2a6315cec7606e447fe.
Thanks for reporting it @xryanv
