### ISSUE TITLE
LAL and the Brotherhood of Old

### ISSUE THREAD

**Issue by Xahtax** [loot/skyrimse#875]
If you use the Thalmor start with LAL and [the Brotherhood of Old](https://www.nexusmods.com/skyrimspecialedition/mods/15322), you can't leave the embassy, because TBO adds two (?) doors and locks one of them with an apprentice lock. Changing the LO, does not solve this. 
You can open one of the doors, they'll clip through each other and you're stuck in the embassy.

What should be done about this? Can this issue be ignored? Saying that both mods don't work together would be a bit too much, since it's just one start.

Sorry if it's wrong to add the issue here.

I got also told that Loot sorts TBO after LAL (when using Lexy's LotD guide), is that correct? 
![unknown2](https://user-images.githubusercontent.com/52102338/67609435-03efb000-f78d-11e9-9741-ccf092a2a691.png)
![unknown1](https://user-images.githubusercontent.com/52102338/67609437-04884680-f78d-11e9-897d-a7b7ac9cd6cb.png)
![grafik](https://user-images.githubusercontent.com/52102338/67610010-3b139080-f790-11e9-8e7e-7f043ab8bc93.png)
![grafik](https://user-images.githubusercontent.com/52102338/67610017-423a9e80-f790-11e9-99ee-c3bb69f9adad.png)

**Comment by MacSplody** [comment]
> I got also told that Loot sorts TBO after LAL (when using Lexy's LotD guide), is that correct?

If they're using `Immersive Citizens - AI Overhaul.esp` then yes.

```yaml
  - name: 'The Brotherhood of Old.esp'
    after:
      - 'Immersive Citizens - AI Overhaul.esp'
      - 'SkyrimSewers.esp'
```

> What should be done about this? Can this issue be ignored? Saying that both mods don't work together would be a bit too much, since it's just one start.

A message could be added about that start choice.

**Comment by Xahtax** [comment]
Yes, that would be a good idea.

**Comment by MacSplody** [comment]
@Xahtax I sent the Brotherhood of Old mod author a patch which should resolve the conflict.

**Comment by MacSplody** [comment]
I received permission from TBoO author TomTesoro to release a patch.
![image](https://user-images.githubusercontent.com/1944639/69375174-99ecfc80-0c9f-11ea-8a27-73f16ec24101.png)

**Comment by Xahtax** [comment]
Thank you for looking into it :)
