### ISSUE TITLE
Cyclic interaction error involving Immersive Citizens and Live Another Life

### ISSUE THREAD

**Issue by Ortham** [loot/skyrimse#89]
Reported by @ArtaiosGreybark in PR #82:

>Load ICAO After LAL
> Failing that will cause a cyclic interaction between "Bells of Skyrim - ICAIO Patch.esp" and "Alternate Start - Live Another Life.esp". Back cycle: Alternate Start - Live Another Life.esp, Alternate Start LAL TKAA Patch.esp, Immersive Citizens - AI Overhaul.esp, Bells of Skyrim - ICAIO Patch.esp as per master list (no user meta data!).
>
> LAL edits seem to also have been integrated with ICAO since 0.39a: https://www.nexusmods.com/skyrimspecialedition/mods/173?tab=posts

This probably has the same root cause as loot/loot-api#21. Adding `after` metadata so ICAIO loads after LAL fixes the issue, but it may be better to also/instead change ICAIO's group.

**Comment by Ortham** [comment]
This should now be fixed in fcb3e7a3c9da82c74d5a4081367af05f8f174a21. @ArtaiosGreybark, can you verify? @Silarn, does this fix your issue too?

**Comment by Graybark** [comment]
Yes, that fixes it. Thanks! Any ideas for the group?

**Comment by Ortham** [comment]
I kept the group but now no other groups load after it, and it just loads after the `default` group.
