### ISSUE TITLE
Dirty plugins

### ISSUE THREAD

**Issue by Soukmancer** [loot/skyrimse#902]
- [x] `AdalvaldsRetreatXBoxPC.esp` https://www.nexusmods.com/skyrimspecialedition/mods/18935
- [x] `AltStartRaceMenuActivator.esp` https://www.nexusmods.com/skyrimspecialedition/mods/22683
- [x] `Artifacts.esp` https://www.nexusmods.com/skyrimspecialedition/mods/2431
- [x] `BetterTreasuryHouse.esp` https://www.nexusmods.com/skyrimspecialedition/mods/2485
- [x] `BreezehomeBasement.esp` https://www.nexusmods.com/skyrimspecialedition/mods/3569
- [x] `Caveoftheforgotten.esp` https://www.nexusmods.com/skyrimspecialedition/mods/13499
- [x] `Civil War Aftermath.esp` https://www.nexusmods.com/skyrimspecialedition/mods/3484
- [x] `CollegeEntry.esp` https://www.nexusmods.com/skyrimspecialedition/mods/22184
- [x] `Crossroads Inn.esp` https://www.nexusmods.com/skyrimspecialedition/mods/1406
- [x] `Diversity - A Character Overhaul.esp` https://www.nexusmods.com/skyrimspecialedition/mods/5291
- [x] `DwemerSpectresLegendary.esp` https://www.nexusmods.com/skyrimspecialedition/mods/8016
- [x] `EasierRidersDungeonPackSSE.esp` https://www.nexusmods.com/skyrimspecialedition/mods/2218
- [x] `ELFX Fixes.esp` https://www.nexusmods.com/skyrimspecialedition/mods/25498
- [x] `Eli_Routa - Non-Stormcloak.esp` https://www.nexusmods.com/skyrimspecialedition/mods/1193
- [x] `Equippable Tomes.esp` https://www.nexusmods.com/skyrimspecialedition/mods/157
- [x] `Faerdham.esp` https://www.nexusmods.com/skyrimspecialedition/mods/10876
- [x] `flaho_shi_eagles_nest_ENG.esp` https://www.nexusmods.com/skyrimspecialedition/mods/9961
- [x] `ForgottenCity.esp` https://www.nexusmods.com/skyrimspecialedition/mods/1179
- [x] `Guards_Armor_Replacer.esp` https://www.nexusmods.com/skyrimspecialedition/mods/22671
- [x] `HopesabandonSSE 1.1.esp` https://www.nexusmods.com/skyrimspecialedition/mods/13870
- [x] `Incaendo_IsengravBarrow.esp` https://www.nexusmods.com/skyrimspecialedition/mods/20584
- [x] `JerallMountainsCitadel.esm` https://www.nexusmods.com/skyrimspecialedition/mods/18175
- [x] `JerallMountainsCitadelPart1.esm` https://www.nexusmods.com/skyrimspecialedition/mods/18175
- [x] `JerallMountainsCitadelPart2.esm` https://www.nexusmods.com/skyrimspecialedition/mods/27331
- [x] `JokerinesRedditDungeon.esp` https://www.nexusmods.com/skyrimspecialedition/mods/17806
- [x] `konahrik_accoutrements.esp` https://www.nexusmods.com/skyrimspecialedition/mods/22206
- [x] `ktWeaponPackSE.esp` https://www.nexusmods.com/skyrimspecialedition/mods/15050
- [x] `Lost Caves - Vanilla Cities.esp` https://www.nexusmods.com/skyrimspecialedition/mods/6137
- [x] `LupineWerewolfPerkExpansion.esp` https://www.nexusmods.com/skyrimspecialedition/mods/16561
- [x] `Mage Outfit Texture Overhaul.esp` https://www.nexusmods.com/skyrimspecialedition/mods/25611
- [x] `mannyBlackRock.esm` https://www.nexusmods.com/skyrimspecialedition/mods/23362
- [x] `mannyDragonhead.esm` https://www.nexusmods.com/skyrimspecialedition/mods/23360
- [x] `mihaildwarvendriller.esp` https://www.nexusmods.com/skyrimspecialedition/mods/27979
- [x] `mihailesobonecolossus.esp` https://www.nexusmods.com/skyrimspecialedition/mods/24521
- [x] `mihailesocenturion.esp` https://www.nexusmods.com/skyrimspecialedition/mods/27354
- [x] `mihailicegolem.esp` https://www.nexusmods.com/skyrimspecialedition/mods/26185
- [x] `mihailmmasithis.esp` https://www.nexusmods.com/skyrimspecialedition/mods/27365
- [x] `MrissiTailOfTroubles.esp` https://www.nexusmods.com/skyrimspecialedition/mods/17810
- [x] `MysticismMagic.esp` https://www.nexusmods.com/skyrimspecialedition/mods/27839
- [x] `NewArmoury.esp` https://www.nexusmods.com/skyrimspecialedition/mods/15394
- [x] `ogFalkreathHauntings.esp` https://www.nexusmods.com/skyrimspecialedition/mods/20733
- [x] `Rayeks_End_SSE_1.0.esp` https://www.nexusmods.com/skyrimspecialedition/mods/8285
- [x] `Reverb and Ambiance Overhaul - Skyrim.esp` https://www.nexusmods.com/skyrimspecialedition/mods/701
- [x] `Riften_Well_House.esp` https://www.nexusmods.com/skyrimspecialedition/mods/2758
- [x] `RiverwoodHuntingCabinSE.esp` https://www.nexusmods.com/skyrimspecialedition/mods/1783
- [x] `RLGBriarHome.esp` https://www.nexusmods.com/skyrimspecialedition/mods/19625
- [x] `Shurrashi's Den.esp` https://www.nexusmods.com/skyrimspecialedition/mods/17115
- [x] `SkjolgaBasin.esp` https://www.nexusmods.com/skyrimspecialedition/mods/25080
- [x] `Svellheim_1.0.esp` https://www.nexusmods.com/skyrimspecialedition/mods/22843
- [x] `Undriel_Everlight.esp` https://www.nexusmods.com/skyrimspecialedition/mods/16043
- [x] `Vjarkell Castle.esp` https://www.nexusmods.com/skyrimspecialedition/mods/23097

**Comment by MacSplody** [comment]
Done in https://github.com/loot/skyrimse/commit/dd13631d7cfaa0896c54b49f3b93e3edcebdfa5b.
