### ISSUE TITLE
Cyclical Interaction

### ISSUE THREAD

**Issue by tardyhaiku** [loot/skyrimse#903]
Constantly getting messages like this 

"Cyclic interaction detected between "ABT SE - Faster Arrows Improved.esp" and "Missing Apprentices CRF Quest Fix.esp":

ABT SE - Faster Arrows Improved.esp
 [Group]
ACF Dignified Elders.esp
 [Master]
IW_DignifiedElders_Patch.esp
 [Group]
AnotherSortingMod_2017-SSE.esp
 [Master]
Book Covers Skyrim.esp
 [Masterlist Load After]
Missing Apprentices CRF Quest Fix.esp
 [Group]
ABT SE - Faster Arrows Improved.esp"

Ever since I added Another Sorting Mod to my install that contains Book Covers Skyrim. Having only one or the other means that the sorting has no issues, but both at the same time (even with the ASM provided patch) does nothing.

[I have tried uninstalling the other mods that it shows as part of the 'cyclical interaction' but it then just shows the next mod on the list as a problem, despite everything working fine when ASM and BCS are not there] 

Any suggestions?

**Comment by tardyhaiku** [comment]
@CptMcSplody Yeah, I wanted ASM further down so that it can do more of its name change things (right now it's getting overridden by a lot, and the mod page recommended putting it in the Late Loaders/High Priority Overrides section). 

I think instead I'll just do a TESSEEdit patch for the names that are getting overridden and call it a day.

Thanks for the help!

**Comment by MacSplody** [comment]
Can't really resolve this at the moment, it would require moving a lot of plugins from the _underrides_ group to the _default_ group. It's possible, but it will require testing.
