### ISSUE TITLE
Distinct Interiors plugin replacement patch flagged.

### ISSUE THREAD

**Issue by Squirrelydood** [loot/skyrimse#913]
The masterlist seems to recognize that one of the Distinct interiors patches was added as it removes the deleted Navmesh warning but still keeps the warning about incompatibility with ELFX and Opulent Thieves Guild. However there are two seperate patches, one is by mnikjom found here https://www.nexusmods.com/skyrimspecialedition/mods/23831 from back in March/may that doesn't actually contain the player home edits and it has a second version that also does not contain the Thieves Guild hall. The latter isn't incompatible with OTG and both do not need the no player homes patch of ELFX.

**Comment by MacSplody** [comment]
Done in https://github.com/loot/skyrimse/commit/f085bc1f88a9d7bfb97929d2893bfc29bc5af200.
@Squirrelydood You'll need to be using the latest version of [LOOT v0.15.1](https://github.com/loot/loot/releases/tag/0.15.1).
