### ISSUE TITLE
Realistic Water Two - Wyrmstooth patch is no longer needed

### ISSUE THREAD

**Issue by aki665** [loot/skyrimse#918]
RealisticWaterTwo - Wyrmstooth.esp is no longer included in the installation of RWT as it isn't needed. RealisticWaterTwo - Waves - Wyrmstooth.esp is still included
![image](https://user-images.githubusercontent.com/26409320/70791226-5cabf400-1d9f-11ea-93e4-87afa61b5922.png)

**Comment by MacSplody** [comment]
Done in https://github.com/loot/skyrimse/commit/65ff052320a7ae1ee59c4a23648fb6af594c2d85.
