### ISSUE TITLE
LotD v5 Incompatibilities List

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#927]
https://www.nexusmods.com/skyrimspecialedition/articles/1494
Some incompatible mods.

_Originally posted by @Xahtax in https://github.com/loot/skyrimse/issues/922#issuecomment-566762999_

---

> This is a running list of mods that have conflicts with Legacy of the Dragonborn V5. They will be removed from the list if and when patches are made, or remain here if they continue to not have support.
> 
> Open Cities Skyrim- Without a patch, the museum does not exist in OCS because it transplants all of the enclosed cities into the open worldspace. We have no plans to patch this because OCS is touchy at best and causes A LOT of insane work to adapt just for the sake of riding a horse in town and saving 1 load door.
> 
> Creation Club- The Legacy team members do not own any CC content and therefore we cannot patch it. If you wish to patch it, contact SirJesto on the Legacy Patch Central page and we may pack your patch in our FOMOD. There already is content for most CC items in the community, most of which look or function better, and many of which are already in Legacy.
> 
> Dawnguard/Clab Volkihar Epilogues- Legacy already has a solution built into it to provide all of the path specific relics from the dawnguard questlines. This mod is not needed and may cause conflicts
> 
> Solitude Skyway- Due to Legacy's overhaul of the arch, Solitude Skyway will require a remodel patch to work around it. There is not way to patch Legacy to work with it.
> 
> The People of Skyrim- An included Tree LOD sticks up in front of the museum and cannot be patched out. You can fix this by re-running DynDOLOD or SSELODGen

**Comment by Xahtax** [comment]
MAS Immersion Patch is not compatible with LotD

**Comment by Xahtax** [comment]
- [x] Open Cities

- [x] Dawnguard/Clan Volkihar Epilogues

- [x] Solitude Skyway

- [x] MAS Immersion patch

Won't add the Creation Club and The People of Skyrim

**Comment by MacSplody** [comment]
> Won't add the Creation Club and The People of Skyrim

That's fine, a link to compatibility list could be added to LotD to cover those.

```yaml
  - name: 'LegacyoftheDragonborn.esm'
    msg:
      - <<: *compatNotes
        subs: [ 'https://www.nexusmods.com/skyrimspecialedition/articles/1494' ]
```

**Comment by Xahtax** [comment]
I added it.

**Comment by MacSplody** [comment]
Done in https://github.com/loot/skyrimse/commit/8595b127fd54cc8c9cd39bea2cb3d801c346e224

**Comment by Xahtax** [comment]
Those mods add relics that are already included in legacy. The main mod is fine, though.
```
Lore Weapon Expansion - Daedric Crescent.esp
Lore Weapon Expansion - Goldbrand.esp
Lore Weapon Expansion - Relics of the Crusader.esp
```
