### ISSUE TITLE
Patch recognition failure for True Storms, Obsidian Weathers, Wet & Cold

### ISSUE THREAD

**Issue by cagelight** [loot/skyrimse#942]
![4e7213e79c31f2bde9a46b0888d94403](https://user-images.githubusercontent.com/3761279/71406121-4d317400-2605-11ea-8a53-c0adc6b5a805.png)

These messages are shown despite me having the True Storms + Obsidian Weathers + Wet & Cold patch from [here](https://www.nexusmods.com/skyrimspecialedition/mods/15632) (Obsidian Weathers patch option is in the installer, `Obsidian_TS_Wet&Cold_Patch.esp`)

**Comment by MacSplody** [comment]
`Obsidian_TS_Wet&Cold_Patch.esp` only patches conflicts for `WetandCold.esp`.

![image](https://user-images.githubusercontent.com/1944639/71406667-d0b48a80-2630-11ea-8dc7-8e76fd9932a8.png)

You'll still need another patch for just `TrueStormsSE.esp` and `Obsidian Weathers.esp`.
You can use either the official [Obsidian weathers](https://www.nexusmods.com/skyrimspecialedition/mods/12125?tab=files) patch `True Storms - Obsidian Weathers - Patch .esp` or the 3rd party patch [Obsidian Weathers - TrueStorms Merged Compatibility SSE](https://www.nexusmods.com/skyrimspecialedition/mods/17198).

![image](https://user-images.githubusercontent.com/1944639/71406978-a2837a80-2631-11ea-8bb7-9045009058ea.png)

**Comment by cagelight** [comment]
In that case, there might still be an issue because LOOT claims incompatibility between `True Storms - Obsidian Weathers - Patch .esp` and `Obsidian_TS_Wet&Cold_Patch.esp`. I haven't tried the other plugin yet though, trying that now.

**Comment by MacSplody** [comment]
> In that case, there might still be an issue because LOOT claims incompatibility between `True Storms - Obsidian Weathers - Patch .esp` and `Obsidian_TS_Wet&Cold_Patch.esp`. I haven't tried the other plugin yet though, trying that now.

Yeah I'll have a look at that, it might be okay to use it with both.

**Comment by cagelight** [comment]
The other patch you suggested does seem to work fine, and LOOT has no issues with it.

**Comment by MacSplody** [comment]
I've looked at the patch requirements. It just lists a True Storms & Obsidian patch, not a specific one. It should be fine with either patch, I'll remove the incompatibility message
between `True Storms - Obsidian Weathers - Patch .esp` and `Obsidian_TS_Wet&Cold_Patch.esp`.

**Comment by MacSplody** [comment]
Done in https://github.com/loot/skyrimse/commit/b0ebec667bc4c189e6d0a63f12432792fbbf6f1d.
