### ISSUE TITLE
Luminosity - Skyrim is Lit Edition is sorted too high

### ISSUE THREAD

**Issue by barcharcraz** [loot/skyrimse#944]
I think this needs to be in the same group as the other flavors of Luminosity

**Comment by MacSplody** [comment]
While it does include changes from the previous versions of Luminosity.
It's not going to be as easy as putting it in the same group as previous versions of Luminosity.
It also adds new light bulbs to worldspace cells.

![image](https://user-images.githubusercontent.com/1944639/71452353-33666d00-277c-11ea-802e-4fd77de228f9.png)

This will lead to it reverting Worldspace Cell settings for mods such as Open Cities.

![image](https://user-images.githubusercontent.com/1944639/71452438-049cc680-277d-11ea-89ab-425f433d517a.png)

**Comment by MacSplody** [comment]
@barcharcraz That version has been taken down, I'll close this for now.
It can be reopened if that version is ever rereleased.

![image](https://user-images.githubusercontent.com/1944639/72682654-50fecc00-3ac7-11ea-9958-f38651501dbb.png)
