### ISSUE TITLE
Obscure's College of Winterhold Version 1.5

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#953]
Version 1.5 is here with new load order rules. Both the main plugin and the cell settings plugin are labeled with "Version: 1.5.00" in the description.
Load order rules [are outlined here](https://www.nexusmods.com/skyrimspecialedition/articles/787).

_Originally posted by @SomethingObscure in https://github.com/loot/skyrimse/issues/517#issuecomment-569316617_

**`OCW_Obscure's_CollegeofWinterhold.esp`**
- [x] Add missing requirement message for `OCW_CellSettings.esp`. (Set as error)
- [x] Update Cleaning Info.

---

> If a patch is provided, it doesn't matter if OCW or the other mod are loaded first.  LOOT﻿ will sort OCW according to my suggested rules, but it's best to always verify.
> 
> Recommended Load Order:
>    ▪  The Unofficial Skyrim Special Edition Patch
>    ▪  Skyrim Project Optimization
>    ▪  Interesting NPCs
>    ▪  Cutting Room Floor
>    ▪  OCW_Obscure's_CollegeofWinterhold.esp
>    ▪  Any mod which edits Winterhold in any way, with their OCW patch (if applicable) loaded directly below them
>    ▪  ...
>    ▪  Unique Region Names - Conflicts are intentional and harmless.
>    ▪  OCW_CellSettings.esp
>    ▪  Realistic Water 2
>    ▪  Generated plugins such as bashed patches or DynDOLOD
>    ▪  Other mods that edit the Tamriel Worldspace
> 
> Notes:
>    ▪  The ELFX﻿ patch may be placed before or after ELFXEnhancer.esp or ELFX - Hardcore.esp. It doesn't matter. What matters is that OCW_CellSettings.esp is loaded last.
>    ▪  If OCW_LightingPatch_Brighter.esp or OCW_LightingPatch_Darker.esp are in use, they may be loaded anywhere after the main OCW plugin.
>    ▪  If OCW_MusicPatch_VanillaPlus.esp is in use, it likewise may be loaded anywhere after the main OCW plugin.
>    ▪  Unlike previous versions of OCW, the Sounds of Skyrim patch just needs to be loaded after Sounds of Skyrim and OCW.

- [x] Update afters.
  - [x] Add version checks.
  - [x] Add ESM check.

---

- [x] Update patch messages
  #### Not included with v1.5.00
  - [x] `OCW_ELE_FEPatch.esp`
  - [x] `OCW_ELEA_FEPatch.esp`
  - [x] `OCW_ICE_FEPatch.esp`
  - [x] `OCW_LAR_FEPatch.esp`
  - [x] `OCW_LAR_RoB_MergedFEPatch.esp`
  - [x] `OCW_LLO_FEPatch.esp`
  - [x] `OCW_MCMSfA_FEPatch.esp`
  - [x] `OCW_SoS_MCMSfA_MergedFEPatch.esp`
  - [x] `OCW_SoS_SmMM_MergedFEPatch.esp`
  - [x] `OCW_TW_FEPatch.esp`
  - [x] `OCW_WCH_FEPatch.esp`
  - [x] `SoulMusic_OCoW_Patch.esp`
  - [x] `tpos_Obscures_CollegeofWinterholdPatch_Full.esp`
  #### New patches for v1.5.00
  - [x] `OCW_A-aNAoM_FEPatch.esp`
  - [x] `OCW_ACE_FEPatch.esp`
  - [x] `OCW_AO_FEPatch.esp`
  - [x] `OCW_AR_FEPatch.esp`
  - [x] `OCW_AR_RoB_FEPatch.esp`
  - [x] `OCW_AtTotTB_FEPatch.esp`
  - [x] `OCW_BCS_FEPatch.esp`
  - [x] `OCW_BSL_FEPatch.esp`
  - [x] `OCW_ECW_FEPatch.esp`
  - [x] `OCW_FM_FEPatch.esp`
  - [x] `OCW_KA_FEPatch.esp`
  - [x] `OCW_LLO-SiLE_FEPatch.esp`
  - [x] `OCW_MaMO_FEPatch.esp`
  - [x] `OCW_MC_FEPatch.esp`
  - [x] `OCW_ToK_FEPatch.esp`
  - [x] `OCW_tPoS2F_FEPatch.esp`
  - [x] `OCW_tPoS2P_FEPatch.esp`
  #### Included in v1.4 & v1.5
  - [x] `OCW_3DTaP_FEPatch.esp`
  - [x] `OCW_AMM_FEPatch.esp`
  - [x] `OCW_AMM-SE_FEPatch.esp`
  - [x] `OCW_BCS-LL_FEPatch.esp`
  - [x] `OCW_BDS_FEPatch.esp`
  - [x] `OCW_BMA_FEPatch.esp`
  - [x] `OCW_BSFWF_FEPatch.esp`
  - [x] `OCW_CM_FEPatch.esp`
  - [x] `OCW_DFS_FEPatch.esp`
  - [x] `OCW_ELFX_FEPatch.esp`
  - [x] `OCW_ELFXE_FEPatch.esp`
  - [x] `OCW_ICNs_OE_FEPatch.esp`
  - [x] `OCW_IL_FEPatch.esp`
  - [x] `OCW_iN_FEPatch.esp`
  - [x] `OCW_iNE_FEPatch.esp`
  - [x] `OCW_LotD_FEPatch.esp`
  - [x] `OCW_LWP_FEPatch.esp`
  - [x] `OCW_MEL_FEPatch.esp`
  - [x] `OCW_ML_FEPatch.esp`
  - [x] `OCW_MLM_FEPatch.esp`
  - [x] `OCW_MLU_FEPatch.esp`
  - [x] `OCW_MMC_FEPatch.esp`
  - [x] `OCW_MToT_FEPatch.esp`
  - [x] `OCW_RLS_FEPatch.esp`
  - [x] `OCW_RoB_FEPatch.esp`
  - [x] `OCW_SC_FEPatch.esp`
  - [x] `OCW_SFCO_FEPatch.esp`
  - [x] `OCW_SoS_FEPatch.esp`
  - [x] `OCW_SPO_FEPatch.esp`
  - [x] `OCW_SR_FEPatch.esp`
  - [x] `OCW_TGCoW_FEPatch.esp`
  - [x] `OCW_TGCs_FEPatch.esp`
  - [x] `OCW_WACCF_FEPatch.esp`
  - [x] `OCW_WR2_FEPatch.esp`

---

> OCW is incompatible with the following mods (patches will not be made)
>    ▪  Apepi's Better College of Winterhold
>    ▪  Better College Students Room
>    ▪  College Grounds
>    ▪  College of Winterhold Upgraded
>    ▪  Especially Special Winterhold
>    ▪  Fix that Winterhold Bridge (Currently Unavailable) - Will result in massive light glitching if used with OCW.
>    ▪  A Follower Pack
>    ▪  Guards of Skyrim - College Guards
>    ▪  Immersive College of Winterhold
>    ▪  Improved Eyes Skyrim - Causes one of my new NPCs to glitch. So far I haven't been able to fix it.
>    ▪  Juniper's College of Winterhold
>    ▪  Mage College Dorm Doors - OCW already contains doors and ownership settings
>    ▪  Magic College Music - Songs for Academy﻿﻿ - OCW includes its own music
>    ▪  Magical College of Winterhold
>    ▪  Okata's College of Winterhold - Thriving Edition
>    ▪  Toberone's Winterhold College﻿
> 
> OCW has minor incompatibilities with the following mods
>    ▪  Cloaks and Capes Fixes﻿ - A tanning rack added by this mod is hidden behind some clutter which OCW adds
>    ▪  Marvelous Mirabelle﻿ - Conflict is narrative, not technical
>    ▪  College of Winterhold Bridge Fix - This mod has ITM records and should be cleaned in xEdit prior to using it with OCW.
>    ▪  Psijic Teleport Spells - This mod has ITM records and should be cleaned in xEdit prior to using it with OCW.
>    ▪  There are minor item placement issues with the Creation Club modules Wild Horses and Arcane Archer.

- [x] Add inc:
  - [x] [Magic College Music - Songs for Academy](https://www.nexusmods.com/skyrimspecialedition/mods/1893) `MagiCollege.esp` incompatible with OCW 1.5.00+.

---

**`OCW_CellSettings.esp`**

- [x] Add cleaning info.

- [x] Add afters:
  - [x] `ELE_SSE.esp`
  - [x] `ELFXEnhancer.esp`
  - [x] `ELFX - Hardcore.esp`
  - [x] `Luminosity - Lightweight Lighting.esp`
  - [x] `Luminosity Lighting Overhaul.esp`
  - [x] `Luminosity - Skyrim is Lit Edition.esp`
  - [x] `Immersive Citizens - AI Overhaul.esp`
  - [x] `Immersive Music.esp`
  - [x] `Soulmancer Soundtrack - NoVindDun.esp`
  - [x] `Unique Region Names.esp`

Add Group:
- [x] Add to `High Priority Overrides` or `Late Loaders`.

**Comment by SomethingObscure** [comment]
Thanks so much, Cpt!

**Comment by MacSplody** [comment]
@SomethingObscure You're welcome.

**Comment by SomethingObscure** [comment]
If OCW is flagged as a master, it must still load after [Interesting NPCs](https://www.nexusmods.com/skyrimspecialedition/mods/29194).

**Comment by MacSplody** [comment]
> If OCW is flagged as a master, it must still load after [Interesting NPCs](https://www.nexusmods.com/skyrimspecialedition/mods/29194).

Yeah that's fine, I'll update the condition to check if they're both masters.

---

Default sorting places `OCW_AR_RoB_FEPatch.esp` before `OCW_MC_FEPatch.esp`
Will need an after added.

![image](https://user-images.githubusercontent.com/1944639/71548894-bf5edb80-29ac-11ea-9b20-fd9db5d3df74.png)

**Comment by MacSplody** [comment]
`MCWT_AWizardsWalk.esp` is included with `OCW_Obscure's_CollegeofWinterhold.esp` v1.5

![image](https://user-images.githubusercontent.com/1944639/71553045-0aeea500-2a00-11ea-9b5c-567c7ba671db.png)

**Comment by SomethingObscure** [comment]
OCW 1.5.02 now includes the injected records from the [SPO](https://www.nexusmods.com/skyrimspecialedition/mods/14084) patch.  The patch is obsolete.
A patch for [Tamrielic Culture](https://www.nexusmods.com/skyrimspecialedition/mods/11418) has been added.

**Comment by MacSplody** [comment]
SPO esp versions are incompatible with ESM flagged version of OCW.
![image](https://user-images.githubusercontent.com/1944639/71562665-948f8880-2a7b-11ea-8a56-7d7395819b22.png)

**Comment by SomethingObscure** [comment]
Patches have been added for [EBQO](https://www.nexusmods.com/skyrimspecialedition/mods/159) and [QaiS](https://www.nexusmods.com/skyrimspecialedition/mods/18416) in version 1.5.03.

**Comment by SomethingObscure** [comment]
Hi Cpt. [Guardian Spectres](https://www.nexusmods.com/skyrimspecialedition/mods/30772) has 44 ITMs and should be cleaned before using it with OCW.  (Reported to me by Spasticon1.)

**Comment by MacSplody** [comment]
> 
> 
> Patches have been added for [EBQO](https://www.nexusmods.com/skyrimspecialedition/mods/159) and [QaiS](https://www.nexusmods.com/skyrimspecialedition/mods/18416) in version 1.5.03.

> 
> 
> Hi Cpt. [Guardian Spectres](https://www.nexusmods.com/skyrimspecialedition/mods/30772) has 44 ITMs and should be cleaned before using it with OCW. (Reported to me by Spasticon1.)

Thanks for the info @SomethingObscure 

Closing as the main updates are done, but you can still leave comments here if anything needs to be changed.

**Comment by SomethingObscure** [comment]
I went ahead and made a patch for [Improved Eyes Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/9141) so if there was any conflict warning, that can be removed.  Sadly, to complicate things, the conflict is in only one of several versions of Improved Eyes, and they all have the same plugin name.  Players will get the bug that this patch solves if they select "Complete" and then "Default Only" in the installer.

**Comment by MacSplody** [comment]
> 
> 
> I went ahead and made a patch for [Improved Eyes Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/9141) so if there was any conflict warning, that can be removed. Sadly, to complicate things, the conflict is in only one of several versions of Improved Eyes, and they all have the same plugin name. Players will get the bug that this patch solves if they select "Complete" and then "Default Only" in the installer.

A checksum for it's crc could be used, if that plugin was modified it would break the check though.

**Comment by SomethingObscure** [comment]
Hi Cpt.  New patches are up.

[BadGremlin's Collection](https://www.nexusmods.com/skyrimspecialedition/mods/15092) - Only covers the complete version
[Humans, Mer, and Beastfolk](https://www.nexusmods.com/skyrimspecialedition/mods/24174) - New facegen for my new NPCs
[Realistic Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/14384) - Mostly forwards navmesh to compensate for this mod's 77 ITMs.
[Sounds of Skyrim Complete](https://www.nexusmods.com/skyrimspecialedition/mods/30658) - Same as the old patch, but for Arthmoor's port.
[Flora Respawn Fix](https://www.nexusmods.com/skyrimspecialedition/mods/13186) - Optional. Adds the fix to the new harvestables.
