### ISSUE TITLE
New patches for OCW version 1.5.03

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#963]
Patches have been added for [EBQO](https://www.nexusmods.com/skyrimspecialedition/mods/159) and [QaiS](https://www.nexusmods.com/skyrimspecialedition/mods/18416) in version 1.5.03.

_Originally posted by @SomethingObscure in https://github.com/loot/skyrimse/issues/953#issuecomment-569669106_

**Comment by SomethingObscure** [comment]
The patch for EBQO has been discontinued.  It never worked correctly, and 1.5.07 removes the need for it.

**Comment by MacSplody** [comment]
Done in https://github.com/loot/skyrimse/commit/806ee7b0bdedf1415d9919668e0716b28f652185.
