### ISSUE TITLE
Vikings Weapenory LL plugin needs bash tags

### ISSUE THREAD

**Issue by barcharcraz** [loot/skyrimse#965]
The plugin: Vikings Weaponry LL - Johnskyrim.esp

from https://www.nexusmods.com/skyrimspecialedition/mods/14409/?tab=description

needs bash tags

I believe it just needs a relev tag

**Comment by MacSplody** [comment]
@barcharcraz Thanks, that will be added when https://github.com/loot/skyrimse/pull/929 is merged into v0.15.

**Comment by MacSplody** [comment]
Done in https://github.com/loot/skyrimse/commit/85cf67dfa82aaed68ac05fc383e9e395b1e7d9eb.
