### ISSUE TITLE
Racial Body Morphs and Imperious

### ISSUE THREAD

**Issue by Harry-894** [loot/skyrimse#968]
LOOT gives an error for racial body morphs {https://www.nexusmods.com/skyrimspecialedition/mods/20684?tab=files} if im using imperious ... however theres a patch on the mods page that works very well in my case ... had a full play-through with these mods installed without any issues.

**Comment by MacSplody** [comment]
> LOOT gives an error for racial body morphs {[https://www.nexusmods.com/skyrimspecialedition/mods/20684?tab=files}](https://www.nexusmods.com/skyrimspecialedition/mods/20684?tab=files%7D) if im using imperious ... however theres a patch on the mods page that works very well in my case ... had a full play-through with these mods installed without any issues.

Those are replacer plugins, not patches, it won't cause any issues because of the load order.
It could be made clearer that those are replacer plugins.

![image](https://user-images.githubusercontent.com/1944639/71642967-16b1c400-2cab-11ea-8b24-013ae5498023.png)

**Comment by Harry-894** [comment]
ok, thank you for the reply .... maybe if the imperious version is detected it should say the other one is not needed ?

**Comment by MacSplody** [comment]
> ok, thank you for the reply .... maybe if the imperious version is detected it should say the other one is not needed ?

I've added changes in https://github.com/loot/skyrimse/commit/fd4031b37f52222144a138483991c44353a8bc23, you can update your masterlist to see the changes. 
- It will now inform the user to only use one version of Racial Body Morphs.
- And to use the Imperious version if that's is active.
- Check to make sure the required meshes are installed.

**Comment by Harry-894** [comment]
well i just noticed the imperious version doesnt have the meshes included ... only the regular one does ... the author shouldve probably just renamed it to be a replacer instead of having a different name ... anyways thanks for the update.

**Comment by MacSplody** [comment]
> the author shouldve probably just renamed it to be a replacer instead of having a different name

Well it's easier for LOOT to check this way, but yeah they could have put the meshes in all versions.

> anyways thanks for the update.

You're welcome, thanks for the feedback.
