### ISSUE TITLE
Add a message for the Undeath CACO patch

### ISSUE THREAD

**Issue by Xahtax** [loot/skyrimse#970]
https://www.nexusmods.com/skyrimspecialedition/mods/29825 fixes an issue between Undeath and CACO, a Loot message should link to the patch. But I could be wrong about that.

**Comment by SphericalPinniped** [comment]
Agreed. Currently, the LOOT message that appears under Undeath.esp as  reads "Complete Alchemy & Cooking Overhaul is not fully compatible with this mod. Complete Alchemy & Cooking Overhaul adds a flora respawn fix to several records that Undeath modifies. A patch is recommended to ensure correct functionality for both mods."

To verify that this patch is valid to link, I looked at the Patch in xEdit and it both reimplements the Flora Fix spawn scripts to the two records Undeath touches as well as edits Undeath's Leveled Lists to ensure that you can get both the Undeath pearl drops as well as the other drops from Kryptopyr's leveled lists.

**Comment by MacSplody** [comment]
Yeah that looks fine, the semi compatible message in Undeath can be replaced with a 3rd party patch message.

**Comment by MacSplody** [comment]
Done in https://github.com/loot/skyrimse/commit/d3c6fcf19557d31ff0024a80ce1d8b6a67da56c6, Thanks for the feedback @Xahtax @SphericalPinniped
