### ISSUE TITLE
Lore Weapon Expansion Addons are incompatible with LotD v5

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#985]
Those mods add relics that are already included in legacy. The main mod is fine, though.
```
Lore Weapon Expansion - Daedric Crescent.esp
Lore Weapon Expansion - Goldbrand.esp
Lore Weapon Expansion - Relics of the Crusader.esp
```

_Originally posted by @Xahtax in https://github.com/loot/skyrimse/issues/927#issuecomment-571393288_

---

~~- [ ] Add `alreadyInX` message to Lore Weapon Expansion addons.~~
- [x] Add inc for Lore Weapon Expansion addons and LotDv5.

**Comment by Xahtax** [comment]
The incompatibility message would fit better. Lore weapon expansion is not included, they just use the same relic names.

**Comment by MacSplody** [comment]
> The incompatibility message would fit better. Lore weapon expansion is not included, they just use the same relic names.

Right, updated the issue.

**Comment by MacSplody** [comment]
Done in https://github.com/loot/skyrimse/commit/5311f1f1a2d4af2c1ecd6d86b0c0b35c2d859be6
