### ISSUE TITLE
Obscure's CW patches added in v1.5.09

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#992]
- [x] [BadGremlin's Collection](https://www.nexusmods.com/skyrimspecialedition/mods/15092) - Only covers the complete version
- [x] [Humans, Mer, and Beastfolk](https://www.nexusmods.com/skyrimspecialedition/mods/24174) - New facegen for my new NPCs
- [x] [Realistic Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/14384) - Mostly forwards navmesh to compensate for this mod's 77 ITMs.
- [x] [Sounds of Skyrim Complete](https://www.nexusmods.com/skyrimspecialedition/mods/30658) - Same as the old patch, but for Arthmoor's port.
- [x] [Flora Respawn Fix](https://www.nexusmods.com/skyrimspecialedition/mods/13186) - Optional. Adds the fix to the new harvestables.

_Originally posted by @SomethingObscure in https://github.com/loot/skyrimse/issues/953#issuecomment-573310237_

---

- [x] Flora Respawn Fix's patch has been updated and should not be considered optional.  Without the patch, the transforming Arch-Mage's quarters can break.
- [x] [Interesting NPCs](https://www.nexusmods.com/skyrimspecialedition/mods/29194?tab=files)      
  Not a full patch. Only forwards persistent reference flags where needed.
- [x] [Lanterns of Skyrim II](https://www.nexusmods.com/skyrimspecialedition/mods/30817)
   Only needed for the _LoS II - Tamriel Master Lights.esp_ plugin.
- [x] [Scrollwriting in Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/28294)
  Moves scrollwriting table and adds new elements.
- [x] **Winterhold Restored - JKs Skyrim Patch.esp**
   A patch for the patch.
- [x] If **OCW_WR2_JK_FEPatch.esp** is installed, then **OCW_WR2_FEPatch.esp** isn't needed.

**Comment by SomethingObscure** [comment]
I have some patch updates for you.

- Flora Respawn Fix's patch has been updated and should not be considered optional.  Without the patch, the transforming Arch-Mage's quarters can break.
- [Interesting NPCs](https://www.nexusmods.com/skyrimspecialedition/mods/29194?tab=files) - Not a full patch. Only forwards persistent reference flags where needed.
- [Lanterns of Skyrim II](https://www.nexusmods.com/skyrimspecialedition/mods/30817) - Only needed for the _LoS II - Tamriel Master Lights.esp_ plugin.
- [Scrollwriting in Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/28294) - Moves scrollwriting table and adds new elements.
- **Winterhold Restored - JKs Skyrim Patch.esp** - A patch for the patch. If **OCW_WR2_JK_FEPatch.esp** is installed, then **OCW_WR2_FEPatch.esp** isn't needed.
- [Solitude Temple Frescoes 2019](https://www.nexusmods.com/skyrimspecialedition/mods/29695) - Created several patches for a few different versions. This port author has made eight different versions of this plugin, half with compacted form IDs, and all of them have the same name. I've already spent too much time dealing with this decision, so I don't recommend you spend any. I'm just adding it here so it's clear I haven't forgotten it.

**Comment by MacSplody** [comment]
> [Solitude Temple Frescoes 2019](https://www.nexusmods.com/skyrimspecialedition/mods/29695) Created several patches for a few different versions. This port author has made eight different versions of this plugin, half with compacted form IDs, and all of them have the same name. I've already spent too much time dealing with this decision, so I don't recommend you spend any. I'm just adding it here so it's clear I haven't forgotten it.

@SomethingObscure Yeah I've left it out as it's too much of a headache to figure out the right versions, the rest is done now.
