### ISSUE TITLE
Dawnguard Arsenal SSE - Bash Tags

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#994]
Mod name: Dawnguard Arsenal SSE

Link: https://www.nexusmods.com/skyrimspecialedition/mods/25094

Version: 1

Should have bash tags: {{BASH:Actors.CombatStyle,Actors.Stats,Delev,Invent,NPC.Class,Sound,Stats}}

![DGA](https://user-images.githubusercontent.com/26516348/72315240-35ba4800-36e6-11ea-8237-b58520ada31d.PNG)

**Comment by MacSplody** [comment]
@Sabre142 Yeah that looks fine, it might need the _**Keywords**_ and _**Graphics**_ tags as well.

![image](https://user-images.githubusercontent.com/1944639/72315632-64570500-368b-11ea-816a-5d35016a3091.png)


![image](https://user-images.githubusercontent.com/1944639/72315705-a4b68300-368b-11ea-8743-05115931edb4.png)

Can you add those in a pull request?

**Comment by MacSplody** [comment]
Done in https://github.com/loot/skyrimse/commit/94c0a5f466bda66193c34defa30a75e7018c9b9d
